import type {
    BrandGuideline,
    BrandGuidelineSection,
    BriefTemplate,
    Campaign,
    CampaignAsset,
    CampaignChannel,
    CampaignKpi,
    CreativeBrief,
    CreativeReview,
} from "@/types";

// ─── Brief Templates ─────────────────────────────────────────

export const MOCK_BRIEF_TEMPLATES: BriefTemplate[] = [
    {
        id: "bt-1",
        organization_id: "org-1",
        name: "Product Launch Brief",
        description:
            "Standard template for product launches with media, social, and experiential channels",
        brief_type: "product",
        template_sections: {
            overview: true,
            audience: true,
            scope: true,
            budget: true,
            timeline: true,
            kpis: true,
        },
        default_kpis: [
            { metric: "Brand Awareness Lift", target: 15, measurement_method: "Pre/post survey" },
            {
                metric: "Earned Media Value",
                target: 500000,
                measurement_method: "Media monitoring",
            },
        ],
        default_deliverable_manifest: [
            { type: "Hero Video", quantity: 1, specs: "16:9, 60s" },
            { type: "Social Cutdowns", quantity: 6, specs: "1:1, 9:16, 15s each" },
            { type: "Key Art", quantity: 3, specs: "Horizontal, vertical, square" },
        ],
        is_active: true,
        usage_count: 12,
        created_by: null,
        created_at: "2025-06-01T00:00:00Z",
        updated_at: "2026-01-15T00:00:00Z",
    },
    {
        id: "bt-2",
        organization_id: "org-1",
        name: "Social Campaign Brief",
        description:
            "Quick-turn social media campaign template with platform-specific deliverables",
        brief_type: "social",
        template_sections: { overview: true, audience: true, scope: true, timeline: true },
        default_kpis: [
            { metric: "Engagement Rate", target: 4.5, measurement_method: "Platform analytics" },
            { metric: "Reach", target: 1000000, measurement_method: "Platform analytics" },
        ],
        default_deliverable_manifest: [
            { type: "Static Posts", quantity: 10, specs: "1080x1080" },
            { type: "Reels/Stories", quantity: 5, specs: "9:16, 15-30s" },
        ],
        is_active: true,
        usage_count: 24,
        created_by: null,
        created_at: "2025-08-10T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "bt-3",
        organization_id: "org-1",
        name: "Event Activation Brief",
        description:
            "Experiential marketing activation brief with spatial, digital, and printed deliverables",
        brief_type: "experiential",
        template_sections: {
            overview: true,
            audience: true,
            scope: true,
            budget: true,
            timeline: true,
            kpis: true,
        },
        default_kpis: [
            { metric: "Foot Traffic", target: 5000, measurement_method: "Sensor counting" },
            { metric: "Social Mentions", target: 2000, measurement_method: "Social listening" },
        ],
        default_deliverable_manifest: [
            { type: "Environmental Graphics", quantity: 8, specs: "Large format print" },
            { type: "Digital Interactives", quantity: 2, specs: "Touchscreen, 4K" },
            { type: "Branded Merchandise", quantity: 3, specs: "T-shirts, totes, stickers" },
        ],
        is_active: true,
        usage_count: 8,
        created_by: null,
        created_at: "2025-09-20T00:00:00Z",
        updated_at: "2026-01-20T00:00:00Z",
    },
];

// ─── Brand Guidelines ────────────────────────────────────────

export const MOCK_BRAND_GUIDELINES: BrandGuideline[] = [
    {
        id: "bg-1",
        organization_id: "org-1",
        parent_id: null,
        brand_kit_id: "bk-rilla",
        name: "Rilla — Master Brand",
        description: "Primary brand guidelines for all Rilla communications",
        brand_level: "primary",
        markets: ["US", "UK", "CA"],
        status: "published",
        current_version: 3,
        created_by: null,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-01-10T00:00:00Z",
    },
    {
        id: "bg-2",
        organization_id: "org-1",
        parent_id: "bg-1",
        brand_kit_id: null,
        name: "Rilla — Enterprise Sub-Brand",
        description: "Enterprise product line guidelines, inherits from master",
        brand_level: "sub_brand",
        markets: ["US"],
        status: "published",
        current_version: 1,
        created_by: null,
        created_at: "2025-07-15T00:00:00Z",
        updated_at: "2025-12-01T00:00:00Z",
    },
    {
        id: "bg-3",
        organization_id: "org-1",
        parent_id: null,
        brand_kit_id: "bk1",
        name: "Coachella — Event Brand",
        description: "Festival brand guidelines including environmental and digital standards",
        brand_level: "primary",
        markets: ["US"],
        status: "published",
        current_version: 5,
        created_by: null,
        created_at: "2024-11-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "bg-4",
        organization_id: "org-1",
        parent_id: "bg-3",
        brand_kit_id: null,
        name: "Coachella — EMEA Variant",
        description: "European market adaptations for Coachella brand",
        brand_level: "market_variant",
        markets: ["UK", "DE", "FR"],
        status: "draft",
        current_version: 0,
        created_by: null,
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-02-15T00:00:00Z",
    },
];

export const MOCK_BRAND_GUIDELINE_SECTIONS: BrandGuidelineSection[] = [
    {
        id: "bgs-1",
        brand_guideline_id: "bg-1",
        section_type: "visual_identity",
        title: "Visual Identity",
        description: "Logo usage, clear space, and incorrect usage examples",
        content: {
            logo_variants: ["full_lockup", "icon_only", "wordmark", "monochrome"],
            minimum_size: "24px height",
            clear_space: "1x logo height on all sides",
            incorrect_usage: ["stretching", "rotation", "color_alteration", "drop_shadow"],
        },
        display_order: 0,
        is_inherited: false,
        overrides_parent_section_id: null,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-01-10T00:00:00Z",
    },
    {
        id: "bgs-2",
        brand_guideline_id: "bg-1",
        section_type: "color_system",
        title: "Color System",
        description: "Primary, secondary, and accent palettes with usage rules",
        content: {
            primary_palette: [
                { name: "Rilla Purple", hex: "#8B5CF6", usage: "Primary CTA, headers" },
            ],
            secondary_palette: [
                { name: "Deep Night", hex: "#1E1033", usage: "Backgrounds, body text" },
            ],
            gradient_rules: "Primary to accent gradient at 135°",
            contrast_ratios: { minimum_text: "4.5:1", minimum_large_text: "3:1" },
        },
        display_order: 1,
        is_inherited: false,
        overrides_parent_section_id: null,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-01-10T00:00:00Z",
    },
    {
        id: "bgs-3",
        brand_guideline_id: "bg-1",
        section_type: "typography",
        title: "Typography",
        description: "Font families, weights, and size scale",
        content: {
            font_families: [{ name: "Inter", role: "primary", weights: [400, 500, 600, 700] }],
            size_scale: {
                xs: "12px",
                sm: "14px",
                base: "16px",
                lg: "18px",
                xl: "24px",
                "2xl": "32px",
                "3xl": "48px",
            },
            line_heights: { tight: 1.2, normal: 1.5, relaxed: 1.75 },
        },
        display_order: 2,
        is_inherited: false,
        overrides_parent_section_id: null,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-01-10T00:00:00Z",
    },
    {
        id: "bgs-4",
        brand_guideline_id: "bg-1",
        section_type: "tone_and_voice",
        title: "Tone & Voice",
        description: "Brand personality, tone dimensions, and vocabulary",
        content: {
            personality: ["confident", "innovative", "approachable", "data-driven"],
            tone_dimensions: { formality: 0.6, playfulness: 0.4, authority: 0.8, warmth: 0.5 },
            prohibited_terms: ["cheap", "basic", "simple"],
        },
        display_order: 3,
        is_inherited: false,
        overrides_parent_section_id: null,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-01-10T00:00:00Z",
    },
];

// ─── Creative Briefs ─────────────────────────────────────────

export const MOCK_CREATIVE_BRIEFS: CreativeBrief[] = [
    {
        id: "cb-1",
        organization_id: "org-1",
        template_id: "bt-1",
        brand_guideline_id: "bg-1",
        brand_guideline_version_id: null,
        project_id: null,
        deal_id: null,
        company_id: null,
        title: "Rilla AI Coach — Q2 Product Launch",
        brief_type: "product",
        objective_summary:
            "Drive awareness and adoption of Rilla AI Coach 2.0 among enterprise sales leaders",
        status: "active",
        business_objectives: [
            "Increase product trials by 40%",
            "Generate 500 MQLs",
            "Achieve $2M pipeline",
        ],
        success_criteria: [
            "Trial signup rate > 15%",
            "Campaign ROI > 3:1",
            "Brand awareness lift > 10%",
        ],
        competitive_context:
            "Gong and Chorus dominating paid search; opportunity in organic/experiential",
        target_segments: [
            {
                name: "VP Sales",
                demographic: "B2B SaaS, 100-1000 employees",
                psychographic: "Data-driven, ROI-focused",
            },
            {
                name: "Sales Enablement",
                demographic: "B2B Enterprise",
                psychographic: "Process-oriented, training-focused",
            },
        ],
        personas: [
            {
                name: "Data-Driven Dana",
                role: "VP Sales",
                pain_point: "No visibility into field rep conversations",
            },
        ],
        deliverable_manifest: [
            { type: "Hero Video", quantity: 1, specs: "16:9, 90s", channel: "website" },
            { type: "Social Cutdowns", quantity: 8, specs: "1:1 and 9:16, 15s", channel: "social" },
            { type: "Key Art", quantity: 4, specs: "Multi-format", channel: "all" },
            { type: "Email Templates", quantity: 3, specs: "Responsive HTML", channel: "email" },
            {
                type: "Landing Page",
                quantity: 1,
                specs: "Responsive, CTA-optimized",
                channel: "website",
            },
        ],
        channels: ["social_meta", "social_linkedin", "email", "website", "display"],
        markets: ["US", "UK"],
        tone_direction: "Confident, data-driven, slightly provocative — challenge the status quo",
        visual_direction:
            "Bold purple gradients, clean data visualizations, real product screenshots",
        total_budget: 250000,
        budget_breakdown: [
            { category: "Video Production", amount: 80000 },
            { category: "Design & Creative", amount: 45000 },
            { category: "Media Buying", amount: 95000 },
            { category: "Email Platform", amount: 15000 },
            { category: "Contingency", amount: 15000 },
        ],
        contingency_pct: 6,
        start_date: "2026-03-01",
        end_date: "2026-05-31",
        milestone_dates: [
            { label: "Creative Kickoff", date: "2026-03-01" },
            { label: "Draft Review", date: "2026-03-15" },
            { label: "Final Approval", date: "2026-03-25" },
            { label: "Campaign Launch", date: "2026-04-01" },
        ],
        kpi_definitions: [
            {
                metric: "Trial Signups",
                target: 500,
                measurement_method: "Product analytics",
                attribution_model: "last_touch",
            },
            {
                metric: "MQLs Generated",
                target: 500,
                measurement_method: "CRM pipeline",
                attribution_model: "linear",
            },
            { metric: "Brand Awareness Lift", target: 10, measurement_method: "Survey panel" },
            { metric: "Campaign ROI", target: 3, measurement_method: "Revenue / spend" },
        ],
        owner_id: null,
        approver_ids: [],
        reviewer_ids: [],
        contributor_ids: [],
        inspiration_assets: [],
        competitor_references: [],
        previous_campaign_ids: [],
        version: 2,
        amendment_of_id: null,
        retrospective_notes: null,
        created_by: null,
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cb-2",
        organization_id: "org-1",
        template_id: "bt-3",
        brand_guideline_id: "bg-3",
        brand_guideline_version_id: null,
        project_id: null,
        deal_id: null,
        company_id: null,
        title: "Coachella 2026 — Main Stage Experience",
        brief_type: "experiential",
        objective_summary:
            "Create an immersive main stage experience that drives social sharing and brand recall",
        status: "final_approved",
        business_objectives: [
            "15K daily attendee interactions",
            "10M social impressions",
            "85% positive sentiment",
        ],
        success_criteria: [
            "Foot traffic > 15K/day",
            "Social mentions > 5K during event",
            "NPS > 70",
        ],
        competitive_context:
            "Competing with Sahara tent and DoLab for attention; need visual spectacle",
        target_segments: [
            {
                name: "Festival Core",
                demographic: "18-34, music enthusiasts",
                psychographic: "Experience-seekers, social-first",
            },
        ],
        personas: [],
        deliverable_manifest: [
            { type: "Stage Design Renders", quantity: 5, specs: "4K renders, multiple angles" },
            {
                type: "Environmental Graphics",
                quantity: 12,
                specs: "Large format, weather-resistant",
            },
            { type: "Digital Interactives", quantity: 3, specs: "Touchscreen, ruggedized" },
            {
                type: "Social Content Kit",
                quantity: 1,
                specs: "Templates, hashtag guide, AR filters",
            },
        ],
        channels: ["experiential", "social_meta", "social_tiktok"],
        markets: ["US"],
        tone_direction: "Electrifying, inclusive, unforgettable",
        visual_direction: "Neon-accented, desert-inspired, large-scale geometric patterns",
        total_budget: 850000,
        budget_breakdown: [
            { category: "Stage Design & Build", amount: 450000 },
            { category: "Environmental Graphics", amount: 120000 },
            { category: "Digital Interactives", amount: 180000 },
            { category: "Social Content", amount: 50000 },
            { category: "Contingency", amount: 50000 },
        ],
        contingency_pct: 6,
        start_date: "2026-01-15",
        end_date: "2026-04-20",
        milestone_dates: [
            { label: "Design Kickoff", date: "2026-01-15" },
            { label: "Design Approval", date: "2026-02-15" },
            { label: "Fabrication Start", date: "2026-02-20" },
            { label: "Load-In", date: "2026-04-07" },
            { label: "Festival Weekend", date: "2026-04-11" },
        ],
        kpi_definitions: [
            { metric: "Daily Foot Traffic", target: 15000, measurement_method: "Sensor counting" },
            {
                metric: "Social Impressions",
                target: 10000000,
                measurement_method: "Social listening",
            },
            { metric: "Brand Recall", target: 85, measurement_method: "Post-event survey" },
        ],
        owner_id: null,
        approver_ids: [],
        reviewer_ids: [],
        contributor_ids: [],
        inspiration_assets: [],
        competitor_references: [],
        previous_campaign_ids: [],
        version: 1,
        amendment_of_id: null,
        retrospective_notes: null,
        created_by: null,
        created_at: "2025-12-10T00:00:00Z",
        updated_at: "2026-02-15T00:00:00Z",
    },
    {
        id: "cb-3",
        organization_id: "org-1",
        template_id: "bt-2",
        brand_guideline_id: "bg-1",
        brand_guideline_version_id: null,
        project_id: null,
        deal_id: null,
        company_id: null,
        title: "Rilla — Always-On Social Program Q1",
        brief_type: "social",
        objective_summary: "Maintain brand presence and thought leadership across social channels",
        status: "completed",
        business_objectives: ["Grow LinkedIn following by 20%", "Maintain 4% engagement rate"],
        success_criteria: ["15 posts/month", "Engagement rate ≥ 4%", "+2K followers/month"],
        competitive_context: null,
        target_segments: [],
        personas: [],
        deliverable_manifest: [
            { type: "Static Posts", quantity: 30, specs: "1080x1080" },
            { type: "Reels", quantity: 8, specs: "9:16, 15-30s" },
            { type: "Carousels", quantity: 6, specs: "1080x1080, 5-8 slides" },
        ],
        channels: ["social_linkedin", "social_meta", "social_x"],
        markets: ["US"],
        tone_direction: "Thought-provoking, educational, data-rich",
        visual_direction: "Clean, branded purple palette, infographic-style",
        total_budget: 35000,
        budget_breakdown: [
            { category: "Design", amount: 15000 },
            { category: "Copywriting", amount: 8000 },
            { category: "Video", amount: 10000 },
            { category: "Contingency", amount: 2000 },
        ],
        contingency_pct: 6,
        start_date: "2026-01-01",
        end_date: "2026-03-31",
        milestone_dates: [],
        kpi_definitions: [
            { metric: "Engagement Rate", target: 4, measurement_method: "Platform analytics" },
            { metric: "Follower Growth", target: 6000, measurement_method: "Platform analytics" },
        ],
        owner_id: null,
        approver_ids: [],
        reviewer_ids: [],
        contributor_ids: [],
        inspiration_assets: [],
        competitor_references: [],
        previous_campaign_ids: [],
        version: 1,
        amendment_of_id: null,
        retrospective_notes:
            "Strong performance on carousel posts. Video reels underperformed — consider shorter format next quarter.",
        created_by: null,
        created_at: "2025-12-15T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "cb-4",
        organization_id: "org-1",
        template_id: null,
        brand_guideline_id: null,
        brand_guideline_version_id: null,
        project_id: null,
        deal_id: null,
        company_id: null,
        title: "Nike — CES Innovation Showcase Brief",
        brief_type: "event",
        objective_summary:
            "Design an immersive booth experience showcasing Nike's connected fitness ecosystem",
        status: "stakeholder_review",
        business_objectives: [
            "Position Nike as tech-forward fitness brand",
            "Generate 200+ enterprise leads",
        ],
        success_criteria: ["Booth traffic > 3K/day", "Lead scan rate > 60%"],
        competitive_context:
            "Adidas and Under Armour also exhibiting; need to differentiate on tech innovation",
        target_segments: [],
        personas: [],
        deliverable_manifest: [
            {
                type: "Booth Design Package",
                quantity: 1,
                specs: "40x60 booth, 3D renders + fabrication drawings",
            },
            { type: "Interactive Demos", quantity: 4, specs: "Touch + motion sensor" },
            { type: "Printed Collateral", quantity: 3, specs: "Brochures, data sheets" },
        ],
        channels: ["experiential", "print"],
        markets: ["US"],
        tone_direction: "Bold, athletic, tech-forward",
        visual_direction: "Nike black with dynamic motion graphics, LED integration",
        total_budget: 500000,
        budget_breakdown: [
            { category: "Booth Design & Build", amount: 320000 },
            { category: "Interactive Demos", amount: 100000 },
            { category: "Collateral", amount: 30000 },
            { category: "Contingency", amount: 50000 },
        ],
        contingency_pct: 10,
        start_date: "2026-03-01",
        end_date: "2026-06-15",
        milestone_dates: [
            { label: "Brief Approval", date: "2026-03-10" },
            { label: "Design Phase", date: "2026-03-15" },
            { label: "Fabrication Start", date: "2026-04-15" },
        ],
        kpi_definitions: [
            { metric: "Booth Traffic", target: 3000, measurement_method: "Badge scans" },
            { metric: "Lead Scans", target: 200, measurement_method: "CRM import" },
        ],
        owner_id: null,
        approver_ids: [],
        reviewer_ids: [],
        contributor_ids: [],
        inspiration_assets: [],
        competitor_references: [],
        previous_campaign_ids: [],
        version: 1,
        amendment_of_id: null,
        retrospective_notes: null,
        created_by: null,
        created_at: "2026-02-18T00:00:00Z",
        updated_at: "2026-02-24T00:00:00Z",
    },
];

// ─── Campaigns ───────────────────────────────────────────────

export const MOCK_CAMPAIGNS: Campaign[] = [
    {
        id: "camp-1",
        organization_id: "org-1",
        brief_id: "cb-1",
        brand_guideline_version_id: null,
        company_id: null,
        project_id: null,
        name: "Rilla AI Coach 2.0 Launch",
        description: "Multi-channel product launch campaign for Rilla AI Coach 2.0",
        status: "in_production",
        objective: "Drive 500 trial signups and 500 MQLs through integrated campaign",
        target_audience: "VP Sales and Sales Enablement leaders at B2B SaaS companies",
        key_messages: [
            "The end of ridealongs",
            "AI-powered coaching at scale",
            "See what top reps do differently",
        ],
        total_budget: 250000,
        spent_budget: 62000,
        start_date: "2026-03-01",
        end_date: "2026-05-31",
        launch_date: "2026-04-01",
        owner_id: null,
        team_member_ids: [],
        total_reach: null,
        total_impressions: null,
        total_engagements: null,
        total_conversions: null,
        roi: null,
        post_analysis_notes: null,
        tags: ["product_launch", "B2B", "SaaS"],
        created_by: null,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "camp-2",
        organization_id: "org-1",
        brief_id: "cb-2",
        brand_guideline_version_id: null,
        company_id: null,
        project_id: null,
        name: "Coachella 2026 Main Stage",
        description: "Experiential campaign for Coachella main stage design and activation",
        status: "approved",
        objective: "Create the most Instagrammed stage at Coachella 2026",
        target_audience: "Festival attendees 18-34",
        key_messages: ["Immerse yourself", "Desert dreams", "Sound meets vision"],
        total_budget: 850000,
        spent_budget: 380000,
        start_date: "2026-01-15",
        end_date: "2026-04-20",
        launch_date: "2026-04-11",
        owner_id: null,
        team_member_ids: [],
        total_reach: null,
        total_impressions: null,
        total_engagements: null,
        total_conversions: null,
        roi: null,
        post_analysis_notes: null,
        tags: ["experiential", "festival", "large_scale"],
        created_by: null,
        created_at: "2025-12-15T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "camp-3",
        organization_id: "org-1",
        brief_id: "cb-3",
        brand_guideline_version_id: null,
        company_id: null,
        project_id: null,
        name: "Rilla — Q1 Always-On Social",
        description: "Ongoing social media presence maintaining thought leadership",
        status: "completed",
        objective: "Grow LinkedIn following and maintain engagement rate",
        target_audience: "Sales leaders and revenue operations professionals",
        key_messages: ["Sales coaching insights", "Data-driven selling", "Field intelligence"],
        total_budget: 35000,
        spent_budget: 33200,
        start_date: "2026-01-01",
        end_date: "2026-03-31",
        launch_date: "2026-01-01",
        owner_id: null,
        team_member_ids: [],
        total_reach: 2800000,
        total_impressions: 5200000,
        total_engagements: 208000,
        total_conversions: 340,
        roi: 4.2,
        post_analysis_notes:
            "Carousel posts drove 3x engagement vs static. LinkedIn outperformed Meta significantly for B2B audience.",
        tags: ["social", "always_on", "B2B"],
        created_by: null,
        created_at: "2025-12-20T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "camp-4",
        organization_id: "org-1",
        brief_id: null,
        brand_guideline_version_id: null,
        company_id: null,
        project_id: null,
        name: "Glossier Pop-Up Experience",
        description: "Retail pop-up activation for Glossier seasonal collection",
        status: "live",
        objective: "Drive foot traffic and product trials for new skincare line",
        target_audience: "Beauty-conscious consumers 18-35",
        key_messages: ["Skin first, makeup second", "Real beauty, real results"],
        total_budget: 175000,
        spent_budget: 140000,
        start_date: "2026-02-01",
        end_date: "2026-03-15",
        launch_date: "2026-02-14",
        owner_id: null,
        team_member_ids: [],
        total_reach: 450000,
        total_impressions: 1200000,
        total_engagements: 85000,
        total_conversions: 1200,
        roi: 2.8,
        post_analysis_notes: null,
        tags: ["experiential", "retail", "beauty"],
        created_by: null,
        created_at: "2026-01-05T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "camp-5",
        organization_id: "org-1",
        brief_id: null,
        brand_guideline_version_id: null,
        company_id: null,
        project_id: null,
        name: "Tesla — Autonomy Day Digital Campaign",
        description: "Digital-first campaign around Tesla Autonomy Day announcement",
        status: "planning",
        objective: "Maximize earned media and social conversation around announcement",
        target_audience: "Tech enthusiasts, EV owners, investors",
        key_messages: ["The future drives itself", "Full autonomy, delivered"],
        total_budget: 120000,
        spent_budget: 0,
        start_date: "2026-04-01",
        end_date: "2026-04-30",
        launch_date: "2026-04-15",
        owner_id: null,
        team_member_ids: [],
        total_reach: null,
        total_impressions: null,
        total_engagements: null,
        total_conversions: null,
        roi: null,
        post_analysis_notes: null,
        tags: ["digital", "tech", "automotive"],
        created_by: null,
        created_at: "2026-02-20T00:00:00Z",
        updated_at: "2026-02-24T00:00:00Z",
    },
];

// ─── Campaign Channels ───────────────────────────────────────

export const MOCK_CAMPAIGN_CHANNELS: CampaignChannel[] = [
    {
        id: "cc-1",
        campaign_id: "camp-1",
        channel_type: "social_linkedin",
        label: "LinkedIn Sponsored",
        budget_allocation: 45000,
        budget_pct: 18,
        launch_date: "2026-04-01",
        end_date: "2026-05-31",
        status: "planned",
        notes: null,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "cc-2",
        campaign_id: "camp-1",
        channel_type: "social_meta",
        label: "Meta Ads",
        budget_allocation: 30000,
        budget_pct: 12,
        launch_date: "2026-04-01",
        end_date: "2026-05-31",
        status: "planned",
        notes: null,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "cc-3",
        campaign_id: "camp-1",
        channel_type: "email",
        label: "Email Nurture",
        budget_allocation: 15000,
        budget_pct: 6,
        launch_date: "2026-04-01",
        end_date: "2026-05-15",
        status: "planned",
        notes: null,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "cc-4",
        campaign_id: "camp-1",
        channel_type: "website",
        label: "Landing Page",
        budget_allocation: 5000,
        budget_pct: 2,
        launch_date: "2026-03-28",
        end_date: "2026-05-31",
        status: "planned",
        notes: null,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "cc-5",
        campaign_id: "camp-2",
        channel_type: "experiential",
        label: "Main Stage",
        budget_allocation: 650000,
        budget_pct: 76,
        launch_date: "2026-04-11",
        end_date: "2026-04-13",
        status: "planned",
        notes: null,
        created_at: "2025-12-15T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cc-6",
        campaign_id: "camp-2",
        channel_type: "social_tiktok",
        label: "TikTok Activation",
        budget_allocation: 50000,
        budget_pct: 6,
        launch_date: "2026-04-10",
        end_date: "2026-04-20",
        status: "planned",
        notes: null,
        created_at: "2025-12-15T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cc-7",
        campaign_id: "camp-3",
        channel_type: "social_linkedin",
        label: "LinkedIn Organic",
        budget_allocation: 12000,
        budget_pct: 34,
        launch_date: "2026-01-01",
        end_date: "2026-03-31",
        status: "completed",
        notes: "Top performer",
        created_at: "2025-12-20T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "cc-8",
        campaign_id: "camp-3",
        channel_type: "social_meta",
        label: "Instagram",
        budget_allocation: 13000,
        budget_pct: 37,
        launch_date: "2026-01-01",
        end_date: "2026-03-31",
        status: "completed",
        notes: null,
        created_at: "2025-12-20T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
];

// ─── Campaign Assets ─────────────────────────────────────────

export const MOCK_CAMPAIGN_ASSETS: CampaignAsset[] = [
    {
        id: "ca-1",
        campaign_id: "camp-1",
        digital_asset_id: null,
        brief_id: "cb-1",
        name: "AI Coach 2.0 — Hero Video",
        asset_role: "hero",
        production_status: "in_production",
        target_channels: ["website", "social_linkedin"],
        brand_compliance_score: null,
        compliance_notes: null,
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: { format: "16:9", duration: "90s", resolution: "4K" },
        due_date: "2026-03-20",
        approved_at: null,
        deployed_at: null,
        assigned_to: null,
        created_by: null,
        created_at: "2026-02-10T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "ca-2",
        campaign_id: "camp-1",
        digital_asset_id: null,
        brief_id: "cb-1",
        name: "LinkedIn Carousel — Feature Breakdown",
        asset_role: "supporting",
        production_status: "in_review",
        target_channels: ["social_linkedin"],
        brand_compliance_score: 92,
        compliance_notes: "Minor font weight deviation on slide 3",
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: { format: "1080x1080", slides: 6 },
        due_date: "2026-03-10",
        approved_at: null,
        deployed_at: null,
        assigned_to: null,
        created_by: null,
        created_at: "2026-02-12T00:00:00Z",
        updated_at: "2026-02-23T00:00:00Z",
    },
    {
        id: "ca-3",
        campaign_id: "camp-1",
        digital_asset_id: null,
        brief_id: "cb-1",
        name: "Email Template — Trial Invitation",
        asset_role: "supporting",
        production_status: "approved",
        target_channels: ["email"],
        brand_compliance_score: 98,
        compliance_notes: null,
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: { format: "responsive_html", width: "600px" },
        due_date: "2026-03-15",
        approved_at: "2026-03-12T00:00:00Z",
        deployed_at: null,
        assigned_to: null,
        created_by: null,
        created_at: "2026-02-15T00:00:00Z",
        updated_at: "2026-02-23T00:00:00Z",
    },
    {
        id: "ca-4",
        campaign_id: "camp-2",
        digital_asset_id: null,
        brief_id: "cb-2",
        name: "Main Stage — Design Render Package",
        asset_role: "hero",
        production_status: "approved",
        target_channels: ["experiential"],
        brand_compliance_score: 95,
        compliance_notes: null,
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: {
            format: "4K renders",
            count: 5,
            angles: ["front", "aerial", "crowd_pov", "stage_left", "night"],
        },
        due_date: "2026-02-15",
        approved_at: "2026-02-14T00:00:00Z",
        deployed_at: null,
        assigned_to: null,
        created_by: null,
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-02-14T00:00:00Z",
    },
    {
        id: "ca-5",
        campaign_id: "camp-2",
        digital_asset_id: null,
        brief_id: "cb-2",
        name: "Environmental Graphics — Wayfinding Set",
        asset_role: "supporting",
        production_status: "in_production",
        target_channels: ["experiential"],
        brand_compliance_score: null,
        compliance_notes: null,
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: { format: "large_format", count: 12, material: "vinyl_on_substrate" },
        due_date: "2026-03-20",
        approved_at: null,
        deployed_at: null,
        assigned_to: null,
        created_by: null,
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "ca-6",
        campaign_id: "camp-3",
        digital_asset_id: null,
        brief_id: "cb-3",
        name: "Q1 Social Content Kit",
        asset_role: "template",
        production_status: "deployed",
        target_channels: ["social_linkedin", "social_meta"],
        brand_compliance_score: 96,
        compliance_notes: null,
        locale: "en-US",
        localized_from_id: null,
        localization_notes: null,
        specs: { static_posts: 30, reels: 8, carousels: 6 },
        due_date: "2025-12-28",
        approved_at: "2025-12-27T00:00:00Z",
        deployed_at: "2026-01-01T00:00:00Z",
        assigned_to: null,
        created_by: null,
        created_at: "2025-12-15T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
];

// ─── Campaign KPIs ───────────────────────────────────────────

export const MOCK_CAMPAIGN_KPIS: CampaignKpi[] = [
    {
        id: "kpi-1",
        campaign_id: "camp-1",
        metric_name: "Trial Signups",
        metric_type: "count",
        target_value: 500,
        current_value: null,
        measurement_method: "Product analytics",
        attribution: "last_touch",
        data_source: "product_db",
        reporting_frequency: "weekly",
        is_primary: true,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "kpi-2",
        campaign_id: "camp-1",
        metric_name: "MQLs Generated",
        metric_type: "count",
        target_value: 500,
        current_value: null,
        measurement_method: "CRM pipeline",
        attribution: "linear",
        data_source: "crm",
        reporting_frequency: "weekly",
        is_primary: true,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "kpi-3",
        campaign_id: "camp-1",
        metric_name: "Campaign ROI",
        metric_type: "ratio",
        target_value: 3.0,
        current_value: null,
        measurement_method: "Revenue / spend",
        attribution: "linear",
        data_source: "finance",
        reporting_frequency: "monthly",
        is_primary: false,
        created_at: "2026-02-05T00:00:00Z",
        updated_at: "2026-02-22T00:00:00Z",
    },
    {
        id: "kpi-4",
        campaign_id: "camp-3",
        metric_name: "Engagement Rate",
        metric_type: "percentage",
        target_value: 4.0,
        current_value: 4.2,
        measurement_method: "Platform analytics",
        attribution: "last_touch",
        data_source: "platform_api",
        reporting_frequency: "weekly",
        is_primary: true,
        created_at: "2025-12-20T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "kpi-5",
        campaign_id: "camp-3",
        metric_name: "Follower Growth",
        metric_type: "count",
        target_value: 6000,
        current_value: 5800,
        measurement_method: "Platform analytics",
        attribution: "last_touch",
        data_source: "platform_api",
        reporting_frequency: "monthly",
        is_primary: false,
        created_at: "2025-12-20T00:00:00Z",
        updated_at: "2026-02-25T00:00:00Z",
    },
];

// ─── Creative Reviews ────────────────────────────────────────

export const MOCK_CREATIVE_REVIEWS: CreativeReview[] = [
    {
        id: "cr-1",
        campaign_asset_id: "ca-2",
        reviewer_id: null,
        gate_type: "creative_director",
        status: "approved",
        score: 88,
        feedback: "Strong visual hierarchy. Tighten copy on slide 3.",
        annotations: [],
        requested_at: "2026-02-20T00:00:00Z",
        reviewed_at: "2026-02-21T00:00:00Z",
        organization_id: "org-1",
        created_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cr-2",
        campaign_asset_id: "ca-2",
        reviewer_id: null,
        gate_type: "brand_compliance",
        status: "approved",
        score: 92,
        feedback: "Minor font weight deviation on slide 3, acceptable.",
        annotations: [],
        requested_at: "2026-02-20T00:00:00Z",
        reviewed_at: "2026-02-21T00:00:00Z",
        organization_id: "org-1",
        created_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cr-3",
        campaign_asset_id: "ca-3",
        reviewer_id: null,
        gate_type: "creative_director",
        status: "approved",
        score: 95,
        feedback: "Clean, on-brand. Approved.",
        annotations: [],
        requested_at: "2026-03-08T00:00:00Z",
        reviewed_at: "2026-03-09T00:00:00Z",
        organization_id: "org-1",
        created_at: "2026-03-08T00:00:00Z",
    },
    {
        id: "cr-4",
        campaign_asset_id: "ca-3",
        reviewer_id: null,
        gate_type: "legal",
        status: "approved",
        score: null,
        feedback: "No legal concerns.",
        annotations: [],
        requested_at: "2026-03-09T00:00:00Z",
        reviewed_at: "2026-03-10T00:00:00Z",
        organization_id: "org-1",
        created_at: "2026-03-09T00:00:00Z",
    },
    {
        id: "cr-5",
        campaign_asset_id: "ca-4",
        reviewer_id: null,
        gate_type: "creative_director",
        status: "approved",
        score: 97,
        feedback: "Stunning renders. Approved for fabrication.",
        annotations: [],
        requested_at: "2026-02-12T00:00:00Z",
        reviewed_at: "2026-02-13T00:00:00Z",
        organization_id: "org-1",
        created_at: "2026-02-12T00:00:00Z",
    },
    {
        id: "cr-6",
        campaign_asset_id: "ca-1",
        reviewer_id: null,
        gate_type: "creative_director",
        status: "requested",
        score: null,
        feedback: null,
        annotations: [],
        requested_at: "2026-02-22T00:00:00Z",
        reviewed_at: null,
        organization_id: "org-1",
        created_at: "2026-02-22T00:00:00Z",
    },
];
