/* ═══════════════════════════════════════════════════════════════
   Mock Data — Legal, Compliance, Finance & Procurement Governance
   Migration 015 entities
   ═══════════════════════════════════════════════════════════════ */

import type {
    AssetCertification,
    BudgetApproval,
    ComplianceChecklist,
    ContractAmendment,
    ContractClause,
    ContractObligation,
    EngineeringApproval,
    EntityDependency,
    GLAccount,
    GoodsReceipt,
    GovernanceAuditLogEntry,
    InsurancePolicy,
    InsuranceRequirement,
    IPRight,
    PaymentApproval,
    Permit,
    PurchaseRequisition,
    VendorRiskScore,
} from "@/types/governance";

// ─── GL Accounts ───

export const MOCK_GL_ACCOUNTS: GLAccount[] = [
    {
        id: "gl-1",
        code: "4100",
        name: "Project Revenue — Fixed Price",
        description: "Revenue from fixed-price projects",
        account_type: "revenue",
        capex_opex: "opex",
        is_active: true,
        display_order: 1,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-2",
        code: "4200",
        name: "Project Revenue — T&M",
        description: "Revenue from time & materials projects",
        account_type: "revenue",
        capex_opex: "opex",
        is_active: true,
        display_order: 2,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-3",
        code: "5100",
        name: "Direct Labor",
        description: "Direct labor costs for projects",
        account_type: "expense",
        capex_opex: "opex",
        department: "production",
        is_active: true,
        display_order: 10,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-4",
        code: "5200",
        name: "Materials",
        description: "Raw materials and consumables",
        account_type: "expense",
        capex_opex: "opex",
        department: "production",
        is_active: true,
        display_order: 11,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-5",
        code: "5300",
        name: "Equipment Rental",
        description: "Rental equipment costs",
        account_type: "expense",
        capex_opex: "opex",
        is_active: true,
        display_order: 12,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-6",
        code: "5400",
        name: "Subcontractor Costs",
        description: "Subcontractor and vendor labor",
        account_type: "expense",
        capex_opex: "opex",
        is_active: true,
        display_order: 13,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-7",
        code: "1400",
        name: "Equipment Assets",
        description: "Purchased equipment (CapEx)",
        account_type: "asset",
        capex_opex: "capex",
        is_active: true,
        display_order: 4,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "gl-8",
        code: "5700",
        name: "Permits & Insurance",
        description: "Permit fees and insurance premiums",
        account_type: "expense",
        capex_opex: "opex",
        is_active: true,
        display_order: 14,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
];

// ─── Insurance ───

export const MOCK_INSURANCE_REQUIREMENTS: InsuranceRequirement[] = [
    {
        id: "ir-1",
        name: "Vendor General Liability",
        description: "Required GL policy for all vendors",
        entity_type: "vendor",
        coverage_type: "general_liability",
        minimum_amount: 1000000,
        currency: "USD",
        required_before: "po_issuance",
        auto_suspend_on_expiry: true,
        expiry_warning_days: 30,
        is_active: true,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "ir-2",
        name: "Vendor Workers Comp",
        description: "Required WC for construction vendors",
        entity_type: "vendor",
        contract_category: "vendor_agreement",
        coverage_type: "workers_compensation",
        minimum_amount: 500000,
        currency: "USD",
        required_before: "work_order_start",
        auto_suspend_on_expiry: true,
        expiry_warning_days: 30,
        is_active: true,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "ir-3",
        name: "Venue Event Liability",
        description: "Required event liability for venues",
        entity_type: "location",
        coverage_type: "event_liability",
        minimum_amount: 2000000,
        currency: "USD",
        required_before: "activation",
        auto_suspend_on_expiry: false,
        expiry_warning_days: 14,
        is_active: true,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
];

export const MOCK_INSURANCE_POLICIES: InsurancePolicy[] = [
    {
        id: "ip-1",
        holder_type: "vendor",
        holder_id: "v1",
        policy_type: "general_liability",
        carrier: "Hartford Insurance",
        policy_number: "GL-2026-44521",
        coverage_amount: 2000000,
        deductible: 5000,
        premium: 12000,
        currency: "USD",
        effective_date: "2026-01-01",
        expiry_date: "2027-01-01",
        additional_insured_required: true,
        status: "active",
        verified_by: "user-1",
        verified_at: "2026-01-05T10:00:00Z",
        requirement_id: "ir-1",
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-02T00:00:00Z",
        updated_at: "2026-01-05T10:00:00Z",
    },
    {
        id: "ip-2",
        holder_type: "vendor",
        holder_id: "v2",
        policy_type: "general_liability",
        carrier: "State Farm",
        policy_number: "GL-2025-78332",
        coverage_amount: 1000000,
        currency: "USD",
        effective_date: "2025-06-01",
        expiry_date: "2026-03-01",
        additional_insured_required: true,
        status: "expiring_soon",
        requirement_id: "ir-1",
        tags: [],
        organization_id: "org-1",
        created_at: "2025-06-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "ip-3",
        holder_type: "vendor",
        holder_id: "v3",
        policy_type: "workers_compensation",
        carrier: "Liberty Mutual",
        policy_number: "WC-2025-11209",
        coverage_amount: 500000,
        currency: "USD",
        effective_date: "2025-03-15",
        expiry_date: "2026-01-15",
        additional_insured_required: false,
        status: "expired",
        requirement_id: "ir-2",
        tags: [],
        organization_id: "org-1",
        created_at: "2025-03-15T00:00:00Z",
        updated_at: "2026-01-16T00:00:00Z",
    },
    {
        id: "ip-4",
        holder_type: "vendor",
        holder_id: "v1",
        policy_type: "auto_liability",
        carrier: "Hartford Insurance",
        policy_number: "AL-2026-44522",
        coverage_amount: 1000000,
        currency: "USD",
        effective_date: "2026-01-01",
        expiry_date: "2027-01-01",
        additional_insured_required: false,
        status: "active",
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-02T00:00:00Z",
        updated_at: "2026-01-02T00:00:00Z",
    },
    {
        id: "ip-5",
        holder_type: "organization",
        holder_id: "org-1",
        policy_type: "umbrella",
        carrier: "Chubb",
        policy_number: "UMB-2026-00112",
        coverage_amount: 5000000,
        premium: 45000,
        currency: "USD",
        effective_date: "2026-01-01",
        expiry_date: "2027-01-01",
        additional_insured_required: false,
        status: "active",
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
];

// ─── Contract Amendments ───

export const MOCK_CONTRACT_AMENDMENTS: ContractAmendment[] = [
    {
        id: "ca-1",
        contract_id: "contract-1",
        amendment_number: 1,
        title: "Extended Timeline — Phase 2",
        description: "Extended project delivery by 3 weeks due to venue availability",
        value_impact: 15000,
        schedule_impact_days: 21,
        scope_changes: "Added 3 additional installation days",
        effective_date: "2026-02-15",
        status: "executed",
        signed_at: "2026-02-14T16:00:00Z",
        signed_by: "Jane Smith",
        counterparty_signed_by: "Bob Client",
        counterparty_signed_at: "2026-02-14T17:30:00Z",
        organization_id: "org-1",
        created_at: "2026-02-10T00:00:00Z",
        updated_at: "2026-02-14T17:30:00Z",
    },
    {
        id: "ca-2",
        contract_id: "contract-2",
        amendment_number: 1,
        title: "Scope Reduction — AV Package",
        description: "Client elected to use in-house AV instead of contracted AV package",
        value_impact: -8500,
        schedule_impact_days: 0,
        effective_date: "2026-03-01",
        status: "pending_signature",
        organization_id: "org-1",
        created_at: "2026-02-20T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
];

// ─── Contract Clauses ───

export const MOCK_CONTRACT_CLAUSES: ContractClause[] = [
    {
        id: "cc-1",
        clause_type: "indemnification",
        title: "Mutual Indemnification",
        body: "Each party shall indemnify the other against third-party claims arising from breach of this agreement.",
        is_standard: true,
        risk_level: "medium",
        negotiable: true,
        is_template: true,
        display_order: 1,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "cc-2",
        clause_type: "limitation_of_liability",
        title: "Limitation of Liability",
        body: "Neither party's aggregate liability shall exceed the total contract value.",
        is_standard: true,
        risk_level: "high",
        negotiable: true,
        is_template: true,
        display_order: 2,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "cc-3",
        clause_type: "insurance_requirements",
        title: "Insurance Requirements",
        body: "Vendor shall maintain general liability insurance of no less than $1,000,000 per occurrence.",
        is_standard: true,
        risk_level: "high",
        negotiable: false,
        is_template: true,
        display_order: 3,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "cc-4",
        clause_type: "ip_ownership",
        title: "Work Product Ownership",
        body: "All deliverables created under this agreement shall be considered works made for hire.",
        is_standard: true,
        risk_level: "critical",
        negotiable: true,
        is_template: true,
        display_order: 4,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "cc-5",
        clause_type: "force_majeure",
        title: "Force Majeure",
        body: "Neither party shall be liable for delays due to acts of God, government actions, or other unforeseeable events.",
        is_standard: true,
        risk_level: "low",
        negotiable: false,
        is_template: true,
        display_order: 5,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
    {
        id: "cc-6",
        clause_type: "cancellation",
        title: "Event Cancellation",
        body: "In the event of cancellation within 30 days of event, 50% of contract value shall be payable as a kill fee.",
        is_standard: true,
        risk_level: "high",
        negotiable: true,
        is_template: true,
        display_order: 6,
        organization_id: "org-1",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
    },
];

// ─── Contract Obligations ───

export const MOCK_CONTRACT_OBLIGATIONS: ContractObligation[] = [
    {
        id: "co-1",
        contract_id: "contract-1",
        party: "us",
        description: "Deliver stage design renderings by March 1",
        due_date: "2026-03-01",
        is_recurring: false,
        status: "in_progress",
        is_critical: true,
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "co-2",
        contract_id: "contract-1",
        party: "counterparty",
        description: "Provide venue access for site survey",
        due_date: "2026-02-28",
        is_recurring: false,
        status: "fulfilled",
        verified_by: "user-1",
        verified_at: "2026-02-25T10:00:00Z",
        is_critical: false,
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-25T10:00:00Z",
    },
    {
        id: "co-3",
        contract_id: "contract-1",
        party: "us",
        description: "Submit monthly progress report",
        is_recurring: true,
        recurrence_pattern: "monthly",
        next_due_date: "2026-03-01",
        status: "pending",
        is_critical: false,
        organization_id: "org-1",
        created_at: "2026-01-15T00:00:00Z",
        updated_at: "2026-01-15T00:00:00Z",
    },
];

// ─── IP Rights ───

export const MOCK_IP_RIGHTS: IPRight[] = [
    {
        id: "ipr-1",
        contract_id: "contract-1",
        asset_type: "design",
        asset_description: "Stage design and fabrication drawings",
        owner: "us",
        license_type: "work_for_hire",
        territory: "worldwide",
        exclusivity: false,
        sublicensable: false,
        permitted_uses: "Client may use designs for internal marketing",
        prohibited_uses: "Cannot license to third parties",
        organization_id: "org-1",
        created_at: "2026-01-15T00:00:00Z",
        updated_at: "2026-01-15T00:00:00Z",
    },
    {
        id: "ipr-2",
        contract_id: "contract-2",
        asset_type: "photograph",
        asset_description: "Event photography — all images captured during activation",
        owner: "us",
        license_type: "non_exclusive",
        territory: "worldwide",
        duration: "2 years",
        exclusivity: false,
        sublicensable: true,
        permitted_uses: "Portfolio, social media, website",
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
];

// ─── Permits ───

export const MOCK_PERMITS: Permit[] = [
    {
        id: "pmt-1",
        permit_type: "fire",
        jurisdiction: "City of Austin",
        jurisdiction_level: "local",
        issuing_authority: "Austin Fire Department",
        entity_type: "location",
        entity_id: "loc-1",
        permit_number: "FP-2026-0445",
        title: "Fire Permit — Austin Convention Center",
        applied_date: "2026-01-15",
        submitted_date: "2026-01-16",
        approved_date: "2026-02-01",
        effective_date: "2026-03-01",
        expiry_date: "2026-03-15",
        permit_fee: 750,
        total_cost: 750,
        status: "approved",
        conditions: "Fire watch required during load-in/load-out",
        conditions_met: true,
        requires_inspection: true,
        blocks_entity: true,
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-15T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "pmt-2",
        permit_type: "noise",
        jurisdiction: "City of Austin",
        jurisdiction_level: "local",
        issuing_authority: "Austin Code Department",
        entity_type: "event",
        entity_id: "evt-1",
        title: "Amplified Sound Permit — SXSW Activation",
        applied_date: "2026-01-20",
        submitted_date: "2026-01-21",
        status: "under_review",
        conditions: "Sound levels must not exceed 85dB at property line",
        conditions_met: false,
        requires_inspection: false,
        blocks_entity: true,
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-01-21T00:00:00Z",
    },
    {
        id: "pmt-3",
        permit_type: "street_closure",
        jurisdiction: "City of Miami Beach",
        jurisdiction_level: "local",
        issuing_authority: "Miami Beach Public Works",
        entity_type: "event",
        entity_id: "evt-2",
        title: "Street Closure — Ocean Drive Block Party",
        status: "required",
        conditions_met: false,
        requires_inspection: false,
        blocks_entity: true,
        tags: [],
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "pmt-4",
        permit_type: "building",
        jurisdiction: "City of Austin",
        jurisdiction_level: "local",
        issuing_authority: "Austin Building Department",
        entity_type: "activation",
        entity_id: "act-1",
        permit_number: "BP-2026-1122",
        title: "Temporary Structure Permit — 30ft Stage",
        applied_date: "2026-01-10",
        approved_date: "2026-02-05",
        effective_date: "2026-02-20",
        expiry_date: "2026-03-20",
        permit_fee: 1200,
        total_cost: 1200,
        status: "active",
        conditions_met: true,
        requires_inspection: true,
        inspection_date: "2026-02-20",
        inspection_passed: true,
        blocks_entity: true,
        tags: [],
        organization_id: "org-1",
        created_at: "2026-01-10T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "pmt-5",
        permit_type: "liquor",
        jurisdiction: "State of Texas",
        jurisdiction_level: "state",
        issuing_authority: "TABC",
        entity_type: "event",
        entity_id: "evt-1",
        title: "Temporary Alcohol Permit — SXSW Event",
        applied_date: "2026-02-01",
        status: "submitted",
        application_fee: 250,
        conditions_met: false,
        requires_inspection: false,
        blocks_entity: true,
        tags: [],
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
];

// ─── Engineering Approvals ───

export const MOCK_ENGINEERING_APPROVALS: EngineeringApproval[] = [
    {
        id: "ea-1",
        approval_type: "structural",
        entity_type: "activation",
        entity_id: "act-1",
        engineer_name: "Dr. Robert Chen, PE",
        engineer_license_number: "TX-PE-84521",
        engineering_firm: "Structural Dynamics LLC",
        status: "approved",
        submitted_at: "2026-01-20T00:00:00Z",
        approved_at: "2026-02-05T00:00:00Z",
        valid_until: "2026-04-01",
        conditions: "Maximum wind load 45mph. Temporary bracing required during assembly.",
        conditions_met: true,
        inspection_schedule: [
            { date: "2026-03-01", type: "pre-load-in" },
            { date: "2026-03-10", type: "in-use" },
        ],
        organization_id: "org-1",
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-02-05T00:00:00Z",
    },
    {
        id: "ea-2",
        approval_type: "electrical",
        entity_type: "activation",
        entity_id: "act-1",
        engineer_name: "Sarah Martinez, PE",
        engineer_license_number: "TX-PE-67890",
        engineering_firm: "PowerTech Engineering",
        status: "under_review",
        submitted_at: "2026-02-10T00:00:00Z",
        conditions_met: false,
        inspection_schedule: [],
        organization_id: "org-1",
        created_at: "2026-02-10T00:00:00Z",
        updated_at: "2026-02-10T00:00:00Z",
    },
    {
        id: "ea-3",
        approval_type: "rigging",
        entity_type: "event",
        entity_id: "evt-1",
        engineer_name: "Michael Torres, PE",
        engineer_license_number: "TX-PE-55432",
        status: "pending",
        conditions_met: false,
        inspection_schedule: [],
        organization_id: "org-1",
        created_at: "2026-02-15T00:00:00Z",
        updated_at: "2026-02-15T00:00:00Z",
    },
];

// ─── Compliance Checklists ───

export const MOCK_COMPLIANCE_CHECKLISTS: ComplianceChecklist[] = [
    {
        id: "cl-1",
        checklist_type: "fire_safety",
        entity_type: "location",
        entity_id: "loc-1",
        title: "Fire Safety Inspection — Austin Convention Center",
        items: [
            { id: "i1", title: "Emergency exits clear", completed: true },
            { id: "i2", title: "Fire extinguishers accessible", completed: true },
            { id: "i3", title: "Sprinkler system functional", completed: true },
            { id: "i4", title: "Evacuation plan posted", completed: false },
        ],
        total_items: 4,
        completed_items: 3,
        completion_percent: 75,
        status: "in_progress",
        organization_id: "org-1",
        created_at: "2026-02-15T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
    {
        id: "cl-2",
        checklist_type: "ada",
        entity_type: "location",
        entity_id: "loc-1",
        title: "ADA Compliance Check — Austin Convention Center",
        items: [
            { id: "i1", title: "Wheelchair accessible entrances", completed: true },
            { id: "i2", title: "ADA-compliant restrooms", completed: true },
            { id: "i3", title: "Assistive listening available", completed: true },
        ],
        total_items: 3,
        completed_items: 3,
        completion_percent: 100,
        status: "completed",
        inspected_at: "2026-02-18T14:00:00Z",
        organization_id: "org-1",
        created_at: "2026-02-15T00:00:00Z",
        updated_at: "2026-02-18T14:00:00Z",
    },
    {
        id: "cl-3",
        checklist_type: "osha",
        entity_type: "activation",
        entity_id: "act-1",
        title: "OSHA Safety Check — Stage Build",
        items: [
            { id: "i1", title: "PPE available for all crew", completed: false },
            { id: "i2", title: "Fall protection for heights >6ft", completed: false },
        ],
        total_items: 2,
        completed_items: 0,
        completion_percent: 0,
        status: "not_started",
        organization_id: "org-1",
        created_at: "2026-02-20T00:00:00Z",
        updated_at: "2026-02-20T00:00:00Z",
    },
];

// ─── Asset Certifications ───

export const MOCK_ASSET_CERTIFICATIONS: AssetCertification[] = [
    {
        id: "ac-1",
        asset_id: "asset-1",
        cert_type: "rigging_inspection",
        title: "Annual Rigging Inspection — Chain Motors",
        cert_number: "RI-2026-001",
        issued_by: "Certified Rigging Inspectors Inc",
        issued_date: "2026-01-15",
        expiry_date: "2027-01-15",
        status: "current",
        blocks_usage: true,
        organization_id: "org-1",
        created_at: "2026-01-15T00:00:00Z",
        updated_at: "2026-01-15T00:00:00Z",
    },
    {
        id: "ac-2",
        asset_id: "asset-2",
        cert_type: "electrical_safety",
        title: "Electrical Safety Test — LED Wall Panels",
        issued_by: "UL Testing Lab",
        issued_date: "2025-06-01",
        expiry_date: "2026-06-01",
        status: "current",
        blocks_usage: true,
        organization_id: "org-1",
        created_at: "2025-06-01T00:00:00Z",
        updated_at: "2025-06-01T00:00:00Z",
    },
    {
        id: "ac-3",
        asset_id: "asset-3",
        cert_type: "structural_integrity",
        title: "Structural Load Test — Portable Stage",
        issued_by: "Structural Dynamics LLC",
        issued_date: "2025-01-01",
        expiry_date: "2026-01-01",
        status: "expired",
        blocks_usage: true,
        organization_id: "org-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2026-01-02T00:00:00Z",
    },
];

// ─── Budget Approvals ───

export const MOCK_BUDGET_APPROVALS: BudgetApproval[] = [
    {
        id: "ba-1",
        entity_type: "budget",
        entity_id: "budget-1",
        amount: 125000,
        currency: "USD",
        threshold_rule: "$100K+ requires VP",
        requested_by: "user-pm-1",
        requested_at: "2026-02-10T09:00:00Z",
        approver_id: "user-vp-1",
        approved_at: "2026-02-11T14:00:00Z",
        status: "approved",
        approval_level: 3,
        organization_id: "org-1",
        created_at: "2026-02-10T09:00:00Z",
        updated_at: "2026-02-11T14:00:00Z",
    },
    {
        id: "ba-2",
        entity_type: "change_order",
        entity_id: "co-1",
        amount: 15000,
        currency: "USD",
        threshold_rule: "$5K-$25K requires Director",
        requested_by: "user-pm-1",
        requested_at: "2026-02-20T11:00:00Z",
        status: "pending",
        approval_level: 2,
        justification: "Extended timeline requires additional crew days",
        organization_id: "org-1",
        created_at: "2026-02-20T11:00:00Z",
        updated_at: "2026-02-20T11:00:00Z",
    },
    {
        id: "ba-3",
        entity_type: "purchase_order",
        entity_id: "po-3",
        amount: 3200,
        currency: "USD",
        threshold_rule: "$0-$5K PM only",
        requested_by: "user-pm-2",
        requested_at: "2026-02-22T10:00:00Z",
        approver_id: "user-pm-2",
        approved_at: "2026-02-22T10:05:00Z",
        status: "approved",
        approval_level: 1,
        organization_id: "org-1",
        created_at: "2026-02-22T10:00:00Z",
        updated_at: "2026-02-22T10:05:00Z",
    },
];

// ─── Payment Approvals ───

export const MOCK_PAYMENT_APPROVALS: PaymentApproval[] = [
    {
        id: "pa-1",
        payment_type: "vendor_invoice",
        entity_id: "inv-1",
        amount: 45000,
        currency: "USD",
        vendor_id: "v1",
        payee_name: "SteelCraft Fabrication",
        threshold_rule: "$10K-$50K Finance Director",
        requested_by: "user-ap-1",
        requested_at: "2026-02-18T09:00:00Z",
        status: "pending",
        three_way_match_verified: true,
        vendor_compliance_verified: true,
        budget_within_limit: true,
        organization_id: "org-1",
        created_at: "2026-02-18T09:00:00Z",
        updated_at: "2026-02-18T09:00:00Z",
    },
    {
        id: "pa-2",
        payment_type: "vendor_invoice",
        entity_id: "inv-2",
        amount: 8200,
        currency: "USD",
        vendor_id: "v2",
        payee_name: "EventTech Rentals",
        threshold_rule: "$2.5K-$10K AP Manager",
        requested_by: "user-ap-1",
        requested_at: "2026-02-19T14:00:00Z",
        approver_id: "user-apmgr-1",
        approved_at: "2026-02-20T09:00:00Z",
        status: "approved",
        three_way_match_verified: true,
        vendor_compliance_verified: true,
        budget_within_limit: true,
        organization_id: "org-1",
        created_at: "2026-02-19T14:00:00Z",
        updated_at: "2026-02-20T09:00:00Z",
    },
    {
        id: "pa-3",
        payment_type: "expense_reimbursement",
        entity_id: "exp-5",
        amount: 1250,
        currency: "USD",
        payee_name: "John Miller",
        threshold_rule: "$0-$2.5K auto",
        requested_by: "user-ap-1",
        requested_at: "2026-02-21T11:00:00Z",
        approver_id: "user-ap-1",
        approved_at: "2026-02-21T11:01:00Z",
        status: "approved",
        three_way_match_verified: false,
        vendor_compliance_verified: false,
        budget_within_limit: true,
        organization_id: "org-1",
        created_at: "2026-02-21T11:00:00Z",
        updated_at: "2026-02-21T11:01:00Z",
    },
];

// ─── Purchase Requisitions ───

export const MOCK_PURCHASE_REQUISITIONS: PurchaseRequisition[] = [
    {
        id: "pr-1",
        project_id: "proj-1",
        number: "REQ-2026-001",
        title: "LED Wall Panels for SXSW Stage",
        requester_id: "user-pm-1",
        line_items: [
            { name: "LED Panel 500x500", qty: 48, unit_price: 350 },
            { name: "Mounting Hardware Kit", qty: 12, unit_price: 125 },
        ],
        estimated_cost: 18300,
        budget_code: "5300",
        gl_account_id: "gl-5",
        department: "production",
        urgency: "high",
        needed_by: "2026-02-28",
        justification: "Required for main stage at SXSW activation",
        status: "approved",
        approved_by: "user-dir-1",
        approved_at: "2026-02-12T15:00:00Z",
        converted_po_id: "po-5",
        organization_id: "org-1",
        created_at: "2026-02-10T00:00:00Z",
        updated_at: "2026-02-12T15:00:00Z",
    },
    {
        id: "pr-2",
        project_id: "proj-1",
        number: "REQ-2026-002",
        title: "Catering Services — VIP Lounge",
        requester_id: "user-pm-2",
        line_items: [{ name: "VIP Catering Package (100 pax)", qty: 3, unit_price: 4500 }],
        estimated_cost: 13500,
        department: "operations",
        urgency: "normal",
        needed_by: "2026-03-05",
        justification: "Three-day event catering for VIP lounge",
        status: "pending_approval",
        organization_id: "org-1",
        created_at: "2026-02-18T00:00:00Z",
        updated_at: "2026-02-18T00:00:00Z",
    },
    {
        id: "pr-3",
        project_id: "proj-2",
        number: "REQ-2026-003",
        title: "Safety Equipment — Crew PPE",
        requester_id: "user-pm-1",
        line_items: [
            { name: "Hard Hats", qty: 25, unit_price: 35 },
            { name: "Safety Vests", qty: 25, unit_price: 18 },
            { name: "Safety Glasses", qty: 50, unit_price: 8 },
        ],
        estimated_cost: 1725,
        urgency: "critical",
        needed_by: "2026-02-26",
        justification: "Mandatory PPE for construction crew",
        status: "converted_to_po",
        converted_po_id: "po-6",
        organization_id: "org-1",
        created_at: "2026-02-20T00:00:00Z",
        updated_at: "2026-02-21T00:00:00Z",
    },
];

// ─── Goods Receipts ───

export const MOCK_GOODS_RECEIPTS: GoodsReceipt[] = [
    {
        id: "gr-1",
        purchase_order_id: "po-5",
        receipt_number: "GR-2026-001",
        received_by: "user-wh-1",
        received_at: "2026-02-25T10:30:00Z",
        line_items: [
            { name: "LED Panel 500x500", qty_ordered: 48, qty_received: 48, condition: "good" },
            { name: "Mounting Hardware Kit", qty_ordered: 12, qty_received: 12, condition: "good" },
        ],
        status: "complete",
        delivery_location: "Main Warehouse",
        photos: [],
        organization_id: "org-1",
        created_at: "2026-02-25T10:30:00Z",
        updated_at: "2026-02-25T10:30:00Z",
    },
    {
        id: "gr-2",
        purchase_order_id: "po-4",
        receipt_number: "GR-2026-002",
        received_by: "user-wh-1",
        received_at: "2026-02-24T14:00:00Z",
        line_items: [
            { name: "Truss Sections (10ft)", qty_ordered: 20, qty_received: 18, condition: "good" },
        ],
        status: "discrepancy",
        discrepancies: "2 truss sections missing from shipment. Vendor notified.",
        photos: [],
        organization_id: "org-1",
        created_at: "2026-02-24T14:00:00Z",
        updated_at: "2026-02-24T14:00:00Z",
    },
];

// ─── Vendor Risk Scores ───

export const MOCK_VENDOR_RISK_SCORES: VendorRiskScore[] = [
    {
        id: "vrs-1",
        vendor_id: "v1",
        score_date: "2026-02-25",
        overall_score: 92,
        financial_score: 95,
        compliance_score: 90,
        performance_score: 94,
        operational_score: 88,
        risk_level: "low",
        risk_factors: [],
        recommendations: [],
        total_spend: 245000,
        active_po_count: 3,
        overdue_invoice_count: 0,
        incident_count: 0,
        organization_id: "org-1",
        created_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "vrs-2",
        vendor_id: "v2",
        score_date: "2026-02-25",
        overall_score: 74,
        financial_score: 80,
        compliance_score: 60,
        performance_score: 82,
        operational_score: 75,
        risk_level: "medium",
        risk_factors: [{ factor: "Insurance expiring in 4 days", severity: "high" }],
        recommendations: [{ action: "Request insurance renewal proof" }],
        total_spend: 89000,
        active_po_count: 1,
        overdue_invoice_count: 1,
        incident_count: 0,
        organization_id: "org-1",
        created_at: "2026-02-25T00:00:00Z",
    },
    {
        id: "vrs-3",
        vendor_id: "v3",
        score_date: "2026-02-25",
        overall_score: 45,
        financial_score: 50,
        compliance_score: 25,
        performance_score: 60,
        operational_score: 45,
        risk_level: "critical",
        risk_factors: [
            { factor: "Workers comp insurance expired", severity: "critical" },
            { factor: "2 overdue invoices", severity: "medium" },
        ],
        recommendations: [
            { action: "Suspend vendor until compliance resolved" },
            { action: "Identify backup vendor" },
        ],
        total_spend: 32000,
        active_po_count: 0,
        overdue_invoice_count: 2,
        incident_count: 1,
        organization_id: "org-1",
        created_at: "2026-02-25T00:00:00Z",
    },
];

// ─── Entity Dependencies ───

export const MOCK_ENTITY_DEPENDENCIES: EntityDependency[] = [
    {
        id: "dep-1",
        dependent_entity_type: "event",
        dependent_entity_id: "evt-1",
        required_entity_type: "permit",
        required_entity_id: "pmt-1",
        dependency_type: "hard_block",
        description: "Fire permit required before event can proceed",
        status: "satisfied",
        satisfied_at: "2026-02-01T00:00:00Z",
        auto_check: true,
        organization_id: "org-1",
        created_at: "2026-01-15T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "dep-2",
        dependent_entity_type: "event",
        dependent_entity_id: "evt-1",
        required_entity_type: "permit",
        required_entity_id: "pmt-2",
        dependency_type: "hard_block",
        description: "Noise permit required for amplified sound",
        status: "pending",
        auto_check: true,
        organization_id: "org-1",
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-01-20T00:00:00Z",
    },
    {
        id: "dep-3",
        dependent_entity_type: "activation",
        dependent_entity_id: "act-1",
        required_entity_type: "engineering_approval",
        required_entity_id: "ea-1",
        dependency_type: "hard_block",
        description: "Structural engineering approval required before build",
        status: "satisfied",
        satisfied_at: "2026-02-05T00:00:00Z",
        auto_check: true,
        organization_id: "org-1",
        created_at: "2026-01-20T00:00:00Z",
        updated_at: "2026-02-05T00:00:00Z",
    },
    {
        id: "dep-4",
        dependent_entity_type: "purchase_order",
        dependent_entity_id: "po-7",
        required_entity_type: "insurance_policy",
        dependency_type: "hard_block",
        description: "Vendor insurance must be active before PO issuance",
        status: "expired",
        auto_check: true,
        organization_id: "org-1",
        created_at: "2026-02-15T00:00:00Z",
        updated_at: "2026-02-15T00:00:00Z",
    },
    {
        id: "dep-5",
        dependent_entity_type: "event",
        dependent_entity_id: "evt-1",
        required_entity_type: "permit",
        required_entity_id: "pmt-5",
        dependency_type: "hard_block",
        description: "Liquor license required for alcohol service",
        status: "pending",
        auto_check: true,
        organization_id: "org-1",
        created_at: "2026-02-01T00:00:00Z",
        updated_at: "2026-02-01T00:00:00Z",
    },
];

// ─── Governance Audit Log ───

export const MOCK_GOVERNANCE_AUDIT_LOG: GovernanceAuditLogEntry[] = [
    {
        id: "gal-1",
        domain: "compliance",
        entity_type: "permit",
        entity_id: "pmt-1",
        action: "approved",
        actor_id: "user-1",
        change_summary: "Fire permit approved by Austin Fire Department",
        metadata: {},
        logged_at: "2026-02-01T10:00:00Z",
        organization_id: "org-1",
    },
    {
        id: "gal-2",
        domain: "legal",
        entity_type: "insurance_policy",
        entity_id: "ip-1",
        action: "verified",
        actor_id: "user-1",
        change_summary: "GL policy verified — Hartford $2M coverage",
        metadata: {},
        logged_at: "2026-01-05T10:00:00Z",
        organization_id: "org-1",
    },
    {
        id: "gal-3",
        domain: "finance",
        entity_type: "budget_approval",
        entity_id: "ba-1",
        action: "approved",
        actor_id: "user-vp-1",
        change_summary: "Budget $125K approved by VP Operations",
        metadata: {},
        logged_at: "2026-02-11T14:00:00Z",
        organization_id: "org-1",
    },
    {
        id: "gal-4",
        domain: "legal",
        entity_type: "insurance_policy",
        entity_id: "ip-3",
        action: "expired",
        change_summary: "Workers comp policy expired — vendor v3 suspended",
        metadata: {},
        logged_at: "2026-01-16T00:00:00Z",
        organization_id: "org-1",
    },
    {
        id: "gal-5",
        domain: "finance",
        entity_type: "payment_approval",
        entity_id: "pa-2",
        action: "approved",
        actor_id: "user-apmgr-1",
        change_summary: "Payment $8,200 to EventTech Rentals approved",
        metadata: {},
        logged_at: "2026-02-20T09:00:00Z",
        organization_id: "org-1",
    },
];
