import type {
    ClassificationAssessment,
    WorkerOffboardingRun,
    WorkerOnboardingRun,
    WorkerProfile,
    WorkerReview,
} from "@/types/workforce";

// ─── Worker Profiles ───
export const MOCK_WORKER_PROFILES: WorkerProfile[] = [
    {
        id: "wp1",
        firstName: "Alex",
        lastName: "Rivera",
        email: "alex.r@org.com",
        phone: "+1-555-0101",
        primaryClassification: "full_time_employee",
        taxClassification: "w2",
        lifecycleStatus: "active",
        initialEngagementDate: "2023-06-15",
        primaryRole: "Production Manager",
        skills: ["project_management", "budgeting", "vendor_relations"],
        department: "production",
        homeBase: "Los Angeles",
        willingToTravel: true,
        travelRadius: 500,
        tags: ["senior", "lead"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: ["Site Supervisor"],
        createdAt: "2023-06-15T00:00:00Z",
        activeEngagements: 3,
        complianceScore: 100,
        averageRating: 4.8,
    },
    {
        id: "wp2",
        firstName: "Jordan",
        lastName: "Park",
        email: "jordan.p@org.com",
        phone: "+1-555-0102",
        primaryClassification: "full_time_employee",
        taxClassification: "w2",
        lifecycleStatus: "active",
        initialEngagementDate: "2024-01-10",
        primaryRole: "Technical Director",
        skills: ["audio", "lighting", "rigging", "cad"],
        department: "technical",
        homeBase: "New York",
        willingToTravel: true,
        tags: ["senior"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: ["AV Lead"],
        createdAt: "2024-01-10T00:00:00Z",
        activeEngagements: 2,
        complianceScore: 95,
        averageRating: 4.6,
    },
    {
        id: "wp3",
        firstName: "Maya",
        lastName: "Chen",
        email: "maya.c@org.com",
        phone: "+1-555-0103",
        primaryClassification: "part_time_employee",
        taxClassification: "w2",
        lifecycleStatus: "active",
        initialEngagementDate: "2024-08-01",
        primaryRole: "Scenic Artist",
        skills: ["painting", "scenic_design", "fabrication"],
        department: "scenic",
        homeBase: "Los Angeles",
        willingToTravel: false,
        tags: [],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2024-08-01T00:00:00Z",
        activeEngagements: 1,
        complianceScore: 100,
        averageRating: 4.2,
    },
    {
        id: "wp4",
        firstName: "Carlos",
        lastName: "Mendez",
        email: "carlos.m@org.com",
        phone: "+1-555-0104",
        primaryClassification: "seasonal_employee",
        taxClassification: "w2_seasonal",
        lifecycleStatus: "active",
        initialEngagementDate: "2024-03-01",
        mostRecentEngagementDate: "2026-02-01",
        primaryRole: "Stage Hand",
        skills: ["rigging", "carpentry", "load_in"],
        department: "construction",
        homeBase: "Miami",
        willingToTravel: true,
        travelRadius: 200,
        tags: ["festival_season", "returning"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: false,
        secondaryRoles: ["Rigger"],
        createdAt: "2024-03-01T00:00:00Z",
        activeEngagements: 1,
        complianceScore: 85,
        averageRating: 4.5,
    },
    {
        id: "wp5",
        firstName: "Sam",
        lastName: "Okafor",
        email: "sam.o@freelance.com",
        phone: "+1-555-0105",
        primaryClassification: "freelancer",
        taxClassification: "1099",
        lifecycleStatus: "active",
        initialEngagementDate: "2025-04-15",
        primaryRole: "Lighting Designer",
        skills: ["lighting_design", "programming", "grandma3", "vectorworks"],
        department: "lighting",
        homeBase: "Chicago",
        willingToTravel: true,
        travelRadius: 1000,
        tags: ["specialist", "premium"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2025-04-15T00:00:00Z",
        activeEngagements: 2,
        complianceScore: 90,
        averageRating: 4.9,
    },
    {
        id: "wp6",
        firstName: "Priya",
        lastName: "Sharma",
        email: "priya@steelcraft.com",
        phone: "+1-555-0106",
        primaryClassification: "subcontractor",
        taxClassification: "corp_to_corp",
        lifecycleStatus: "active",
        initialEngagementDate: "2025-01-01",
        primaryRole: "Fabrication Lead",
        skills: ["steel_fabrication", "welding", "structural"],
        department: "fabrication",
        homeBase: "Detroit",
        willingToTravel: true,
        tags: ["preferred_vendor"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2025-01-01T00:00:00Z",
        activeEngagements: 1,
        complianceScore: 100,
        averageRating: 4.7,
    },
    {
        id: "wp7",
        firstName: "Derek",
        lastName: "Williams",
        email: "derek.w@org.com",
        phone: "+1-555-0107",
        primaryClassification: "contract_employee",
        taxClassification: "w2",
        lifecycleStatus: "active",
        initialEngagementDate: "2025-09-01",
        primaryRole: "Project Coordinator",
        skills: ["coordination", "scheduling", "logistics"],
        department: "production",
        homeBase: "Austin",
        willingToTravel: false,
        tags: ["temp_to_perm"],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2025-09-01T00:00:00Z",
        activeEngagements: 1,
        complianceScore: 100,
        averageRating: 3.8,
    },
    {
        id: "wp8",
        firstName: "Kenji",
        lastName: "Tanaka",
        email: "kenji@avpros.com",
        phone: "+1-555-0108",
        primaryClassification: "independent_contractor",
        taxClassification: "1099",
        lifecycleStatus: "active",
        initialEngagementDate: "2025-06-01",
        primaryRole: "AV Technician",
        skills: ["audio", "video", "networking", "dante"],
        department: "av",
        homeBase: "San Francisco",
        willingToTravel: true,
        travelRadius: 300,
        tags: ["specialist"],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: ["Broadcast Engineer"],
        createdAt: "2025-06-01T00:00:00Z",
        activeEngagements: 1,
        complianceScore: 75,
        averageRating: 4.3,
    },
    {
        id: "wp9",
        firstName: "Lena",
        lastName: "Kowalski",
        email: "lena.k@org.com",
        phone: "+1-555-0109",
        primaryClassification: "intern",
        taxClassification: "exempt",
        lifecycleStatus: "onboarding",
        initialEngagementDate: "2026-02-20",
        primaryRole: "Production Intern",
        skills: ["organization", "cad_basic"],
        department: "production",
        homeBase: "Los Angeles",
        willingToTravel: false,
        tags: ["spring_2026"],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: false,
        secondaryRoles: [],
        createdAt: "2026-02-20T00:00:00Z",
        activeEngagements: 0,
        complianceScore: 40,
        averageRating: 0,
    },
    {
        id: "wp10",
        firstName: "Travis",
        lastName: "Moore",
        email: "travis.m@org.com",
        phone: "+1-555-0110",
        primaryClassification: "full_time_employee",
        taxClassification: "w2",
        lifecycleStatus: "offboarding",
        initialEngagementDate: "2022-01-15",
        offboardingDate: "2026-03-01",
        primaryRole: "Warehouse Manager",
        skills: ["logistics", "inventory", "forklift"],
        department: "logistics",
        homeBase: "Los Angeles",
        willingToTravel: false,
        tags: [],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2022-01-15T00:00:00Z",
        activeEngagements: 0,
        complianceScore: 100,
        averageRating: 3.5,
    },
    {
        id: "wp11",
        firstName: "Nina",
        lastName: "Alvarez",
        email: "nina.a@org.com",
        primaryClassification: "seasonal_employee",
        taxClassification: "w2_seasonal",
        lifecycleStatus: "alumni",
        initialEngagementDate: "2024-05-01",
        offboardingDate: "2025-10-31",
        primaryRole: "Brand Ambassador",
        skills: ["events", "hospitality", "sales"],
        department: "staffing",
        homeBase: "Miami",
        willingToTravel: true,
        tags: ["festival_season", "returning"],
        preferred: true,
        doNotEngage: false,
        portalAccessEnabled: false,
        secondaryRoles: [],
        createdAt: "2024-05-01T00:00:00Z",
        activeEngagements: 0,
        complianceScore: 80,
        averageRating: 4.4,
    },
    {
        id: "wp12",
        firstName: "Greg",
        lastName: "Foster",
        email: "greg.f@sparkelectric.com",
        primaryClassification: "subcontractor",
        taxClassification: "corp_to_corp",
        lifecycleStatus: "suspended",
        initialEngagementDate: "2025-03-01",
        primaryRole: "Electrical Contractor",
        skills: ["electrical", "power_distribution"],
        department: "technical",
        homeBase: "Dallas",
        willingToTravel: true,
        tags: [],
        preferred: false,
        doNotEngage: false,
        portalAccessEnabled: true,
        secondaryRoles: [],
        createdAt: "2025-03-01T00:00:00Z",
        activeEngagements: 0,
        complianceScore: 30,
        averageRating: 3.2,
    },
];

// ─── Onboarding Runs ───
export const MOCK_ONBOARDING_RUNS: WorkerOnboardingRun[] = [
    {
        id: "obr1",
        workerProfileId: "wp9",
        workerName: "Lena Kowalski",
        classification: "intern",
        startedAt: "2026-02-20T09:00:00Z",
        targetCompletionDate: "2026-03-01",
        status: "in_progress",
        totalSteps: 8,
        completedSteps: 3,
        steps: [
            {
                id: "s1",
                runId: "obr1",
                templateStepId: "t1",
                stepName: "Offer Letter Signed",
                status: "completed",
                completedAt: "2026-02-20T10:00:00Z",
                completedByName: "Lena Kowalski",
                dueDate: "2026-02-21",
            },
            {
                id: "s2",
                runId: "obr1",
                templateStepId: "t2",
                stepName: "I-9 Verification",
                status: "completed",
                completedAt: "2026-02-21T14:00:00Z",
                completedByName: "HR Team",
                dueDate: "2026-02-23",
            },
            {
                id: "s3",
                runId: "obr1",
                templateStepId: "t3",
                stepName: "Background Check",
                status: "completed",
                completedAt: "2026-02-24T09:00:00Z",
                completedByName: "System",
                dueDate: "2026-02-27",
            },
            {
                id: "s4",
                runId: "obr1",
                templateStepId: "t4",
                stepName: "Safety Training",
                status: "in_progress",
                assignedToName: "Alex Rivera",
                dueDate: "2026-02-28",
            },
            {
                id: "s5",
                runId: "obr1",
                templateStepId: "t5",
                stepName: "Equipment Assignment",
                status: "not_started",
                assignedToName: "IT Team",
                dueDate: "2026-02-28",
            },
            {
                id: "s6",
                runId: "obr1",
                templateStepId: "t6",
                stepName: "IT Setup (Email, Accounts)",
                status: "not_started",
                assignedToName: "IT Team",
                dueDate: "2026-02-28",
            },
            {
                id: "s7",
                runId: "obr1",
                templateStepId: "t7",
                stepName: "Department Orientation",
                status: "not_started",
                assignedToName: "Alex Rivera",
                dueDate: "2026-03-01",
            },
            {
                id: "s8",
                runId: "obr1",
                templateStepId: "t8",
                stepName: "Mentor Assignment",
                status: "not_started",
                assignedToName: "Alex Rivera",
                dueDate: "2026-03-01",
            },
        ],
    },
    {
        id: "obr2",
        workerProfileId: "wp8",
        workerName: "Kenji Tanaka",
        classification: "independent_contractor",
        startedAt: "2025-06-01T09:00:00Z",
        completedAt: "2025-06-08T16:00:00Z",
        status: "completed",
        totalSteps: 6,
        completedSteps: 6,
    },
    {
        id: "obr3",
        workerProfileId: "wp4",
        workerName: "Carlos Mendez",
        classification: "seasonal_employee",
        startedAt: "2026-02-01T09:00:00Z",
        targetCompletionDate: "2026-02-07",
        status: "in_progress",
        totalSteps: 5,
        completedSteps: 4,
        notes: "Returning seasonal — skipped I-9 and background check (on file)",
    },
];

// ─── Offboarding Runs ───
export const MOCK_OFFBOARDING_RUNS: WorkerOffboardingRun[] = [
    {
        id: "ofr1",
        workerProfileId: "wp10",
        workerName: "Travis Moore",
        reason: "Voluntary resignation — relocating",
        isVoluntary: true,
        eligibleForRehire: true,
        startedAt: "2026-02-15T09:00:00Z",
        status: "in_progress",
        totalSteps: 7,
        completedSteps: 3,
        exitInterviewCompleted: false,
    },
];

// ─── Worker Reviews ───
export const MOCK_WORKER_REVIEWS: WorkerReview[] = [
    {
        id: "wr1",
        workerProfileId: "wp1",
        workerName: "Alex Rivera",
        reviewerId: "u1",
        reviewerName: "Sarah Kim (VP Production)",
        reviewType: "periodic",
        targetType: "employee",
        overallRating: 5,
        qualityRating: 5,
        timelinessRating: 5,
        communicationRating: 5,
        professionalismRating: 5,
        reliabilityRating: 5,
        safetyRating: 5,
        strengths: "Exceptional leadership on multi-site projects. Consistently under budget.",
        goals: "Develop vendor management team. Lead SXSW 2027 planning.",
        comments: "Top performer. Promotion track.",
        wouldReengage: true,
        reviewPeriodStart: "2025-07-01",
        reviewPeriodEnd: "2026-01-31",
        reviewDate: "2026-02-10",
        acknowledgedAt: "2026-02-11T09:00:00Z",
    },
    {
        id: "wr2",
        workerProfileId: "wp5",
        workerName: "Sam Okafor",
        projectName: "Coachella 2026",
        reviewerId: "u2",
        reviewerName: "Jordan Park",
        reviewType: "project_completion",
        targetType: "freelancer",
        overallRating: 5,
        qualityRating: 5,
        timelinessRating: 4,
        communicationRating: 5,
        professionalismRating: 5,
        reliabilityRating: 5,
        safetyRating: 5,
        strengths: "Brilliant design work. Creative problem solver under pressure.",
        areasForImprovement: "Could improve on initial timeline estimates.",
        wouldReengage: true,
        reviewDate: "2026-02-20",
    },
    {
        id: "wr3",
        workerProfileId: "wp7",
        workerName: "Derek Williams",
        reviewerId: "u1",
        reviewerName: "Alex Rivera",
        reviewType: "periodic",
        targetType: "contractor",
        overallRating: 4,
        qualityRating: 4,
        timelinessRating: 3,
        communicationRating: 4,
        professionalismRating: 4,
        reliabilityRating: 4,
        strengths: "Good organizational skills. Reliable.",
        areasForImprovement: "Needs to improve proactive communication on delays.",
        goals: "Complete PMP certification by Q3 2026.",
        wouldReengage: true,
        reviewPeriodStart: "2025-09-01",
        reviewPeriodEnd: "2026-02-01",
        reviewDate: "2026-02-05",
    },
    {
        id: "wr4",
        workerProfileId: "wp4",
        workerName: "Carlos Mendez",
        projectName: "Art Basel 2025",
        reviewerId: "u2",
        reviewerName: "Jordan Park",
        reviewType: "project_completion",
        targetType: "employee",
        overallRating: 5,
        qualityRating: 5,
        timelinessRating: 5,
        communicationRating: 4,
        professionalismRating: 5,
        reliabilityRating: 5,
        safetyRating: 5,
        strengths: "Rock solid. Third season and still the best rigger on the team.",
        wouldReengage: true,
        reviewDate: "2025-12-20",
        acknowledgedAt: "2025-12-21T10:00:00Z",
    },
    {
        id: "wr5",
        workerProfileId: "wp10",
        workerName: "Travis Moore",
        reviewerId: "u1",
        reviewerName: "Alex Rivera",
        reviewType: "periodic",
        targetType: "employee",
        overallRating: 3,
        qualityRating: 3,
        timelinessRating: 3,
        communicationRating: 3,
        professionalismRating: 4,
        reliabilityRating: 3,
        safetyRating: 4,
        strengths: "Reliable attendance. Good safety record.",
        areasForImprovement:
            "Inventory accuracy has declined. Process adherence needs improvement.",
        wouldReengage: true,
        reviewPeriodStart: "2025-07-01",
        reviewPeriodEnd: "2026-01-31",
        reviewDate: "2026-02-01",
    },
];

// ─── Classification Assessments ───
export const MOCK_CLASSIFICATION_ASSESSMENTS: ClassificationAssessment[] = [
    {
        id: "ca1",
        workerProfileId: "wp5",
        workerName: "Sam Okafor",
        assessmentMethod: "abc_test",
        assessmentDate: "2026-01-15",
        nextAssessmentDate: "2026-07-15",
        result: "properly_classified",
        score: 92,
        factors: {
            a_free_from_control: true,
            b_outside_usual_business: true,
            c_independent_trade: true,
            sets_own_hours: true,
            provides_own_tools: true,
            works_for_others: true,
            invoice_based: true,
        },
        assessorId: "u1",
        assessorName: "Alex Rivera",
        rationale:
            "Sam operates independently, sets own hours, provides own design tools, invoices for completed work, and regularly works for other production companies.",
        reclassificationCompleted: false,
        supportingDocUrls: [],
    },
    {
        id: "ca2",
        workerProfileId: "wp8",
        workerName: "Kenji Tanaka",
        assessmentMethod: "abc_test",
        assessmentDate: "2025-12-01",
        nextAssessmentDate: "2026-06-01",
        result: "at_risk",
        score: 65,
        factors: {
            a_free_from_control: true,
            b_outside_usual_business: false,
            c_independent_trade: true,
            sets_own_hours: false,
            provides_own_tools: false,
            works_for_others: true,
            invoice_based: true,
        },
        assessorId: "u1",
        assessorName: "Alex Rivera",
        rationale:
            "Kenji works primarily on our projects, uses our AV equipment, and follows our scheduling. Factor B (outside usual course of business) fails — AV work is core to our operations.",
        recommendedAction:
            "Review engagement structure. Consider converting to W-2 contract or restructuring SOW to project-based deliverables.",
        reclassifyTo: "contract_employee",
        reclassificationCompleted: false,
        supportingDocUrls: [],
    },
];
