/* ═══════════════════════════════════════════════════════════════
   PLAYBOOK — CRM & Revenue Pipeline Mock Data
   Migration 013 entities
   ═══════════════════════════════════════════════════════════════ */

import type {
    Opportunity,
    OpportunityActivity,
    ChangeOrder,
    RevenueSchedule,
    AccountHealthScore,
} from "@/types";

// ─── Opportunities ───

export const MOCK_OPPORTUNITIES: Opportunity[] = [
    {
        id: "opp-1",
        companyId: "comp-nike",
        primaryContactId: "cont-sarah",
        leadId: "lead-1",
        name: "SXSW 2027 Brand Activation",
        description: "Large-scale brand activation at SXSW featuring interactive installations, product demos, and influencer meetups.",
        type: "new_business",
        stage: "negotiation",
        value: 520000,
        probability: 70,
        weightedValue: 364000,
        currency: "USD",
        expectedCloseDate: "2026-04-15",
        assignedTo: "u1",
        assignedToName: "Alex Rivera",
        nextStep: "Send revised pricing with VIP lounge option",
        lastActivityAt: "2026-02-24T14:30:00Z",
        tags: ["sxsw", "brand-activation"],
        companyName: "Nike",
        contactName: "Sarah Chen",
        contactEmail: "sarah@nike.com",
        organizationId: "org-1",
        createdAt: "2026-01-15T00:00:00Z",
        updatedAt: "2026-02-24T14:30:00Z",
    },
    {
        id: "opp-2",
        companyId: "comp-lv",
        primaryContactId: "cont-pierre",
        name: "Art Basel 2026 Installation",
        description: "Immersive art installation combining digital projection mapping with physical sculpture for Art Basel Miami.",
        type: "new_business",
        stage: "proposal_sent",
        value: 1350000,
        probability: 45,
        weightedValue: 607500,
        currency: "USD",
        expectedCloseDate: "2026-05-01",
        assignedTo: "u2",
        assignedToName: "Jordan Park",
        nextStep: "Follow up on proposal — client reviewing internally",
        lastActivityAt: "2026-02-20T10:00:00Z",
        tags: ["art-basel", "installation"],
        companyName: "Louis Vuitton",
        contactName: "Pierre Moreau",
        contactEmail: "pierre@lv.com",
        organizationId: "org-1",
        createdAt: "2026-02-01T00:00:00Z",
        updatedAt: "2026-02-20T10:00:00Z",
    },
    {
        id: "opp-3",
        companyId: "comp-tesla",
        primaryContactId: "cont-mike",
        name: "CES 2027 Booth Design & Build",
        description: "Full booth design, fabrication, and on-site management for Tesla at CES 2027.",
        type: "new_business",
        stage: "discovery",
        value: 880000,
        probability: 25,
        weightedValue: 220000,
        currency: "USD",
        expectedCloseDate: "2026-06-15",
        assignedTo: "u1",
        assignedToName: "Alex Rivera",
        nextStep: "Schedule discovery call with VP of Events",
        lastActivityAt: "2026-02-22T09:00:00Z",
        tags: ["ces", "booth"],
        companyName: "Tesla",
        contactName: "Mike Wong",
        contactEmail: "mike@tesla.com",
        organizationId: "org-1",
        createdAt: "2026-02-15T00:00:00Z",
        updatedAt: "2026-02-22T09:00:00Z",
    },
    {
        id: "opp-4",
        companyId: "comp-apple",
        primaryContactId: "cont-lisa",
        name: "Product Launch Experiential Event",
        description: "Exclusive product launch event with immersive brand storytelling and media experience.",
        type: "new_business",
        stage: "qualification",
        value: 2200000,
        probability: 30,
        weightedValue: 660000,
        currency: "USD",
        expectedCloseDate: "2026-07-01",
        assignedTo: "u2",
        assignedToName: "Jordan Park",
        nextStep: "Confirm budget range and decision timeline",
        lastActivityAt: "2026-02-23T16:00:00Z",
        tags: ["launch", "experiential"],
        companyName: "Apple",
        contactName: "Lisa Park",
        contactEmail: "lisa@apple.com",
        organizationId: "org-1",
        createdAt: "2026-02-20T00:00:00Z",
        updatedAt: "2026-02-23T16:00:00Z",
    },
    {
        id: "opp-5",
        companyId: "comp-glossier",
        primaryContactId: "cont-emma",
        name: "Holiday Pop-Up 2026 — Multi-City",
        description: "Expansion of successful NYC pop-up to LA and Chicago for the holiday season.",
        type: "expansion",
        stage: "proposal_review",
        value: 425000,
        probability: 60,
        weightedValue: 255000,
        currency: "USD",
        expectedCloseDate: "2026-04-30",
        assignedTo: "u2",
        assignedToName: "Jordan Park",
        nextStep: "Client reviewing multi-city logistics plan",
        lastActivityAt: "2026-02-21T11:00:00Z",
        tags: ["pop-up", "multi-city", "expansion"],
        companyName: "Glossier",
        contactName: "Emma Liu",
        contactEmail: "emma@glossier.com",
        organizationId: "org-1",
        createdAt: "2026-02-10T00:00:00Z",
        updatedAt: "2026-02-21T11:00:00Z",
    },
    {
        id: "opp-6",
        companyId: "comp-coachella",
        primaryContactId: "cont-derek",
        name: "Coachella 2027 Main Stage Renewal",
        description: "Renewal of the main stage design and fabrication contract for Coachella 2027.",
        type: "renewal",
        stage: "contract_sent",
        value: 3800000,
        probability: 85,
        weightedValue: 3230000,
        currency: "USD",
        expectedCloseDate: "2026-03-30",
        assignedTo: "u1",
        assignedToName: "Alex Rivera",
        nextStep: "Awaiting signed contract — verbal commitment received",
        lastActivityAt: "2026-02-25T08:00:00Z",
        tags: ["coachella", "renewal", "main-stage"],
        companyName: "Coachella",
        contactName: "Derek Allen",
        contactEmail: "derek@coachella.com",
        organizationId: "org-1",
        createdAt: "2026-01-20T00:00:00Z",
        updatedAt: "2026-02-25T08:00:00Z",
    },
    {
        id: "opp-7",
        companyId: "comp-nike",
        primaryContactId: "cont-sarah",
        name: "Nike Air Max Day Activation",
        description: "Interactive sneaker customization experience for Air Max Day celebration.",
        type: "upsell",
        stage: "proposal_sent",
        value: 280000,
        probability: 55,
        weightedValue: 154000,
        currency: "USD",
        expectedCloseDate: "2026-03-26",
        assignedTo: "u1",
        assignedToName: "Alex Rivera",
        nextStep: "Proposal sent — waiting for feedback",
        lastActivityAt: "2026-02-18T15:00:00Z",
        tags: ["nike", "upsell", "air-max"],
        companyName: "Nike",
        contactName: "Sarah Chen",
        contactEmail: "sarah@nike.com",
        organizationId: "org-1",
        createdAt: "2026-02-05T00:00:00Z",
        updatedAt: "2026-02-18T15:00:00Z",
    },
    {
        id: "opp-8",
        companyId: "comp-sf",
        name: "Dreamforce Expo 2026",
        description: "Expo booth design and build for Salesforce Dreamforce conference.",
        type: "new_business",
        stage: "lost",
        value: 700000,
        probability: 0,
        weightedValue: 0,
        currency: "USD",
        expectedCloseDate: "2026-02-15",
        assignedTo: "u1",
        assignedToName: "Alex Rivera",
        lostReasonNote: "Went with incumbent vendor — price competitive but timing was an issue",
        competitor: "Freeman XP",
        tags: ["dreamforce", "expo"],
        companyName: "Salesforce",
        organizationId: "org-1",
        createdAt: "2025-11-01T00:00:00Z",
        updatedAt: "2026-02-15T00:00:00Z",
    },
];

// ─── Opportunity Activities ───

export const MOCK_OPPORTUNITY_ACTIVITIES: OpportunityActivity[] = [
    {
        id: "oa-1",
        opportunityId: "opp-1",
        type: "meeting",
        subject: "Discovery call with Nike Events team",
        description: "Discussed scope, timeline, and budget for SXSW activation. Client confirmed $500K–600K range.",
        performedBy: "u1",
        performedByName: "Alex Rivera",
        performedAt: "2026-01-20T10:00:00Z",
        durationMinutes: 45,
        outcome: "Positive — moving to qualification",
        organizationId: "org-1",
        createdAt: "2026-01-20T11:00:00Z",
    },
    {
        id: "oa-2",
        opportunityId: "opp-1",
        type: "proposal_sent",
        subject: "Proposal delivered — SXSW 2027 Activation",
        description: "Sent comprehensive proposal with 3 tier options ($420K, $520K, $650K).",
        performedBy: "u1",
        performedByName: "Alex Rivera",
        performedAt: "2026-02-05T14:00:00Z",
        outcome: "Client acknowledged receipt",
        organizationId: "org-1",
        createdAt: "2026-02-05T14:30:00Z",
    },
    {
        id: "oa-3",
        opportunityId: "opp-1",
        type: "call",
        subject: "Pricing negotiation call",
        description: "Client wants the mid-tier option but with VIP lounge from the top tier. Negotiating delta.",
        contactId: "cont-sarah",
        contactName: "Sarah Chen",
        performedBy: "u1",
        performedByName: "Alex Rivera",
        performedAt: "2026-02-24T14:00:00Z",
        durationMinutes: 30,
        outcome: "Agreed to send revised pricing by end of week",
        organizationId: "org-1",
        createdAt: "2026-02-24T14:30:00Z",
    },
    {
        id: "oa-4",
        opportunityId: "opp-6",
        type: "meeting",
        subject: "Coachella 2027 renewal kick-off",
        description: "Reviewed 2026 performance, discussed 2027 enhancements. Strong relationship — verbal commitment to renew.",
        contactId: "cont-derek",
        contactName: "Derek Allen",
        performedBy: "u1",
        performedByName: "Alex Rivera",
        performedAt: "2026-02-10T09:00:00Z",
        durationMinutes: 60,
        outcome: "Verbal commitment — contract to follow",
        organizationId: "org-1",
        createdAt: "2026-02-10T10:00:00Z",
    },
    {
        id: "oa-5",
        opportunityId: "opp-6",
        type: "contract_sent",
        subject: "Renewal contract sent for signature",
        description: "Sent 2027 main stage contract via DocuSign. Same terms as 2026 with 8% increase for enhanced LED package.",
        performedBy: "u1",
        performedByName: "Alex Rivera",
        performedAt: "2026-02-25T08:00:00Z",
        outcome: "Awaiting signature — expected within 5 days",
        organizationId: "org-1",
        createdAt: "2026-02-25T08:30:00Z",
    },
];

// ─── Change Orders ───

export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
    {
        id: "co-1",
        projectId: "p1",
        companyId: "comp-coachella",
        number: "CO-001",
        title: "Add LED Screen Array — North Stage Wing",
        description: "Client requested additional LED screen array on the north wing to accommodate sponsor branding requirements.",
        changeType: "scope_addition",
        valueImpact: 185000,
        scheduleImpactDays: 5,
        reason: "Sponsor requirement — Pepsi branding placement",
        businessCase: "Sponsor revenue offset covers 120% of additional cost",
        status: "approved",
        requestedBy: "u1",
        requestedByName: "Alex Rivera",
        requestedAt: "2026-02-01T10:00:00Z",
        approvedBy: "u3",
        approvedAt: "2026-02-05T16:00:00Z",
        clientApprovedBy: "Derek Allen",
        clientApprovedAt: "2026-02-03T12:00:00Z",
        scopeAdditions: "4x LED panels (P3.9 outdoor, 3m×2m each), structural mounting, cable management, content management system integration",
        deliverablesAdded: [
            { name: "LED Panel Procurement", value: 95000 },
            { name: "Structural Engineering", value: 35000 },
            { name: "Installation & Integration", value: 55000 },
        ],
        deliverablesRemoved: [],
        tags: ["led", "sponsor"],
        projectName: "Coachella Main Stage 2026",
        companyName: "Coachella",
        organizationId: "org-1",
        createdAt: "2026-02-01T10:00:00Z",
        updatedAt: "2026-02-05T16:00:00Z",
    },
    {
        id: "co-2",
        projectId: "p1",
        companyId: "comp-coachella",
        number: "CO-002",
        title: "Reduce Pyrotechnics Package",
        description: "Local fire marshal imposed new restrictions. Reduced pyrotechnics scope from 12 to 8 stations.",
        changeType: "scope_reduction",
        valueImpact: -45000,
        scheduleImpactDays: 0,
        reason: "Regulatory compliance — fire marshal directive",
        status: "approved",
        requestedBy: "u1",
        requestedByName: "Alex Rivera",
        requestedAt: "2026-02-10T09:00:00Z",
        approvedBy: "u3",
        approvedAt: "2026-02-12T14:00:00Z",
        clientApprovedBy: "Derek Allen",
        clientApprovedAt: "2026-02-11T11:00:00Z",
        scopeRemovals: "4 pyrotechnics stations removed (stations 3, 7, 9, 11)",
        deliverablesAdded: [],
        deliverablesRemoved: [
            { name: "Pyro Stations 3, 7, 9, 11", value: 45000 },
        ],
        tags: ["regulatory", "pyro"],
        projectName: "Coachella Main Stage 2026",
        companyName: "Coachella",
        organizationId: "org-1",
        createdAt: "2026-02-10T09:00:00Z",
        updatedAt: "2026-02-12T14:00:00Z",
    },
    {
        id: "co-3",
        projectId: "p2",
        companyId: "comp-glossier",
        number: "CO-001",
        title: "Extended Run — 2 Additional Weeks",
        description: "Pop-up performing above expectations. Client wants to extend the run by 2 weeks.",
        changeType: "combined",
        valueImpact: 32000,
        scheduleImpactDays: 14,
        reason: "Strong foot traffic and social media engagement exceeding KPIs",
        businessCase: "Additional 2 weeks estimated to generate 40% more brand impressions at marginal cost",
        status: "pending_client",
        requestedBy: "u2",
        requestedByName: "Jordan Park",
        requestedAt: "2026-02-20T14:00:00Z",
        scopeAdditions: "2-week venue extension, additional staffing, restocking consumables",
        deliverablesAdded: [
            { name: "Venue Extension (2 weeks)", value: 18000 },
            { name: "Additional Staffing", value: 8000 },
            { name: "Consumables Restock", value: 6000 },
        ],
        deliverablesRemoved: [],
        tags: ["extension", "pop-up"],
        projectName: "Glossier Pop-Up NYC",
        companyName: "Glossier",
        organizationId: "org-1",
        createdAt: "2026-02-20T14:00:00Z",
        updatedAt: "2026-02-20T14:00:00Z",
    },
];

// ─── Revenue Schedules ───

export const MOCK_REVENUE_SCHEDULES: RevenueSchedule[] = [
    {
        id: "rs-1",
        projectId: "p1",
        dealId: "d5",
        type: "milestone",
        description: "Deposit — 30% on contract signing",
        contractedAmount: 1050000,
        invoicedAmount: 1050000,
        recognizedAmount: 1050000,
        currency: "USD",
        scheduledDate: "2025-11-15",
        invoicedAt: "2025-11-15T00:00:00Z",
        recognizedAt: "2025-11-20T00:00:00Z",
        status: "recognized",
        percentComplete: 100,
        projectName: "Coachella Main Stage 2026",
        dealTitle: "Festival Main Stage",
        organizationId: "org-1",
        createdAt: "2025-11-01T00:00:00Z",
        updatedAt: "2025-11-20T00:00:00Z",
    },
    {
        id: "rs-2",
        projectId: "p1",
        dealId: "d5",
        type: "milestone",
        description: "Fabrication complete — 30%",
        contractedAmount: 1050000,
        invoicedAmount: 1050000,
        recognizedAmount: 0,
        currency: "USD",
        scheduledDate: "2026-02-28",
        invoicedAt: "2026-02-25T00:00:00Z",
        status: "invoiced",
        percentComplete: 0,
        projectName: "Coachella Main Stage 2026",
        dealTitle: "Festival Main Stage",
        organizationId: "org-1",
        createdAt: "2025-11-01T00:00:00Z",
        updatedAt: "2026-02-25T00:00:00Z",
    },
    {
        id: "rs-3",
        projectId: "p1",
        dealId: "d5",
        type: "milestone",
        description: "Load-in complete — 20%",
        contractedAmount: 700000,
        invoicedAmount: 0,
        recognizedAmount: 0,
        currency: "USD",
        scheduledDate: "2026-04-01",
        status: "scheduled",
        percentComplete: 0,
        projectName: "Coachella Main Stage 2026",
        dealTitle: "Festival Main Stage",
        organizationId: "org-1",
        createdAt: "2025-11-01T00:00:00Z",
        updatedAt: "2025-11-01T00:00:00Z",
    },
    {
        id: "rs-4",
        projectId: "p1",
        dealId: "d5",
        type: "milestone",
        description: "Show complete + strike — 20%",
        contractedAmount: 700000,
        invoicedAmount: 0,
        recognizedAmount: 0,
        currency: "USD",
        scheduledDate: "2026-04-15",
        status: "scheduled",
        percentComplete: 0,
        projectName: "Coachella Main Stage 2026",
        dealTitle: "Festival Main Stage",
        organizationId: "org-1",
        createdAt: "2025-11-01T00:00:00Z",
        updatedAt: "2025-11-01T00:00:00Z",
    },
    {
        id: "rs-5",
        projectId: "p2",
        dealId: "d6",
        type: "milestone",
        description: "Deposit — 50% on contract signing",
        contractedAmount: 87500,
        invoicedAmount: 87500,
        recognizedAmount: 87500,
        currency: "USD",
        scheduledDate: "2025-12-10",
        invoicedAt: "2025-12-10T00:00:00Z",
        recognizedAt: "2025-12-15T00:00:00Z",
        status: "recognized",
        percentComplete: 100,
        projectName: "Glossier Pop-Up NYC",
        dealTitle: "Pop-Up Retail Experience",
        organizationId: "org-1",
        createdAt: "2025-12-05T00:00:00Z",
        updatedAt: "2025-12-15T00:00:00Z",
    },
    {
        id: "rs-6",
        projectId: "p2",
        dealId: "d6",
        type: "milestone",
        description: "Pop-up open — 30%",
        contractedAmount: 52500,
        invoicedAmount: 52500,
        recognizedAmount: 52500,
        currency: "USD",
        scheduledDate: "2026-02-01",
        invoicedAt: "2026-02-01T00:00:00Z",
        recognizedAt: "2026-02-05T00:00:00Z",
        status: "recognized",
        percentComplete: 100,
        projectName: "Glossier Pop-Up NYC",
        dealTitle: "Pop-Up Retail Experience",
        organizationId: "org-1",
        createdAt: "2025-12-05T00:00:00Z",
        updatedAt: "2026-02-05T00:00:00Z",
    },
    {
        id: "rs-7",
        projectId: "p2",
        dealId: "d6",
        type: "milestone",
        description: "Final payment — 20%",
        contractedAmount: 35000,
        invoicedAmount: 0,
        recognizedAmount: 0,
        currency: "USD",
        scheduledDate: "2026-03-15",
        status: "scheduled",
        percentComplete: 0,
        projectName: "Glossier Pop-Up NYC",
        dealTitle: "Pop-Up Retail Experience",
        organizationId: "org-1",
        createdAt: "2025-12-05T00:00:00Z",
        updatedAt: "2025-12-05T00:00:00Z",
    },
];

// ─── Account Health Scores ───

export const MOCK_ACCOUNT_HEALTH_SCORES: AccountHealthScore[] = [
    {
        id: "ahs-1",
        companyId: "comp-coachella",
        scoreDate: "2026-02-25",
        overallScore: 92,
        deliveryScore: 95,
        paymentScore: 98,
        engagementScore: 88,
        satisfactionScore: 90,
        expansionScore: 85,
        riskLevel: "low",
        riskFactors: [],
        recommendations: [
            { action: "Propose 2027 multi-stage package", priority: "medium", detail: "Client has expressed interest in expanding beyond main stage" },
        ],
        lifetimeRevenue: 7200000,
        activeProjectCount: 1,
        openOpportunityCount: 1,
        overdueInvoiceCount: 0,
        companyName: "Coachella",
        organizationId: "org-1",
        createdAt: "2026-02-25T00:00:00Z",
    },
    {
        id: "ahs-2",
        companyId: "comp-glossier",
        scoreDate: "2026-02-25",
        overallScore: 85,
        deliveryScore: 90,
        paymentScore: 88,
        engagementScore: 82,
        satisfactionScore: 85,
        expansionScore: 78,
        riskLevel: "low",
        riskFactors: [],
        recommendations: [
            { action: "Pitch multi-city expansion", priority: "high", detail: "NYC pop-up exceeding KPIs — strong case for LA and Chicago" },
        ],
        lifetimeRevenue: 175000,
        activeProjectCount: 1,
        openOpportunityCount: 1,
        overdueInvoiceCount: 0,
        companyName: "Glossier",
        organizationId: "org-1",
        createdAt: "2026-02-25T00:00:00Z",
    },
    {
        id: "ahs-3",
        companyId: "comp-nike",
        scoreDate: "2026-02-25",
        overallScore: 78,
        deliveryScore: 82,
        paymentScore: 90,
        engagementScore: 75,
        satisfactionScore: 72,
        expansionScore: 70,
        riskLevel: "medium",
        riskFactors: [
            { factor: "Engagement declining", severity: "medium", detail: "Response times increasing — last 3 emails took 5+ days" },
        ],
        recommendations: [
            { action: "Schedule executive check-in", priority: "high", detail: "Engagement score trending down — proactive outreach recommended" },
            { action: "Deliver SXSW proposal revisions promptly", priority: "high", detail: "Open negotiation needs swift response" },
        ],
        lifetimeRevenue: 0,
        activeProjectCount: 0,
        openOpportunityCount: 2,
        overdueInvoiceCount: 0,
        companyName: "Nike",
        organizationId: "org-1",
        createdAt: "2026-02-25T00:00:00Z",
    },
    {
        id: "ahs-4",
        companyId: "comp-sf",
        scoreDate: "2026-02-25",
        overallScore: 35,
        deliveryScore: 0,
        paymentScore: 0,
        engagementScore: 20,
        satisfactionScore: 40,
        expansionScore: 15,
        riskLevel: "high",
        riskFactors: [
            { factor: "Lost recent opportunity", severity: "high", detail: "Dreamforce Expo lost to Freeman XP on timing" },
            { factor: "No active projects", severity: "medium", detail: "Zero revenue relationship" },
        ],
        recommendations: [
            { action: "Re-engage with alternative event proposal", priority: "medium", detail: "Offer smaller-scale event to rebuild relationship" },
        ],
        lifetimeRevenue: 0,
        activeProjectCount: 0,
        openOpportunityCount: 0,
        overdueInvoiceCount: 0,
        companyName: "Salesforce",
        organizationId: "org-1",
        createdAt: "2026-02-25T00:00:00Z",
    },
    {
        id: "ahs-5",
        companyId: "comp-apple",
        scoreDate: "2026-02-25",
        overallScore: 55,
        deliveryScore: 0,
        paymentScore: 0,
        engagementScore: 65,
        satisfactionScore: 0,
        expansionScore: 50,
        riskLevel: "medium",
        riskFactors: [
            { factor: "New prospect — no delivery history", severity: "low", detail: "Cannot assess delivery or payment reliability" },
        ],
        recommendations: [
            { action: "Prioritize qualification", priority: "high", detail: "High-value opportunity ($2.2M) needs rapid qualification" },
        ],
        lifetimeRevenue: 0,
        activeProjectCount: 0,
        openOpportunityCount: 1,
        overdueInvoiceCount: 0,
        companyName: "Apple",
        organizationId: "org-1",
        createdAt: "2026-02-25T00:00:00Z",
    },
];

// ─── Opportunity Stage Config (for Kanban) ───

export const OPPORTUNITY_STAGES: { id: string; label: string; color: string }[] = [
    { id: "discovery", label: "Discovery", color: "var(--color-ghost)" },
    { id: "qualification", label: "Qualification", color: "var(--color-info)" },
    { id: "proposal_sent", label: "Proposal Sent", color: "var(--color-primary)" },
    { id: "proposal_review", label: "Proposal Review", color: "var(--color-secondary)" },
    { id: "negotiation", label: "Negotiation", color: "var(--color-warning)" },
    { id: "contract_sent", label: "Contract Sent", color: "var(--color-info)" },
    { id: "won", label: "Won", color: "var(--color-success)" },
    { id: "lost", label: "Lost", color: "var(--color-destructive)" },
];
