// ═══════════════════════════════════════════════════════════════════════════
// FROZEN PHOENIX — Production Lifecycle Mock Data
// ═══════════════════════════════════════════════════════════════════════════

// Note: Using 'any' arrays to avoid strict type checking on mock data
// These will be replaced with proper Supabase types after migration

// ─────────────────────────────────────────────────────────────────────────────
// LOCATIONS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_LOCATIONS = [
    {
        id: "loc-1",
        projectId: "proj-1",
        name: "Javits Center - Hall 1A",
        type: "venue",
        contactName: "Sarah Mitchell",
        contactPhone: "(212) 555-0100",
        contactEmail: "smitchell@javitscenter.com",
        description: "Main exhibition hall for brand activation",
        capacity: 5000,
        squareFootage: 50000,
        amenities: ["WiFi", "Power (200A 3-phase)", "Loading Dock", "Freight Elevator"],
        restrictions: ["No open flames", "No fog machines without approval", "Union labor required"],
        accessStartDate: "2024-03-15",
        accessEndDate: "2024-03-22",
        loadInWindows: [
            { date: "2024-03-15", startTime: "08:00", endTime: "18:00" },
            { date: "2024-03-16", startTime: "08:00", endTime: "18:00" },
        ],
        loadOutWindows: [
            { date: "2024-03-21", startTime: "18:00", endTime: "23:00" },
            { date: "2024-03-22", startTime: "08:00", endTime: "18:00" },
        ],
        address: {
            street1: "429 11th Avenue",
            city: "New York",
            state: "NY",
            postalCode: "10001",
            country: "USA",
        },
        parkingInfo: "Loading dock access via 34th Street entrance",
        dockInfo: "Dock #4 reserved for our load-in",
        purpose: "Primary activation venue",
        dailyRate: 25000,
        totalCost: 175000,
        powerAvailable: "200A 3-phase, 400A single-phase",
        internetAvailable: true,
        insuranceRequired: true,
        permitsRequired: ["Fire permit", "Assembly permit"],
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "loc-2",
        projectId: "proj-1",
        name: "Brooklyn Navy Yard - Building 77",
        type: "fabrication_shop",
        contactName: "Mike Torres",
        contactPhone: "(718) 555-0200",
        contactEmail: "mike@bnyshops.com",
        description: "Fabrication and staging facility",
        squareFootage: 15000,
        amenities: ["Heavy power", "Spray booth", "CNC router", "Welding stations"],
        restrictions: [],
        address: {
            street1: "141 Flushing Avenue",
            city: "Brooklyn",
            state: "NY",
            postalCode: "11205",
            country: "USA",
        },
        purpose: "Fabrication and pre-assembly",
        dailyRate: 2500,
        powerAvailable: "400A 3-phase",
        internetAvailable: true,
        insuranceRequired: true,
        permitsRequired: [],
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "loc-3",
        projectId: "proj-1",
        name: "Newark Warehouse",
        type: "warehouse",
        contactName: "Tom Bradley",
        contactPhone: "(973) 555-0300",
        contactEmail: "tbradley@nwkwarehouse.com",
        description: "Storage and staging warehouse",
        squareFootage: 25000,
        amenities: ["Climate controlled", "24/7 access", "Forklift", "Pallet racking"],
        restrictions: [],
        address: {
            street1: "500 Industrial Way",
            city: "Newark",
            state: "NJ",
            postalCode: "07114",
            country: "USA",
        },
        purpose: "Asset storage and staging",
        dailyRate: 500,
        internetAvailable: true,
        insuranceRequired: false,
        permitsRequired: [],
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// ACTIVATIONS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_ACTIVATIONS = [
    {
        id: "act-1",
        projectId: "proj-1",
        locationId: "loc-1",
        name: "Main Stage Experience",
        type: "stage",
        status: "build",
        leadId: "crew-1",
        teamIds: ["crew-1", "crew-2", "crew-3"],
        vendorIds: ["vendor-1", "vendor-2"],
        description: "40x60 main stage with LED wall, lighting rig, and immersive audio",
        dimensions: { width: 60, depth: 40, height: 24, unit: "ft" },
        components: [
            { id: "comp-1", name: "LED Wall - 20x12", type: "av", quantity: 1, status: "ordered", vendorId: "vendor-1", cost: 45000 },
            { id: "comp-2", name: "Truss System", type: "structural", quantity: 1, status: "fabricating", cost: 25000 },
            { id: "comp-3", name: "Lighting Package", type: "electrical", quantity: 1, status: "ready", vendorId: "vendor-2", cost: 18000 },
            { id: "comp-4", name: "Audio System", type: "av", quantity: 1, status: "ordered", vendorId: "vendor-1", cost: 22000 },
        ],
        installDate: "2024-03-17",
        strikeDate: "2024-03-21",
        operatingHours: [
            { date: "2024-03-18", startTime: "10:00", endTime: "20:00" },
            { date: "2024-03-19", startTime: "10:00", endTime: "20:00" },
            { date: "2024-03-20", startTime: "10:00", endTime: "18:00" },
        ],
        zone: "Hall 1A - North",
        experienceGoals: ["Brand immersion", "Product showcase", "Social media moments"],
        targetAudience: "Tech enthusiasts 25-45",
        expectedFootfall: 15000,
        budget: 150000,
        powerRequirements: "100A 3-phase",
        staffingRequirements: [
            { role: "Stage Manager", quantity: 1, hoursPerDay: 12, skillsRequired: ["Stage management", "AV coordination"] },
            { role: "AV Tech", quantity: 2, hoursPerDay: 10, skillsRequired: ["LED operation", "Audio mixing"] },
            { role: "Lighting Tech", quantity: 1, hoursPerDay: 10, skillsRequired: ["Lighting programming"] },
        ],
        weatherContingency: "Indoor venue - N/A",
        createdAt: "2024-01-20T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "act-2",
        projectId: "proj-1",
        locationId: "loc-1",
        name: "Interactive Demo Pods",
        type: "booth",
        status: "design",
        leadId: "crew-2",
        teamIds: ["crew-2", "crew-4"],
        vendorIds: ["vendor-3"],
        description: "6 interactive demo stations showcasing product features",
        dimensions: { width: 80, depth: 30, height: 10, unit: "ft" },
        components: [
            { id: "comp-5", name: "Demo Pod Structure", type: "structural", quantity: 6, status: "pending", cost: 36000 },
            { id: "comp-6", name: "Touch Screens", type: "technology", quantity: 12, status: "ordered", cost: 24000 },
            { id: "comp-7", name: "Custom Graphics", type: "signage", quantity: 1, status: "pending", vendorId: "vendor-3", cost: 8000 },
        ],
        installDate: "2024-03-17",
        strikeDate: "2024-03-21",
        zone: "Hall 1A - East",
        experienceGoals: ["Hands-on product demos", "Lead capture", "Education"],
        targetAudience: "Potential customers",
        expectedFootfall: 8000,
        budget: 85000,
        powerRequirements: "60A single-phase",
        staffingRequirements: [
            { role: "Demo Specialist", quantity: 6, hoursPerDay: 8, skillsRequired: ["Product knowledge", "Customer service"] },
            { role: "Tech Support", quantity: 1, hoursPerDay: 10, skillsRequired: ["Troubleshooting", "Software"] },
        ],
        createdAt: "2024-01-20T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// EVENTS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_EVENTS = [
    {
        id: "evt-1",
        projectId: "proj-1",
        locationId: "loc-1",
        activationId: "act-1",
        name: "Opening Keynote",
        type: "show",
        status: "confirmed",
        producerId: "user-1",
        stageManagerId: "crew-1",
        attendeeCount: 500,
        vipCount: 50,
        description: "CEO keynote presentation with product reveal",
        runOfShow: [
            { id: "ros-1", time: "09:30", duration: 15, description: "Doors open, guests seated", responsibleParty: "Front of House", cueNumber: "Q1" },
            { id: "ros-2", time: "09:45", duration: 5, description: "House lights dim, video roll", responsibleParty: "AV", cueNumber: "Q2" },
            { id: "ros-3", time: "09:50", duration: 30, description: "CEO keynote", responsibleParty: "Stage Manager", cueNumber: "Q3" },
            { id: "ros-4", time: "10:20", duration: 10, description: "Product reveal", responsibleParty: "AV", cueNumber: "Q4" },
            { id: "ros-5", time: "10:30", duration: 15, description: "Q&A session", responsibleParty: "Stage Manager", cueNumber: "Q5" },
            { id: "ros-6", time: "10:45", duration: 5, description: "Closing, house lights up", responsibleParty: "AV", cueNumber: "Q6" },
        ],
        date: "2024-03-18",
        doorsTime: "09:30",
        startTime: "10:00",
        endTime: "11:00",
        specificLocation: "Main Stage",
        purpose: "Brand launch and product announcement",
        budget: 25000,
        cancellationPolicy: "48-hour notice required",
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "evt-2",
        projectId: "proj-1",
        locationId: "loc-1",
        activationId: "act-1",
        name: "Technical Rehearsal",
        type: "rehearsal",
        status: "scheduled",
        producerId: "user-1",
        stageManagerId: "crew-1",
        description: "Full technical rehearsal with all AV elements",
        runOfShow: [],
        date: "2024-03-17",
        startTime: "14:00",
        endTime: "20:00",
        specificLocation: "Main Stage",
        purpose: "Technical preparation and cue-to-cue",
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "evt-3",
        projectId: "proj-1",
        locationId: "loc-1",
        name: "VIP Reception",
        type: "vip",
        status: "confirmed",
        producerId: "user-1",
        attendeeCount: 100,
        vipCount: 100,
        description: "Exclusive evening reception for VIP guests and press",
        runOfShow: [
            { id: "ros-7", time: "18:00", duration: 30, description: "Arrival and cocktails", responsibleParty: "Catering", cueNumber: "V1" },
            { id: "ros-8", time: "18:30", duration: 15, description: "Welcome remarks", responsibleParty: "Client", cueNumber: "V2" },
            { id: "ros-9", time: "18:45", duration: 45, description: "Networking and demos", responsibleParty: "Demo Team", cueNumber: "V3" },
            { id: "ros-10", time: "19:30", duration: 30, description: "Dinner service", responsibleParty: "Catering", cueNumber: "V4" },
        ],
        date: "2024-03-18",
        doorsTime: "18:00",
        startTime: "18:00",
        endTime: "21:00",
        specificLocation: "VIP Lounge - Hall 1A Mezzanine",
        purpose: "VIP engagement and press relations",
        budget: 35000,
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// ACTIVITIES
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_ACTIVITIES = [
    {
        id: "activity-1",
        projectId: "proj-1",
        eventId: "evt-1",
        activationId: "act-1",
        name: "Product Demo - Feature A",
        type: "demo",
        status: "planned",
        leadId: "crew-4",
        staffIds: ["crew-4", "crew-5"],
        participantCount: 20,
        description: "Hands-on demonstration of Feature A capabilities",
        requirements: ["Demo unit", "Presentation screen", "Microphone"],
        startTime: "11:00",
        endTime: "11:30",
        frequency: "hourly",
        specificLocation: "Demo Pod 1",
        objective: "Educate attendees on Feature A benefits",
        instructions: "Follow demo script v2.1. Allow 5 min for Q&A.",
        equipmentNeeded: ["Demo tablet", "Wireless presenter", "Product samples"],
        contingencyPlan: "If demo unit fails, use backup tablet with video walkthrough",
        createdAt: "2024-02-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "activity-2",
        projectId: "proj-1",
        eventId: "evt-3",
        name: "Photo Opportunity",
        type: "photo_op",
        status: "planned",
        leadId: "crew-6",
        staffIds: ["crew-6"],
        description: "Branded photo opportunity with instant social sharing",
        requirements: ["Photo backdrop", "Ring light", "iPad for sharing"],
        startTime: "18:00",
        endTime: "20:30",
        frequency: "continuous",
        specificLocation: "VIP Lounge entrance",
        objective: "Generate social media content and brand awareness",
        instructions: "Capture photos, apply branded overlay, offer instant sharing via email/text",
        equipmentNeeded: ["DSLR camera", "Photo printer", "Backdrop", "Lighting kit"],
        createdAt: "2024-02-15T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCTION TASKS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTION_TASKS = [
    {
        id: "ptask-1",
        projectId: "proj-1",
        department: "fabrication",
        phase: "fabrication",
        assigneeId: "crew-1",
        assigneeName: "Marcus Johnson",
        title: "Fabricate main stage deck",
        description: "Build 40x60 stage deck with custom finish",
        deliverables: ["Stage deck panels", "Fascia", "Stairs"],
        acceptanceCriteria: ["Level within 1/8\"", "Finish matches approved sample", "Load rating certified"],
        startDate: "2024-02-15",
        dueDate: "2024-03-10",
        estimatedHours: 240,
        actualHours: 180,
        locationId: "loc-2",
        activationId: "act-1",
        priority: "high",
        impactIfDelayed: "Delays entire load-in schedule",
        status: "in_progress",
        percentComplete: 75,
        blockers: [],
        dependencies: [],
        dependents: ["ptask-2", "ptask-3"],
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ptask-2",
        projectId: "proj-1",
        department: "av",
        phase: "load_in",
        assigneeId: "crew-3",
        assigneeName: "David Kim",
        vendorId: "vendor-1",
        title: "Install LED wall",
        description: "Install and calibrate 20x12 LED wall on main stage",
        deliverables: ["LED wall installed", "Calibration complete", "Content tested"],
        acceptanceCriteria: ["No dead pixels", "Color calibrated", "Content plays correctly"],
        startDate: "2024-03-17",
        dueDate: "2024-03-17",
        estimatedHours: 8,
        locationId: "loc-1",
        activationId: "act-1",
        priority: "critical",
        impactIfDelayed: "Keynote cannot proceed without LED wall",
        status: "todo",
        percentComplete: 0,
        blockers: [],
        dependencies: ["ptask-1"],
        dependents: ["ptask-4"],
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ptask-3",
        projectId: "proj-1",
        department: "lighting",
        phase: "load_in",
        assigneeId: "crew-2",
        assigneeName: "Sarah Chen",
        title: "Hang and focus lighting",
        description: "Install lighting rig and program show looks",
        deliverables: ["Lights hung", "Focused", "Show programmed"],
        acceptanceCriteria: ["All fixtures working", "Show file approved", "Backup saved"],
        startDate: "2024-03-17",
        dueDate: "2024-03-17",
        estimatedHours: 10,
        locationId: "loc-1",
        activationId: "act-1",
        priority: "high",
        impactIfDelayed: "Rehearsal cannot proceed",
        status: "todo",
        percentComplete: 0,
        blockers: [],
        dependencies: ["ptask-1"],
        dependents: ["ptask-4"],
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ptask-4",
        projectId: "proj-1",
        department: "production",
        phase: "rehearsal",
        assigneeId: "crew-1",
        assigneeName: "Marcus Johnson",
        title: "Technical rehearsal",
        description: "Full cue-to-cue rehearsal with all elements",
        deliverables: ["Rehearsal complete", "Cue sheet finalized", "Issues resolved"],
        acceptanceCriteria: ["All cues run smoothly", "Timing confirmed", "Client approved"],
        startDate: "2024-03-17",
        dueDate: "2024-03-17",
        estimatedHours: 6,
        locationId: "loc-1",
        activationId: "act-1",
        priority: "critical",
        impactIfDelayed: "Show quality compromised",
        status: "backlog",
        percentComplete: 0,
        blockers: [],
        dependencies: ["ptask-2", "ptask-3"],
        dependents: [],
        createdAt: "2024-02-01T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// MILESTONES
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_MILESTONES = [
    {
        id: "ms-1",
        projectId: "proj-1",
        phase: "design",
        name: "Design Approval",
        description: "Client approval of final design package",
        ownerId: "user-1",
        approverIds: ["client-1"],
        deliverables: [
            { id: "del-1", name: "3D Renderings", type: "document", status: "approved", dueDate: "2024-02-01" },
            { id: "del-2", name: "Floor Plan", type: "document", status: "approved", dueDate: "2024-02-01" },
            { id: "del-3", name: "Budget Estimate", type: "document", status: "approved", dueDate: "2024-02-01" },
        ],
        dueDate: "2024-02-01",
        completedAt: "2024-01-30T15:00:00Z",
        isCriticalPath: true,
        clientFacing: true,
        status: "approved",
        paymentTrigger: true,
        paymentAmount: 75000,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ms-2",
        projectId: "proj-1",
        phase: "fabrication",
        name: "Fabrication Complete",
        description: "All fabrication elements completed and ready for transport",
        ownerId: "crew-1",
        approverIds: ["user-1"],
        deliverables: [
            { id: "del-4", name: "Stage Deck", type: "asset", status: "pending", dueDate: "2024-03-10" },
            { id: "del-5", name: "Demo Pods", type: "asset", status: "pending", dueDate: "2024-03-10" },
            { id: "del-6", name: "Signage Package", type: "asset", status: "pending", dueDate: "2024-03-10" },
        ],
        dueDate: "2024-03-10",
        isCriticalPath: true,
        clientFacing: false,
        status: "in_progress",
        paymentTrigger: false,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ms-3",
        projectId: "proj-1",
        phase: "show",
        name: "Event Execution",
        description: "Successful execution of all scheduled events",
        ownerId: "user-1",
        approverIds: ["client-1"],
        deliverables: [
            { id: "del-7", name: "Opening Keynote", type: "other", status: "pending", dueDate: "2024-03-18" },
            { id: "del-8", name: "VIP Reception", type: "other", status: "pending", dueDate: "2024-03-18" },
            { id: "del-9", name: "Daily Operations", type: "other", status: "pending", dueDate: "2024-03-20" },
        ],
        dueDate: "2024-03-20",
        isCriticalPath: true,
        clientFacing: true,
        status: "pending",
        paymentTrigger: true,
        paymentAmount: 100000,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHIPMENTS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_SHIPMENTS = [
    {
        id: "ship-1",
        projectId: "proj-1",
        number: "SHP-2024-001",
        type: "outbound",
        carrierName: "XPO Logistics",
        coordinatorId: "user-1",
        description: "Main stage elements - Truck 1 of 2",
        items: [
            { id: "si-1", description: "Stage deck panels (20)", quantity: 20, weight: 2000, value: 15000 },
            { id: "si-2", description: "Truss sections", quantity: 12, weight: 1500, value: 8000 },
            { id: "si-3", description: "Stairs and railings", quantity: 1, weight: 500, value: 3000 },
        ],
        totalWeight: 4000,
        weightUnit: "lbs",
        totalPieces: 33,
        pickupDate: "2024-03-14",
        pickupTime: "06:00",
        estimatedDeliveryDate: "2024-03-15",
        originLocationId: "loc-2",
        originAddress: {
            street1: "141 Flushing Avenue",
            city: "Brooklyn",
            state: "NY",
            postalCode: "11205",
            country: "USA",
        },
        destinationLocationId: "loc-1",
        destinationAddress: {
            street1: "429 11th Avenue",
            city: "New York",
            state: "NY",
            postalCode: "10001",
            country: "USA",
        },
        priority: "standard",
        status: "booked",
        cost: 2500,
        specialInstructions: "Deliver to Dock #4. Call coordinator 30 min before arrival.",
        liftgateRequired: false,
        insideDelivery: true,
        appointmentRequired: true,
        createdAt: "2024-03-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "ship-2",
        projectId: "proj-1",
        number: "SHP-2024-002",
        type: "outbound",
        carrierName: "XPO Logistics",
        coordinatorId: "user-1",
        description: "AV and lighting equipment",
        items: [
            { id: "si-4", description: "Lighting fixtures (cases)", quantity: 8, weight: 800, value: 18000 },
            { id: "si-5", description: "Audio equipment (cases)", quantity: 6, weight: 600, value: 22000 },
            { id: "si-6", description: "Cables and accessories", quantity: 4, weight: 200, value: 2000 },
        ],
        totalWeight: 1600,
        weightUnit: "lbs",
        totalPieces: 18,
        pickupDate: "2024-03-15",
        pickupTime: "08:00",
        estimatedDeliveryDate: "2024-03-15",
        originLocationId: "loc-3",
        originAddress: {
            street1: "500 Industrial Way",
            city: "Newark",
            state: "NJ",
            postalCode: "07114",
            country: "USA",
        },
        destinationLocationId: "loc-1",
        destinationAddress: {
            street1: "429 11th Avenue",
            city: "New York",
            state: "NY",
            postalCode: "10001",
            country: "USA",
        },
        priority: "expedited",
        status: "planning",
        cost: 1800,
        specialInstructions: "Fragile equipment - handle with care",
        liftgateRequired: true,
        insideDelivery: true,
        appointmentRequired: true,
        createdAt: "2024-03-01T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// INCIDENTS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_INCIDENTS = [
    {
        id: "inc-1",
        projectId: "proj-1",
        number: "INC-2024-001",
        type: "equipment_failure",
        reportedById: "crew-3",
        involvedPartyIds: [],
        witnessIds: ["crew-1"],
        assignedToId: "user-1",
        title: "LED panel malfunction during testing",
        description: "During pre-show testing, one LED panel in the main wall displayed artifacts and then went dark. Panel is in position R3-C4.",
        immediateActions: "Isolated panel from system. Contacted vendor for replacement.",
        occurredAt: "2024-03-16T14:30:00Z",
        reportedAt: "2024-03-16T14:45:00Z",
        locationId: "loc-1",
        specificLocation: "Main Stage - LED Wall",
        severity: "moderate",
        rootCause: "Suspected power surge or manufacturing defect",
        status: "investigating",
        resolution: "",
        preventiveMeasures: "",
        insuranceClaim: false,
        estimatedCost: 5000,
        attachmentIds: [],
        followUpTaskIds: [],
        createdAt: "2024-03-16T14:45:00Z",
        createdBy: "crew-3",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CREW SHIFTS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_CREW_SHIFTS = [
    {
        id: "shift-1",
        projectId: "proj-1",
        eventId: "evt-1",
        locationId: "loc-1",
        crewMemberId: "crew-1",
        crewMemberName: "Marcus Johnson",
        role: "Stage Manager",
        department: "production",
        duties: ["Manage stage operations", "Call cues", "Coordinate crew"],
        date: "2024-03-18",
        callTime: "07:00",
        startTime: "08:00",
        endTime: "20:00",
        breakMinutes: 60,
        reportingLocation: "Production Office - Hall 1A",
        status: "confirmed",
        hourlyRate: 75,
        overtimeRate: 112.5,
        mealProvided: true,
        travelReimbursement: false,
        createdAt: "2024-03-01T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "shift-2",
        projectId: "proj-1",
        eventId: "evt-1",
        locationId: "loc-1",
        crewMemberId: "crew-2",
        crewMemberName: "Sarah Chen",
        role: "Lighting Director",
        department: "lighting",
        duties: ["Operate lighting console", "Execute show cues", "Troubleshoot issues"],
        date: "2024-03-18",
        callTime: "08:00",
        startTime: "09:00",
        endTime: "19:00",
        breakMinutes: 60,
        reportingLocation: "FOH Position - Hall 1A",
        status: "confirmed",
        hourlyRate: 65,
        overtimeRate: 97.5,
        mealProvided: true,
        travelReimbursement: false,
        createdAt: "2024-03-01T10:00:00Z",
        createdBy: "user-1",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// BUDGETS
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_BUDGETS = [
    {
        id: "budget-1",
        projectId: "proj-1",
        version: 1,
        status: "approved",
        preparedById: "user-1",
        approvedById: "user-2",
        lineItems: [],
        effectiveDate: "2024-01-15",
        totalBudget: 450000,
        totalActual: 325000,
        totalVariance: -125000,
        currency: "USD",
        contingencyPercent: 10,
        markupPercent: 15,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
];

export const MOCK_BUDGET_LINES = [
    {
        id: "bl-1",
        budgetId: "budget-1",
        category: "fabrication",
        description: "Stage deck fabrication",
        phase: "fabrication",
        quantity: 1,
        unit: "lot",
        unitCost: 45000,
        budgetedAmount: 45000,
        actualAmount: 42000,
        committedAmount: 45000,
        variance: -3000,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "bl-2",
        budgetId: "budget-1",
        category: "av",
        subcategory: "LED",
        description: "LED wall rental",
        phase: "show",
        vendorId: "vendor-1",
        quantity: 5,
        unit: "days",
        unitCost: 9000,
        budgetedAmount: 45000,
        actualAmount: 45000,
        committedAmount: 45000,
        variance: 0,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "bl-3",
        budgetId: "budget-1",
        category: "labor",
        description: "Production crew",
        phase: "show",
        quantity: 120,
        unit: "hours",
        unitCost: 75,
        budgetedAmount: 9000,
        actualAmount: 0,
        committedAmount: 9000,
        variance: -9000,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "bl-4",
        budgetId: "budget-1",
        category: "venue",
        description: "Javits Center rental",
        phase: "show",
        quantity: 7,
        unit: "days",
        unitCost: 25000,
        budgetedAmount: 175000,
        actualAmount: 175000,
        committedAmount: 175000,
        variance: 0,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
    {
        id: "bl-5",
        budgetId: "budget-1",
        category: "catering",
        description: "VIP reception catering",
        phase: "show",
        vendorId: "vendor-4",
        quantity: 100,
        unit: "guests",
        unitCost: 150,
        budgetedAmount: 15000,
        actualAmount: 0,
        committedAmount: 15000,
        variance: -15000,
        createdAt: "2024-01-15T10:00:00Z",
        createdBy: "user-1",
    },
];
