/* ═══════════════════════════════════════════════════════════════
   SCHEMA REGISTRY — P0.5 Foundation Infrastructure
   
   Maps entity names to their Zod create/update validation schemas.
   Used by the CRUD API factory and CreateEntityDialog.
   ═══════════════════════════════════════════════════════════════ */

import type { ZodSchema } from "zod";

import {
    approvalCreateSchema,
    approvalUpdateSchema,
    assetCreateSchema,
    assetUpdateSchema,
    budgetCreateSchema,
    contractCreateSchema,
    contractUpdateSchema,
    crewCreateSchema,
    crewUpdateSchema,
    dealCreateSchema,
    dealUpdateSchema,
    invoiceCreateSchema,
    invoiceUpdateSchema,
    projectCreateSchema,
    projectUpdateSchema,
    taskCreateSchema,
    taskUpdateSchema,
    vendorCreateSchema,
    vendorUpdateSchema,
} from "./schemas";

import {
    changeOrderCreateSchema,
    changeOrderUpdateSchema,
    crewShiftCreateSchema,
    crewShiftUpdateSchema,
    documentCreateSchema,
    documentUpdateSchema,
    estimateCreateSchema,
    estimateUpdateSchema,
    expenseCreateSchema,
    expenseUpdateSchema,
    incidentCreateSchema,
    incidentUpdateSchema,
    liveEventCreateSchema,
    liveEventUpdateSchema,
    milestoneCreateSchema,
    milestoneUpdateSchema,
    opportunityCreateSchema,
    opportunityUpdateSchema,
    purchaseOrderCreateSchema,
    purchaseOrderUpdateSchema,
    readinessGateCreateSchema,
    readinessGateUpdateSchema,
    rentalAgreementCreateSchema,
    rentalAgreementUpdateSchema,
    rightsCreateSchema,
    rightsUpdateSchema,
    rosCueCreateSchema,
    rosCueUpdateSchema,
    serviceRequestCreateSchema,
    serviceRequestUpdateSchema,
    shipmentCreateSchema,
    shipmentUpdateSchema,
    sowCreateSchema,
    sowUpdateSchema,
    teamCreateSchema,
    teamMemberCreateSchema,
    teamMemberUpdateSchema,
    teamUpdateSchema,
    timeEntryCreateSchema,
    timeEntryUpdateSchema,
    workOrderCreateSchema,
    workOrderUpdateSchema,
} from "./entity-schemas";

import {
    accountCreateSchema,
    accountUpdateSchema,
    activationCreateSchema,
    activationUpdateSchema,
    automationCreateSchema,
    automationUpdateSchema,
    brandGuidelineCreateSchema,
    brandGuidelineUpdateSchema,
    brandKitCreateSchema,
    brandKitUpdateSchema,
    briefCreateSchema,
    briefUpdateSchema,
    callSheetCreateSchema,
    callSheetUpdateSchema,
    campaignCreateSchema,
    campaignUpdateSchema,
    caseStudyCreateSchema,
    caseStudyUpdateSchema,
    certificationCreateSchema,
    certificationUpdateSchema,
    checklistCreateSchema,
    checklistUpdateSchema,
    clauseCreateSchema,
    clauseUpdateSchema,
    clientInvoiceCreateSchema,
    clientInvoiceUpdateSchema,
    companyCreateSchema,
    companyUpdateSchema,
    complianceChecklistCreateSchema,
    complianceChecklistUpdateSchema,
    contactCreateSchema,
    contactUpdateSchema,
    credentialCreateSchema,
    credentialUpdateSchema,
    creditNoteCreateSchema,
    creditNoteUpdateSchema,
    deckCreateSchema,
    deckUpdateSchema,
    dispatchCreateSchema,
    dispatchUpdateSchema,
    eventCreateSchema,
    eventUpdateSchema,
    insurancePolicyCreateSchema,
    insurancePolicyUpdateSchema,
    leadCreateSchema,
    leadUpdateSchema,
    locationCreateSchema,
    locationUpdateSchema,
    permitCreateSchema,
    permitUpdateSchema,
    personCreateSchema,
    personUpdateSchema,
    proposalCreateSchema,
    proposalUpdateSchema,
    purchaseRequisitionCreateSchema,
    purchaseRequisitionUpdateSchema,
    recurringInvoiceCreateSchema,
    recurringInvoiceUpdateSchema,
    techSheetCreateSchema,
    techSheetUpdateSchema,
    vendorReviewCreateSchema,
    vendorReviewUpdateSchema,
    workerProfileCreateSchema,
    workerProfileUpdateSchema,
} from "./extended-entity-schemas";

import {
    accessAuditLogCreateSchema,
    accessAuditLogUpdateSchema,
    activityLogEntryCreateSchema,
    activityLogEntryUpdateSchema,
    approvalStepCreateSchema,
    approvalStepUpdateSchema,
    assetAssignmentCreateSchema,
    assetAssignmentUpdateSchema,
    automationLogCreateSchema,
    automationLogUpdateSchema,
    brandGuidelineSectionCreateSchema,
    brandGuidelineSectionUpdateSchema,
    briefTemplateCreateSchema,
    briefTemplateUpdateSchema,
    budgetApprovalCreateSchema,
    budgetApprovalUpdateSchema,
    budgetLineItemCreateSchema,
    budgetLineItemUpdateSchema,
    calendarEventCreateSchema,
    calendarEventUpdateSchema,
    campaignAssetCreateSchema,
    campaignAssetUpdateSchema,
    campaignChannelCreateSchema,
    campaignChannelUpdateSchema,
    campaignKpiCreateSchema,
    campaignKpiUpdateSchema,
    checklistTemplateCreateSchema,
    checklistTemplateUpdateSchema,
    clauseLibraryEntryCreateSchema,
    clauseLibraryEntryUpdateSchema,
    commentCreateSchema,
    commentUpdateSchema,
    complianceRequirementCreateSchema,
    complianceRequirementUpdateSchema,
    consumableCreateSchema,
    consumableUpdateSchema,
    consumableUsageCreateSchema,
    consumableUsageUpdateSchema,
    contractObligationCreateSchema,
    contractObligationUpdateSchema,
    creativeBriefCreateSchema,
    creativeBriefUpdateSchema,
    creativeReviewCreateSchema,
    creativeReviewUpdateSchema,
    crewAvailabilityCreateSchema,
    crewAvailabilityUpdateSchema,
    dashboardWidgetCreateSchema,
    dashboardWidgetUpdateSchema,
    dataExportRequestCreateSchema,
    dataExportRequestUpdateSchema,
    digitalAssetCreateSchema,
    digitalAssetUpdateSchema,
    dispatchEntryCreateSchema,
    dispatchEntryUpdateSchema,
    documentTemplateCreateSchema,
    documentTemplateUpdateSchema,
    domainEventCreateSchema,
    domainEventUpdateSchema,
    engineeringApprovalCreateSchema,
    engineeringApprovalUpdateSchema,
    eSignatureCreateSchema,
    eSignatureUpdateSchema,
    expenseReportCreateSchema,
    expenseReportUpdateSchema,
    glAccountCreateSchema,
    glAccountUpdateSchema,
    goalCreateSchema,
    goalUpdateSchema,
    goodsReceiptCreateSchema,
    goodsReceiptUpdateSchema,
    insuranceRequirementCreateSchema,
    insuranceRequirementUpdateSchema,
    integrationCreateSchema,
    integrationUpdateSchema,
    invitationCreateSchema,
    invitationUpdateSchema,
    invoiceTemplateCreateSchema,
    invoiceTemplateUpdateSchema,
    ipRightCreateSchema,
    ipRightUpdateSchema,
    jobCostEntryCreateSchema,
    jobCostEntryUpdateSchema,
    knowledgeBaseArticleCreateSchema,
    knowledgeBaseArticleUpdateSchema,
    liveCrewAssignmentCreateSchema,
    liveCrewAssignmentUpdateSchema,
    loginAuditLogCreateSchema,
    loginAuditLogUpdateSchema,
    lostReasonCreateSchema,
    lostReasonUpdateSchema,
    maintenanceRecordCreateSchema,
    maintenanceRecordUpdateSchema,
    notificationCreateSchema,
    notificationUpdateSchema,
    obligationCreateSchema,
    obligationUpdateSchema,
    organizationCreateSchema,
    organizationUpdateSchema,
    paymentApprovalCreateSchema,
    paymentApprovalUpdateSchema,
    paymentCreateSchema,
    paymentUpdateSchema,
    payrollBatchCreateSchema,
    payrollBatchUpdateSchema,
    productionBudgetLineCreateSchema,
    productionBudgetLineUpdateSchema,
    productionChecklistCreateSchema,
    productionChecklistUpdateSchema,
    productionExpenseCreateSchema,
    productionExpenseUpdateSchema,
    productionMilestoneCreateSchema,
    productionMilestoneUpdateSchema,
    productionSopCreateSchema,
    productionSopUpdateSchema,
    productionTaskCreateSchema,
    productionTaskUpdateSchema,
    productionTimeEntryCreateSchema,
    productionTimeEntryUpdateSchema,
    profileCreateSchema,
    profileUpdateSchema,
    projectAssignmentCreateSchema,
    projectAssignmentUpdateSchema,
    projectTemplateCreateSchema,
    projectTemplateUpdateSchema,
    rateCardCreateSchema,
    rateCardUpdateSchema,
    reportDefinitionCreateSchema,
    reportDefinitionUpdateSchema,
    resilienceTargetCreateSchema,
    resilienceTargetUpdateSchema,
    resourceBookingCreateSchema,
    resourceBookingUpdateSchema,
    revenueScheduleCreateSchema,
    revenueScheduleUpdateSchema,
    rfqCreateSchema,
    rfqUpdateSchema,
    riskAssessmentCreateSchema,
    riskAssessmentUpdateSchema,
    roleChangeLogCreateSchema,
    roleChangeLogUpdateSchema,
    savedViewCreateSchema,
    savedViewUpdateSchema,
    scheduleEntryCreateSchema,
    scheduleEntryUpdateSchema,
    serviceHealthCheckCreateSchema,
    serviceHealthCheckUpdateSchema,
    shiftCreateSchema,
    shiftUpdateSchema,
    slaDefinitionCreateSchema,
    slaDefinitionUpdateSchema,
    slaTrackingCreateSchema,
    slaTrackingUpdateSchema,
    sopCreateSchema,
    sopUpdateSchema,
    stakeholderCreateSchema,
    stakeholderProjectCreateSchema,
    stakeholderProjectUpdateSchema,
    stakeholderUpdateSchema,
    temporaryAccessGrantCreateSchema,
    temporaryAccessGrantUpdateSchema,
    timesheetCreateSchema,
    timesheetUpdateSchema,
    vaultDocumentCreateSchema,
    vaultDocumentUpdateSchema,
    vehicleCreateSchema,
    vehicleUpdateSchema,
    vendorComplianceDocumentCreateSchema,
    vendorComplianceDocumentUpdateSchema,
    warehouseCreateSchema,
    warehouseUpdateSchema,
    workerOffboardingRunCreateSchema,
    workerOffboardingRunUpdateSchema,
    workerOnboardingRunCreateSchema,
    workerOnboardingRunUpdateSchema,
    workerReviewCreateSchema,
    workerReviewUpdateSchema,
    workflowCreateSchema,
    workflowUpdateSchema,
} from "./remaining-entity-schemas";

import {
    accountHealthScoreCreateSchema,
    accountHealthScoreUpdateSchema,
    activityCreateSchema,
    activityUpdateSchema,
    advanceStatusHistoryCreateSchema,
    advanceStatusHistoryUpdateSchema,
    advanceTemplateCreateSchema,
    advanceTemplateUpdateSchema,
    approvalWorkflowCreateSchema,
    approvalWorkflowUpdateSchema,
    assetTagCreateSchema,
    assetTagUpdateSchema,
    assetVersionCreateSchema,
    assetVersionUpdateSchema,
    automationExecutionCreateSchema,
    automationExecutionUpdateSchema,
    automationRuleCreateSchema,
    automationRuleUpdateSchema,
    bomCreateSchema,
    bomUpdateSchema,
    brandCreateSchema,
    brandUpdateSchema,
    catalogCategoryCreateSchema,
    catalogCategoryUpdateSchema,
    catalogItemCreateSchema,
    catalogItemUpdateSchema,
    channelTemplateCreateSchema,
    channelTemplateUpdateSchema,
    commandPositionCreateSchema,
    commandPositionUpdateSchema,
    commChannelCreateSchema,
    commChannelUpdateSchema,
    complianceTemplateCreateSchema,
    complianceTemplateUpdateSchema,
    contractAmendmentCreateSchema,
    contractAmendmentUpdateSchema,
    conversationCreateSchema,
    conversationUpdateSchema,
    credentialAssignmentCreateSchema,
    credentialAssignmentUpdateSchema,
    credentialInventoryPoolCreateSchema,
    credentialInventoryPoolUpdateSchema,
    credentialTypeCreateSchema,
    credentialTypeUpdateSchema,
    customFieldCreateSchema,
    customFieldDefinitionCreateSchema,
    customFieldDefinitionUpdateSchema,
    customFieldUpdateSchema,
    dashboardCreateSchema,
    dashboardUpdateSchema,
    departmentCreateSchema,
    departmentUpdateSchema,
    depreciationScheduleCreateSchema,
    depreciationScheduleUpdateSchema,
    documentVersionCreateSchema,
    documentVersionUpdateSchema,
    emailMessageCreateSchema,
    emailMessageUpdateSchema,
    engagementTermCreateSchema,
    engagementTermUpdateSchema,
    environmentalReadingCreateSchema,
    environmentalReadingUpdateSchema,
    equipmentCheckInCreateSchema,
    equipmentCheckInUpdateSchema,
    fohZoneCreateSchema,
    fohZoneReadingCreateSchema,
    fohZoneReadingUpdateSchema,
    fohZoneUpdateSchema,
    guestIncidentCreateSchema,
    guestIncidentUpdateSchema,
    hrCertificationCreateSchema,
    hrCertificationUpdateSchema,
    inventoryAuditCreateSchema,
    inventoryAuditUpdateSchema,
    inventoryReservationCreateSchema,
    inventoryReservationUpdateSchema,
    kitCreateSchema,
    kitUpdateSchema,
    knowledgeArticleCreateSchema,
    knowledgeArticleUpdateSchema,
    leadSourceCreateSchema,
    leadSourceUpdateSchema,
    legalHoldCreateSchema,
    legalHoldUpdateSchema,
    liveEventInstanceCreateSchema,
    liveEventInstanceUpdateSchema,
    liveFinancialSnapshotCreateSchema,
    liveFinancialSnapshotUpdateSchema,
    loadPlanCreateSchema,
    loadPlanUpdateSchema,
    logisticsEventCreateSchema,
    logisticsEventUpdateSchema,
    maintenanceScheduleCreateSchema,
    maintenanceScheduleUpdateSchema,
    messageCreateSchema,
    messageUpdateSchema,
    postEventReportCreateSchema,
    postEventReportUpdateSchema,
    posTransactionCreateSchema,
    posTransactionUpdateSchema,
    productionAdvanceCreateSchema,
    productionAdvanceItemCreateSchema,
    productionAdvanceItemUpdateSchema,
    productionAdvanceUpdateSchema,
    productionRunCreateSchema,
    productionRunUpdateSchema,
    productionVerticalCreateSchema,
    productionVerticalUpdateSchema,
    providerConnectionCreateSchema,
    providerConnectionUpdateSchema,
    qcGateCreateSchema,
    qcGateUpdateSchema,
    qualityCheckCreateSchema,
    qualityCheckTemplateCreateSchema,
    qualityCheckTemplateUpdateSchema,
    qualityCheckUpdateSchema,
    revenueRecognitionEntryCreateSchema,
    revenueRecognitionEntryUpdateSchema,
    reviewCreateSchema,
    reviewCycleCreateSchema,
    reviewCycleUpdateSchema,
    reviewUpdateSchema,
    scanEventCreateSchema,
    scanEventUpdateSchema,
    scenarioCreateSchema,
    scenarioUpdateSchema,
    slaPolicyCreateSchema,
    slaPolicyUpdateSchema,
    spaceBookingCreateSchema,
    spaceBookingUpdateSchema,
    storageObjectCreateSchema,
    storageObjectUpdateSchema,
    strikeSequenceCreateSchema,
    strikeSequenceUpdateSchema,
    surveyResponseCreateSchema,
    surveyResponseUpdateSchema,
    surveyTemplateCreateSchema,
    surveyTemplateUpdateSchema,
    syncEventCreateSchema,
    syncEventUpdateSchema,
    technicalSpecCreateSchema,
    technicalSpecUpdateSchema,
    testimonialCreateSchema,
    testimonialUpdateSchema,
    timeOffRequestCreateSchema,
    timeOffRequestUpdateSchema,
    timeTrackingPolicyCreateSchema,
    timeTrackingPolicyUpdateSchema,
    upsellEventCreateSchema,
    upsellEventUpdateSchema,
    upsellTriggerCreateSchema,
    upsellTriggerUpdateSchema,
    vendorCommunicationCreateSchema,
    vendorCommunicationUpdateSchema,
    vipGuestCreateSchema,
    vipGuestUpdateSchema,
    vipServiceRequestCreateSchema,
    vipServiceRequestUpdateSchema,
    workerClassificationCreateSchema,
    workerClassificationUpdateSchema,
    workerComplianceDocCreateSchema,
    workerComplianceDocUpdateSchema,
    workPackageCreateSchema,
    workPackageUpdateSchema,
} from "./phase-h-entity-schemas";

// ─── Registry Entry ──────────────────────────────────────────

export interface SchemaEntry {
    create: ZodSchema;
    update: ZodSchema;
}

// ─── Registry ────────────────────────────────────────────────

const SCHEMA_REGISTRY: Record<string, SchemaEntry> = {
    project: { create: projectCreateSchema, update: projectUpdateSchema },
    task: { create: taskCreateSchema, update: taskUpdateSchema },
    deal: { create: dealCreateSchema, update: dealUpdateSchema },
    contract: { create: contractCreateSchema, update: contractUpdateSchema },
    invoice: { create: invoiceCreateSchema, update: invoiceUpdateSchema },
    vendor: { create: vendorCreateSchema, update: vendorUpdateSchema },
    asset: { create: assetCreateSchema, update: assetUpdateSchema },
    crew_member: { create: crewCreateSchema, update: crewUpdateSchema },
    approval: { create: approvalCreateSchema, update: approvalUpdateSchema },
    budget: { create: budgetCreateSchema, update: budgetCreateSchema.partial() },
    opportunity: { create: opportunityCreateSchema, update: opportunityUpdateSchema },
    sow: { create: sowCreateSchema, update: sowUpdateSchema },
    scope_of_work: { create: sowCreateSchema, update: sowUpdateSchema },
    expense: { create: expenseCreateSchema, update: expenseUpdateSchema },
    work_order: { create: workOrderCreateSchema, update: workOrderUpdateSchema },
    shipment: { create: shipmentCreateSchema, update: shipmentUpdateSchema },
    change_order: { create: changeOrderCreateSchema, update: changeOrderUpdateSchema },
    service_request: { create: serviceRequestCreateSchema, update: serviceRequestUpdateSchema },
    purchase_order: { create: purchaseOrderCreateSchema, update: purchaseOrderUpdateSchema },
    milestone: { create: milestoneCreateSchema, update: milestoneUpdateSchema },
    crew_shift: { create: crewShiftCreateSchema, update: crewShiftUpdateSchema },
    time_entry: { create: timeEntryCreateSchema, update: timeEntryUpdateSchema },
    live_event: { create: liveEventCreateSchema, update: liveEventUpdateSchema },
    ros_cue: { create: rosCueCreateSchema, update: rosCueUpdateSchema },
    readiness_gate: { create: readinessGateCreateSchema, update: readinessGateUpdateSchema },
    document: { create: documentCreateSchema, update: documentUpdateSchema },
    incident: { create: incidentCreateSchema, update: incidentUpdateSchema },
    estimate: { create: estimateCreateSchema, update: estimateUpdateSchema },
    rental_agreement: { create: rentalAgreementCreateSchema, update: rentalAgreementUpdateSchema },
    rights: { create: rightsCreateSchema, update: rightsUpdateSchema },
    team: { create: teamCreateSchema, update: teamUpdateSchema },
    team_member: { create: teamMemberCreateSchema, update: teamMemberUpdateSchema },
    event: { create: eventCreateSchema, update: eventUpdateSchema },
    activation: { create: activationCreateSchema, update: activationUpdateSchema },
    lead: { create: leadCreateSchema, update: leadUpdateSchema },
    company: { create: companyCreateSchema, update: companyUpdateSchema },
    contact: { create: contactCreateSchema, update: contactUpdateSchema },
    purchase_requisition: {
        create: purchaseRequisitionCreateSchema,
        update: purchaseRequisitionUpdateSchema,
    },
    brief: { create: briefCreateSchema, update: briefUpdateSchema },
    campaign: { create: campaignCreateSchema, update: campaignUpdateSchema },
    proposal: { create: proposalCreateSchema, update: proposalUpdateSchema },
    worker_profile: { create: workerProfileCreateSchema, update: workerProfileUpdateSchema },
    workforce: { create: workerProfileCreateSchema, update: workerProfileUpdateSchema },
    brand_guideline: { create: brandGuidelineCreateSchema, update: brandGuidelineUpdateSchema },
    brand_kit: { create: brandKitCreateSchema, update: brandKitUpdateSchema },
    deck: { create: deckCreateSchema, update: deckUpdateSchema },
    tech_sheet: { create: techSheetCreateSchema, update: techSheetUpdateSchema },
    certification: { create: certificationCreateSchema, update: certificationUpdateSchema },
    compliance_checklist: {
        create: complianceChecklistCreateSchema,
        update: complianceChecklistUpdateSchema,
    },
    insurance_policy: { create: insurancePolicyCreateSchema, update: insurancePolicyUpdateSchema },
    permit: { create: permitCreateSchema, update: permitUpdateSchema },
    location: { create: locationCreateSchema, update: locationUpdateSchema },
    client_invoice: { create: clientInvoiceCreateSchema, update: clientInvoiceUpdateSchema },
    recurring_invoice: {
        create: recurringInvoiceCreateSchema,
        update: recurringInvoiceUpdateSchema,
    },
    dispatch: { create: dispatchCreateSchema, update: dispatchUpdateSchema },
    vendor_review: { create: vendorReviewCreateSchema, update: vendorReviewUpdateSchema },
    automation: { create: automationCreateSchema, update: automationUpdateSchema },
    call_sheet: { create: callSheetCreateSchema, update: callSheetUpdateSchema },
    case_study: { create: caseStudyCreateSchema, update: caseStudyUpdateSchema },
    checklist: { create: checklistCreateSchema, update: checklistUpdateSchema },
    clause: { create: clauseCreateSchema, update: clauseUpdateSchema },
    credential: { create: credentialCreateSchema, update: credentialUpdateSchema },
    credit_note: { create: creditNoteCreateSchema, update: creditNoteUpdateSchema },
    account: { create: accountCreateSchema, update: accountUpdateSchema },
    person: { create: personCreateSchema, update: personUpdateSchema },

    // ─── Financial Domain ────────────────────────────────────────
    payment: { create: paymentCreateSchema, update: paymentUpdateSchema },
    gl_account: { create: glAccountCreateSchema, update: glAccountUpdateSchema },
    revenue_schedule: { create: revenueScheduleCreateSchema, update: revenueScheduleUpdateSchema },
    budget_line_item: { create: budgetLineItemCreateSchema, update: budgetLineItemUpdateSchema },
    job_cost_entry: { create: jobCostEntryCreateSchema, update: jobCostEntryUpdateSchema },
    payment_approval: { create: paymentApprovalCreateSchema, update: paymentApprovalUpdateSchema },
    budget_approval: { create: budgetApprovalCreateSchema, update: budgetApprovalUpdateSchema },
    production_expense: {
        create: productionExpenseCreateSchema,
        update: productionExpenseUpdateSchema,
    },
    production_budget_line: {
        create: productionBudgetLineCreateSchema,
        update: productionBudgetLineUpdateSchema,
    },
    payroll_batch: { create: payrollBatchCreateSchema, update: payrollBatchUpdateSchema },
    expense_report: { create: expenseReportCreateSchema, update: expenseReportUpdateSchema },
    invoice_template: { create: invoiceTemplateCreateSchema, update: invoiceTemplateUpdateSchema },

    // ─── Assets & Inventory Domain ──────────────────────────────
    digital_asset: { create: digitalAssetCreateSchema, update: digitalAssetUpdateSchema },
    asset_assignment: { create: assetAssignmentCreateSchema, update: assetAssignmentUpdateSchema },
    vehicle: { create: vehicleCreateSchema, update: vehicleUpdateSchema },
    warehouse: { create: warehouseCreateSchema, update: warehouseUpdateSchema },
    consumable: { create: consumableCreateSchema, update: consumableUpdateSchema },
    consumable_usage: { create: consumableUsageCreateSchema, update: consumableUsageUpdateSchema },
    maintenance_record: {
        create: maintenanceRecordCreateSchema,
        update: maintenanceRecordUpdateSchema,
    },

    // ─── Production Domain ──────────────────────────────────────
    production_task: { create: productionTaskCreateSchema, update: productionTaskUpdateSchema },
    production_milestone: {
        create: productionMilestoneCreateSchema,
        update: productionMilestoneUpdateSchema,
    },
    production_sop: { create: productionSopCreateSchema, update: productionSopUpdateSchema },
    production_checklist: {
        create: productionChecklistCreateSchema,
        update: productionChecklistUpdateSchema,
    },
    production_time_entry: {
        create: productionTimeEntryCreateSchema,
        update: productionTimeEntryUpdateSchema,
    },

    // ─── HR & Workforce Domain ──────────────────────────────────
    crew_availability: {
        create: crewAvailabilityCreateSchema,
        update: crewAvailabilityUpdateSchema,
    },
    shift: { create: shiftCreateSchema, update: shiftUpdateSchema },
    timesheet: { create: timesheetCreateSchema, update: timesheetUpdateSchema },
    worker_review: { create: workerReviewCreateSchema, update: workerReviewUpdateSchema },
    worker_onboarding_run: {
        create: workerOnboardingRunCreateSchema,
        update: workerOnboardingRunUpdateSchema,
    },
    worker_offboarding_run: {
        create: workerOffboardingRunCreateSchema,
        update: workerOffboardingRunUpdateSchema,
    },
    goal: { create: goalCreateSchema, update: goalUpdateSchema },
    project_assignment: {
        create: projectAssignmentCreateSchema,
        update: projectAssignmentUpdateSchema,
    },
    live_crew_assignment: {
        create: liveCrewAssignmentCreateSchema,
        update: liveCrewAssignmentUpdateSchema,
    },

    // ─── Scheduling & Calendar Domain ───────────────────────────
    calendar_event: { create: calendarEventCreateSchema, update: calendarEventUpdateSchema },
    schedule_entry: { create: scheduleEntryCreateSchema, update: scheduleEntryUpdateSchema },
    resource_booking: { create: resourceBookingCreateSchema, update: resourceBookingUpdateSchema },

    // ─── Contracts & Legal Domain ───────────────────────────────
    contract_obligation: {
        create: contractObligationCreateSchema,
        update: contractObligationUpdateSchema,
    },
    ip_right: { create: ipRightCreateSchema, update: ipRightUpdateSchema },
    e_signature: { create: eSignatureCreateSchema, update: eSignatureUpdateSchema },

    // ─── Procurement Domain ─────────────────────────────────────
    goods_receipt: { create: goodsReceiptCreateSchema, update: goodsReceiptUpdateSchema },
    rfq: { create: rfqCreateSchema, update: rfqUpdateSchema },
    rate_card: { create: rateCardCreateSchema, update: rateCardUpdateSchema },

    // ─── Engineering & Approvals Domain ─────────────────────────
    engineering_approval: {
        create: engineeringApprovalCreateSchema,
        update: engineeringApprovalUpdateSchema,
    },
    approval_step: { create: approvalStepCreateSchema, update: approvalStepUpdateSchema },

    // ─── Compliance & Safety Domain ─────────────────────────────
    compliance_requirement: {
        create: complianceRequirementCreateSchema,
        update: complianceRequirementUpdateSchema,
    },
    insurance_requirement: {
        create: insuranceRequirementCreateSchema,
        update: insuranceRequirementUpdateSchema,
    },
    risk_assessment: { create: riskAssessmentCreateSchema, update: riskAssessmentUpdateSchema },
    vendor_compliance_document: {
        create: vendorComplianceDocumentCreateSchema,
        update: vendorComplianceDocumentUpdateSchema,
    },

    // ─── Documents & Knowledge Domain ───────────────────────────
    document_template: {
        create: documentTemplateCreateSchema,
        update: documentTemplateUpdateSchema,
    },
    knowledge_base_article: {
        create: knowledgeBaseArticleCreateSchema,
        update: knowledgeBaseArticleUpdateSchema,
    },
    vault_document: { create: vaultDocumentCreateSchema, update: vaultDocumentUpdateSchema },

    // ─── Brand & Creative Domain ────────────────────────────────
    brand_guideline_section: {
        create: brandGuidelineSectionCreateSchema,
        update: brandGuidelineSectionUpdateSchema,
    },
    brief_template: { create: briefTemplateCreateSchema, update: briefTemplateUpdateSchema },
    creative_brief: { create: creativeBriefCreateSchema, update: creativeBriefUpdateSchema },
    creative_review: { create: creativeReviewCreateSchema, update: creativeReviewUpdateSchema },
    campaign_asset: { create: campaignAssetCreateSchema, update: campaignAssetUpdateSchema },
    campaign_channel: { create: campaignChannelCreateSchema, update: campaignChannelUpdateSchema },
    campaign_kpi: { create: campaignKpiCreateSchema, update: campaignKpiUpdateSchema },

    // ─── Stakeholders & Contacts Domain ─────────────────────────
    stakeholder: { create: stakeholderCreateSchema, update: stakeholderUpdateSchema },
    stakeholder_project: {
        create: stakeholderProjectCreateSchema,
        update: stakeholderProjectUpdateSchema,
    },

    // ─── System & Platform Domain ───────────────────────────────
    notification: { create: notificationCreateSchema, update: notificationUpdateSchema },
    comment: { create: commentCreateSchema, update: commentUpdateSchema },
    integration: { create: integrationCreateSchema, update: integrationUpdateSchema },
    saved_view: { create: savedViewCreateSchema, update: savedViewUpdateSchema },
    sop: { create: sopCreateSchema, update: sopUpdateSchema },
    workflow: { create: workflowCreateSchema, update: workflowUpdateSchema },
    project_template: { create: projectTemplateCreateSchema, update: projectTemplateUpdateSchema },
    dashboard_widget: { create: dashboardWidgetCreateSchema, update: dashboardWidgetUpdateSchema },
    report_definition: {
        create: reportDefinitionCreateSchema,
        update: reportDefinitionUpdateSchema,
    },
    invitation: { create: invitationCreateSchema, update: invitationUpdateSchema },
    organization: { create: organizationCreateSchema, update: organizationUpdateSchema },
    data_export_request: {
        create: dataExportRequestCreateSchema,
        update: dataExportRequestUpdateSchema,
    },

    // ─── Audit & Security Domain ────────────────────────────────
    access_audit_log: { create: accessAuditLogCreateSchema, update: accessAuditLogUpdateSchema },
    activity_log_entry: {
        create: activityLogEntryCreateSchema,
        update: activityLogEntryUpdateSchema,
    },
    automation_log: { create: automationLogCreateSchema, update: automationLogUpdateSchema },
    domain_event: { create: domainEventCreateSchema, update: domainEventUpdateSchema },
    login_audit_log: { create: loginAuditLogCreateSchema, update: loginAuditLogUpdateSchema },
    role_change_log: { create: roleChangeLogCreateSchema, update: roleChangeLogUpdateSchema },
    temporary_access_grant: {
        create: temporaryAccessGrantCreateSchema,
        update: temporaryAccessGrantUpdateSchema,
    },

    // ─── Operations & Services Domain ───────────────────────────
    dispatch_entry: { create: dispatchEntryCreateSchema, update: dispatchEntryUpdateSchema },
    obligation: { create: obligationCreateSchema, update: obligationUpdateSchema },
    service_health_check: {
        create: serviceHealthCheckCreateSchema,
        update: serviceHealthCheckUpdateSchema,
    },
    sla_definition: { create: slaDefinitionCreateSchema, update: slaDefinitionUpdateSchema },
    sla_tracking: { create: slaTrackingCreateSchema, update: slaTrackingUpdateSchema },
    resilience_target: {
        create: resilienceTargetCreateSchema,
        update: resilienceTargetUpdateSchema,
    },
    checklist_template: {
        create: checklistTemplateCreateSchema,
        update: checklistTemplateUpdateSchema,
    },
    clause_library_entry: {
        create: clauseLibraryEntryCreateSchema,
        update: clauseLibraryEntryUpdateSchema,
    },
    lost_reason: { create: lostReasonCreateSchema, update: lostReasonUpdateSchema },
    profile: { create: profileCreateSchema, update: profileUpdateSchema },

    // ─── Phase H — Complete Coverage ──────────────────────────────
    activity: { create: activityCreateSchema, update: activityUpdateSchema },
    advance_status_history: {
        create: advanceStatusHistoryCreateSchema,
        update: advanceStatusHistoryUpdateSchema,
    },
    advance_template: { create: advanceTemplateCreateSchema, update: advanceTemplateUpdateSchema },
    asset_tag: { create: assetTagCreateSchema, update: assetTagUpdateSchema },
    asset_version: { create: assetVersionCreateSchema, update: assetVersionUpdateSchema },
    automation_execution: {
        create: automationExecutionCreateSchema,
        update: automationExecutionUpdateSchema,
    },
    automation_rule: { create: automationRuleCreateSchema, update: automationRuleUpdateSchema },
    bom: { create: bomCreateSchema, update: bomUpdateSchema },
    brand: { create: brandCreateSchema, update: brandUpdateSchema },
    contract_amendment: {
        create: contractAmendmentCreateSchema,
        update: contractAmendmentUpdateSchema,
    },
    conversation: { create: conversationCreateSchema, update: conversationUpdateSchema },
    credential_assignment: {
        create: credentialAssignmentCreateSchema,
        update: credentialAssignmentUpdateSchema,
    },
    credential_inventory_pool: {
        create: credentialInventoryPoolCreateSchema,
        update: credentialInventoryPoolUpdateSchema,
    },
    credential_type: { create: credentialTypeCreateSchema, update: credentialTypeUpdateSchema },
    custom_field: { create: customFieldCreateSchema, update: customFieldUpdateSchema },
    custom_field_definition: {
        create: customFieldDefinitionCreateSchema,
        update: customFieldDefinitionUpdateSchema,
    },
    dashboard: { create: dashboardCreateSchema, update: dashboardUpdateSchema },
    depreciation_schedule: {
        create: depreciationScheduleCreateSchema,
        update: depreciationScheduleUpdateSchema,
    },
    document_version: { create: documentVersionCreateSchema, update: documentVersionUpdateSchema },
    foh_zone: { create: fohZoneCreateSchema, update: fohZoneUpdateSchema },
    foh_zone_reading: { create: fohZoneReadingCreateSchema, update: fohZoneReadingUpdateSchema },
    guest_incident: { create: guestIncidentCreateSchema, update: guestIncidentUpdateSchema },
    hr_certification: { create: hrCertificationCreateSchema, update: hrCertificationUpdateSchema },
    inventory_audit: { create: inventoryAuditCreateSchema, update: inventoryAuditUpdateSchema },
    kit: { create: kitCreateSchema, update: kitUpdateSchema },
    legal_hold: { create: legalHoldCreateSchema, update: legalHoldUpdateSchema },
    live_event_instance: {
        create: liveEventInstanceCreateSchema,
        update: liveEventInstanceUpdateSchema,
    },
    live_financial_snapshot: {
        create: liveFinancialSnapshotCreateSchema,
        update: liveFinancialSnapshotUpdateSchema,
    },
    load_plan: { create: loadPlanCreateSchema, update: loadPlanUpdateSchema },
    message: { create: messageCreateSchema, update: messageUpdateSchema },
    post_event_report: { create: postEventReportCreateSchema, update: postEventReportUpdateSchema },
    production_advance: {
        create: productionAdvanceCreateSchema,
        update: productionAdvanceUpdateSchema,
    },
    production_advance_item: {
        create: productionAdvanceItemCreateSchema,
        update: productionAdvanceItemUpdateSchema,
    },
    production_run: { create: productionRunCreateSchema, update: productionRunUpdateSchema },
    production_vertical: {
        create: productionVerticalCreateSchema,
        update: productionVerticalUpdateSchema,
    },
    provider_connection: {
        create: providerConnectionCreateSchema,
        update: providerConnectionUpdateSchema,
    },
    qc_gate: { create: qcGateCreateSchema, update: qcGateUpdateSchema },
    quality_check: { create: qualityCheckCreateSchema, update: qualityCheckUpdateSchema },
    quality_check_template: {
        create: qualityCheckTemplateCreateSchema,
        update: qualityCheckTemplateUpdateSchema,
    },
    review: { create: reviewCreateSchema, update: reviewUpdateSchema },
    review_cycle: { create: reviewCycleCreateSchema, update: reviewCycleUpdateSchema },
    scan_event: { create: scanEventCreateSchema, update: scanEventUpdateSchema },
    scenario: { create: scenarioCreateSchema, update: scenarioUpdateSchema },
    space_booking: { create: spaceBookingCreateSchema, update: spaceBookingUpdateSchema },
    storage_object: { create: storageObjectCreateSchema, update: storageObjectUpdateSchema },
    strike_sequence: { create: strikeSequenceCreateSchema, update: strikeSequenceUpdateSchema },
    survey_response: { create: surveyResponseCreateSchema, update: surveyResponseUpdateSchema },
    survey_template: { create: surveyTemplateCreateSchema, update: surveyTemplateUpdateSchema },
    sync_event: { create: syncEventCreateSchema, update: syncEventUpdateSchema },
    technical_spec: { create: technicalSpecCreateSchema, update: technicalSpecUpdateSchema },
    testimonial: { create: testimonialCreateSchema, update: testimonialUpdateSchema },
    time_off_request: { create: timeOffRequestCreateSchema, update: timeOffRequestUpdateSchema },
    vendor_communication: {
        create: vendorCommunicationCreateSchema,
        update: vendorCommunicationUpdateSchema,
    },
    vip_guest: { create: vipGuestCreateSchema, update: vipGuestUpdateSchema },
    vip_service_request: {
        create: vipServiceRequestCreateSchema,
        update: vipServiceRequestUpdateSchema,
    },
    work_package: { create: workPackageCreateSchema, update: workPackageUpdateSchema },
    worker_classification: {
        create: workerClassificationCreateSchema,
        update: workerClassificationUpdateSchema,
    },
    worker_compliance_doc: {
        create: workerComplianceDocCreateSchema,
        update: workerComplianceDocUpdateSchema,
    },

    // ─── Remediation R1 — 22 Missing Schemas ─────────────────────
    account_health_score: {
        create: accountHealthScoreCreateSchema,
        update: accountHealthScoreUpdateSchema,
    },
    approval_workflow: {
        create: approvalWorkflowCreateSchema,
        update: approvalWorkflowUpdateSchema,
    },
    catalog_category: { create: catalogCategoryCreateSchema, update: catalogCategoryUpdateSchema },
    catalog_item: { create: catalogItemCreateSchema, update: catalogItemUpdateSchema },
    channel_template: { create: channelTemplateCreateSchema, update: channelTemplateUpdateSchema },
    comm_channel: { create: commChannelCreateSchema, update: commChannelUpdateSchema },
    command_position: { create: commandPositionCreateSchema, update: commandPositionUpdateSchema },
    compliance_template: {
        create: complianceTemplateCreateSchema,
        update: complianceTemplateUpdateSchema,
    },
    email_message: { create: emailMessageCreateSchema, update: emailMessageUpdateSchema },
    engagement_term: { create: engagementTermCreateSchema, update: engagementTermUpdateSchema },
    environmental_reading: {
        create: environmentalReadingCreateSchema,
        update: environmentalReadingUpdateSchema,
    },
    equipment_check_in: {
        create: equipmentCheckInCreateSchema,
        update: equipmentCheckInUpdateSchema,
    },
    inventory_reservation: {
        create: inventoryReservationCreateSchema,
        update: inventoryReservationUpdateSchema,
    },
    knowledge_article: {
        create: knowledgeArticleCreateSchema,
        update: knowledgeArticleUpdateSchema,
    },
    logistics_event: { create: logisticsEventCreateSchema, update: logisticsEventUpdateSchema },
    maintenance_schedule: {
        create: maintenanceScheduleCreateSchema,
        update: maintenanceScheduleUpdateSchema,
    },
    pos_transaction: { create: posTransactionCreateSchema, update: posTransactionUpdateSchema },
    revenue_recognition_entry: {
        create: revenueRecognitionEntryCreateSchema,
        update: revenueRecognitionEntryUpdateSchema,
    },
    sla_policy: { create: slaPolicyCreateSchema, update: slaPolicyUpdateSchema },
    time_tracking_policy: {
        create: timeTrackingPolicyCreateSchema,
        update: timeTrackingPolicyUpdateSchema,
    },
    upsell_event: { create: upsellEventCreateSchema, update: upsellEventUpdateSchema },
    upsell_trigger: { create: upsellTriggerCreateSchema, update: upsellTriggerUpdateSchema },
    department: { create: departmentCreateSchema, update: departmentUpdateSchema },
    lead_source: { create: leadSourceCreateSchema, update: leadSourceUpdateSchema },
};

/**
 * Look up the validation schemas for a given entity name.
 * Supports both snake_case DB names and kebab-case URL slugs.
 */
export function getSchemasForEntity(entityName: string): SchemaEntry | undefined {
    const normalized = entityName.toLowerCase().replace(/-/g, "_");
    return SCHEMA_REGISTRY[normalized];
}

/**
 * Get all registered entity names.
 */
export function getRegisteredEntities(): string[] {
    return Object.keys(SCHEMA_REGISTRY);
}
