import {
    LayoutDashboard,
    Filter,
    Users,
    FolderKanban,
    CheckSquare,
    CalendarDays,
    HardHat,
    Package,
    Truck,
    Palette,
    Presentation,
    ShieldCheck,
    Store,
    Receipt,
    ShoppingCart,
    UserCircle,
    GitBranch,
    BookOpen,
    Lock,
    Settings,
    Award,
    BarChart3,
    MapPin,
    Sparkles,
    Calendar,
    FileText,
    DollarSign,
    AlertTriangle,
    Warehouse,
    FileSignature,
    ClipboardList,
    Cpu,
    LayoutTemplate,
    Zap,
    Shield,
    Clock,
    Palmtree,
    TrendingUp,
    CreditCard,
    LayoutList,
    Banknote,
    ReceiptText,
    RefreshCw,
    ScrollText,
    FlaskConical,
    ClipboardCheck,
    UserPlus,
    ShieldAlert,
    Star,
    Navigation,
    ListChecks,
    Calculator,
    Inbox,
    UsersRound,
    Target,
    Handshake,
    Building2,
    ArrowRightLeft,
    Scale,
    BadgeCheck,
    HardDriveDownload,
    Wrench,
    ClipboardMinus,
    Fingerprint,
    BookLock,
    FileBadge,
    CircleDollarSign,
    KeyRound,
    ShieldQuestion,
    Radio,
    Megaphone,
    Gauge,
    Thermometer,
    Drama,
    Crown,
    ArrowLeftRight,
    FileBarChart,
    Image,
    HeartPulse,
    Download,
    type LucideIcon,
} from "lucide-react";

export interface NavItem {
    title: string;
    path: string;
    icon: LucideIcon;
    badge?: string | number;
    permission?: string;
    children?: NavItem[];
}

export interface NavSection {
    title: string;
    items: NavItem[];
    defaultExpanded?: boolean;
}

export const navigationConfig: NavSection[] = [
    {
        title: "Command Center",
        defaultExpanded: true,
        items: [
            { title: "Dashboard", path: "/dashboard", icon: LayoutDashboard, permission: "dashboard.read" },
            { title: "Calendar", path: "/calendar", icon: CalendarDays, permission: "calendar.read" },
            { title: "Reports", path: "/reports", icon: BarChart3, permission: "reports.read" },
            { title: "Forecasting", path: "/forecasting", icon: TrendingUp, permission: "forecasting.read" },
            { title: "Scenarios", path: "/scenarios", icon: FlaskConical, permission: "scenarios.read" },
            { title: "Saved Views", path: "/saved-views", icon: LayoutList, permission: "saved_views.read" },
            { title: "Dashboards", path: "/dashboards", icon: LayoutList, permission: "dashboards.read" },
        ],
    },
    {
        title: "CRM & Revenue",
        defaultExpanded: true,
        items: [
            { title: "Pipeline", path: "/pipeline", icon: Filter, permission: "pipeline.read" },
            { title: "Leads", path: "/leads", icon: UserPlus, permission: "leads.read" },
            { title: "Opportunities", path: "/opportunities", icon: Target, permission: "opportunities.read" },
            { title: "Accounts", path: "/accounts", icon: Building2, permission: "accounts.read" },
            { title: "Contacts", path: "/companies", icon: Users, permission: "people.read" },
            { title: "Deals", path: "/deals", icon: Handshake, permission: "deals.read" },
            { title: "Revenue", path: "/revenue", icon: DollarSign, permission: "revenue.read" },
            { title: "Change Orders", path: "/change-orders", icon: ArrowRightLeft, permission: "change_orders.read" },
            { title: "Case Studies", path: "/case-studies", icon: Award, permission: "case_studies.read" },
            { title: "Service Requests", path: "/service-requests", icon: Inbox, permission: "service_requests.read" },
        ],
    },
    {
        title: "Production",
        defaultExpanded: true,
        items: [
            { title: "Projects", path: "/projects", icon: FolderKanban, permission: "projects.read" },
            { title: "Locations", path: "/locations", icon: MapPin, permission: "locations.read" },
            { title: "Activations", path: "/activations", icon: Sparkles, permission: "activations.read" },
            { title: "Events", path: "/events", icon: Calendar, permission: "events.read" },
            { title: "Tasks", path: "/tasks", icon: CheckSquare, permission: "tasks.read" },
            { title: "Scopes of Work", path: "/scopes-of-work", icon: ScrollText, permission: "sow.read" },
            { title: "Schedule", path: "/scheduling", icon: CalendarDays, permission: "schedule.read" },
        ],
    },
    {
        title: "Resources",
        defaultExpanded: false,
        items: [
            { title: "Crew", path: "/crew", icon: HardHat, permission: "crew.read" },
            { title: "Time Tracking", path: "/time-tracking", icon: Clock, permission: "time_tracking.read" },
            { title: "Time Off", path: "/time-off", icon: Palmtree, permission: "time_off.read" },
            { title: "Assets", path: "/assets", icon: Package, permission: "assets.read" },
            { title: "Inventory", path: "/inventory", icon: Warehouse, permission: "inventory.read" },
            { title: "Fleet", path: "/fleet", icon: Truck, permission: "fleet.read" },
            { title: "Resource Planner", path: "/resource-planner", icon: CalendarDays, permission: "resource_planner.read" },
        ],
    },
    {
        title: "Logistics",
        defaultExpanded: false,
        items: [
            { title: "Shipments", path: "/shipments", icon: Truck, permission: "shipments.read" },
            { title: "Warehouses", path: "/warehouses", icon: Warehouse, permission: "warehouses.read" },
        ],
    },
    {
        title: "Creative",
        defaultExpanded: false,
        items: [
            { title: "Briefs", path: "/briefs", icon: FileText, permission: "creative_briefs.read" },
            { title: "Brand Guidelines", path: "/brand-guidelines", icon: Palette, permission: "brand_guidelines.read" },
            { title: "Campaigns", path: "/campaigns", icon: Target, permission: "campaigns.read" },
            { title: "Creative Assets", path: "/creative-assets", icon: Sparkles, permission: "creative_reviews.read" },
            { title: "Digital Assets", path: "/digital-assets", icon: Image, permission: "digital_assets.read" },
            { title: "Brand Kit", path: "/brand-kit", icon: Palette, permission: "brand.read" },
            { title: "Decks", path: "/decks", icon: Presentation, permission: "decks.read" },
            { title: "Templates", path: "/templates", icon: LayoutTemplate, permission: "templates.read" },
        ],
    },
    {
        title: "Documents",
        defaultExpanded: false,
        items: [
            { title: "Documents", path: "/documents", icon: FileText, permission: "documents.read" },
            { title: "Call Sheets", path: "/call-sheets", icon: ClipboardList, permission: "call_sheets.read" },
            { title: "Tech Sheets", path: "/tech-sheets", icon: Cpu, permission: "tech_sheets.read" },
            { title: "Proposals", path: "/proposals", icon: FileText, permission: "proposals.read" },
        ],
    },
    {
        title: "Finance",
        defaultExpanded: false,
        items: [
            { title: "Overview", path: "/finance", icon: DollarSign, permission: "finance.read" },
            { title: "Budgets", path: "/budgets", icon: DollarSign, permission: "budgets.read" },
            { title: "Rate Cards", path: "/rate-cards", icon: CreditCard, permission: "rate_cards.read" },
            { title: "Client Invoices", path: "/client-invoices", icon: FileText, permission: "client_invoices.read" },
            { title: "Invoices", path: "/invoices", icon: FileText, permission: "invoices.read" },
            { title: "Payments", path: "/payments", icon: Banknote, permission: "payments.read" },
            { title: "Credit Notes", path: "/credit-notes", icon: ReceiptText, permission: "credit_notes.read" },
            { title: "Recurring Invoices", path: "/recurring-invoices", icon: RefreshCw, permission: "recurring_invoices.read" },
            { title: "Expenses", path: "/expenses", icon: Receipt, permission: "expenses.read" },
            { title: "Estimates", path: "/estimates", icon: FileSignature, permission: "estimates.read" },
            { title: "Job Costing", path: "/job-costing", icon: Calculator, permission: "job_costing.read" },
            { title: "GL Accounts", path: "/gl-accounts", icon: CircleDollarSign, permission: "gl_accounts.read" },
            { title: "Budget Approvals", path: "/budget-approvals", icon: ShieldCheck, permission: "budget_approvals.read" },
            { title: "Payment Approvals", path: "/payment-approvals", icon: ShieldCheck, permission: "payment_approvals.read" },
            { title: "Vendors", path: "/vendors", icon: Store, permission: "vendors.read" },
            { title: "Procurement", path: "/procurement", icon: ShoppingCart, permission: "procurement.read" },
            { title: "Purchase Requisitions", path: "/purchase-requisitions", icon: ClipboardList, permission: "purchase_requisitions.read" },
            { title: "Goods Receipts", path: "/goods-receipts", icon: HardDriveDownload, permission: "goods_receipts.read" },
            { title: "Vendor Risk", path: "/vendor-risk", icon: Scale, permission: "vendor_risk.read" },
        ],
    },
    {
        title: "Vendor Management",
        defaultExpanded: false,
        items: [
            { title: "Work Orders", path: "/work-orders", icon: ClipboardCheck, permission: "work_orders.read" },
            { title: "Dispatch", path: "/dispatch", icon: Navigation, permission: "dispatch.read" },
            { title: "Vendor Onboarding", path: "/vendor-onboarding", icon: UserPlus, permission: "vendor_onboarding.read" },
            { title: "Vendor Compliance", path: "/vendor-compliance", icon: ShieldAlert, permission: "vendor_compliance.read" },
            { title: "Vendor Reviews", path: "/vendor-reviews", icon: Star, permission: "vendor_reviews.read" },
            { title: "Checklists", path: "/checklists", icon: ListChecks, permission: "checklists.read" },
        ],
    },
    {
        title: "Workforce",
        defaultExpanded: false,
        items: [
            { title: "Directory", path: "/workforce", icon: UsersRound, permission: "workforce.read" },
            { title: "Onboarding / Offboarding", path: "/workforce/onboarding", icon: UserPlus, permission: "workforce_onboarding.read" },
            { title: "Performance Reviews", path: "/workforce/reviews", icon: Star, permission: "workforce_reviews.read" },
        ],
    },
    {
        title: "Legal",
        defaultExpanded: false,
        items: [
            { title: "Contracts", path: "/contracts", icon: FileSignature, permission: "contracts.read" },
            { title: "Insurance Policies", path: "/insurance-policies", icon: Shield, permission: "insurance_policies.read" },
            { title: "IP & Usage Rights", path: "/ip-rights", icon: Fingerprint, permission: "ip_rights.read" },
            { title: "Clause Library", path: "/clause-library", icon: BookLock, permission: "clause_library.read" },
            { title: "Obligations", path: "/obligations", icon: ClipboardMinus, permission: "obligations.read" },
        ],
    },
    {
        title: "Safety & Compliance",
        defaultExpanded: false,
        items: [
            { title: "Incidents", path: "/incidents", icon: AlertTriangle, permission: "incidents.read" },
            { title: "Permits & Licenses", path: "/permits", icon: FileBadge, permission: "permits.read" },
            { title: "Engineering Approvals", path: "/engineering-approvals", icon: Wrench, permission: "engineering_approvals.read" },
            { title: "Compliance Checklists", path: "/compliance-checklists", icon: ListChecks, permission: "compliance_checklists.read" },
            { title: "Certifications", path: "/certifications", icon: BadgeCheck, permission: "certifications.read" },
            { title: "Approvals", path: "/approvals", icon: ShieldCheck, permission: "approvals.read" },
            { title: "Automations", path: "/automations", icon: Zap, permission: "automations.read" },
        ],
    },
    {
        title: "Live Operations",
        defaultExpanded: false,
        items: [
            { title: "Command Dashboard", path: "/live-ops", icon: Radio, permission: "live_events.read" },
            { title: "Run of Show", path: "/live-ops/run-of-show", icon: Megaphone, permission: "ros_cues.read" },
            { title: "Readiness Gates", path: "/live-ops/readiness", icon: Gauge, permission: "readiness_gates.read" },
            { title: "Department Status", path: "/live-ops/departments", icon: LayoutList, permission: "department_statuses.read" },
            { title: "Live Crew", path: "/live-ops/crew", icon: HardHat, permission: "live_crew.read" },
            { title: "Equipment", path: "/live-ops/equipment", icon: Package, permission: "equipment_check_ins.read" },
            { title: "Comms", path: "/live-ops/comms", icon: Radio, permission: "comm_channels.read" },
            { title: "Environment", path: "/live-ops/environment", icon: Thermometer, permission: "environmental_readings.read" },
            { title: "Financials", path: "/live-ops/financials", icon: DollarSign, permission: "live_financial.read" },
            { title: "Front of House", path: "/live-ops/foh", icon: Drama, permission: "foh_zones.read" },
            { title: "VIP Management", path: "/live-ops/vip", icon: Crown, permission: "vip_guests.read" },
            { title: "Guest Incidents", path: "/live-ops/guest-incidents", icon: AlertTriangle, permission: "guest_incidents.read" },
            { title: "Strike & Load-Out", path: "/live-ops/strike", icon: ArrowLeftRight, permission: "strike_sequences.read" },
            { title: "Reconciliation", path: "/live-ops/reconciliation", icon: ClipboardCheck, permission: "asset_reconciliation.read" },
            { title: "Post-Event Reports", path: "/live-ops/reports", icon: FileBarChart, permission: "post_event_reports.read" },
        ],
    },
    {
        title: "Portals",
        defaultExpanded: false,
        items: [
            { title: "Client Portal", path: "/client-portal", icon: Users, permission: "client_portal.read" },
            { title: "Vendor Portal", path: "/vendor-portal", icon: Store, permission: "vendor_portal.read" },
        ],
    },
    {
        title: "User Management",
        defaultExpanded: false,
        items: [
            { title: "Users", path: "/user-management", icon: UsersRound, permission: "user_management.read" },
            { title: "Invitations", path: "/user-management/invitations", icon: UserPlus, permission: "invitations.read" },
            { title: "Access Reviews", path: "/user-management/access-reviews", icon: ShieldQuestion, permission: "access_reviews.read" },
            { title: "Audit Log", path: "/user-management/audit-log", icon: KeyRound, permission: "audit_log.read" },
        ],
    },
    {
        title: "Organization",
        defaultExpanded: false,
        items: [
            { title: "People", path: "/people", icon: UserCircle, permission: "people.read" },
            { title: "Org Chart", path: "/org-chart", icon: GitBranch, permission: "org_chart.read" },
            { title: "Knowledge Base", path: "/knowledge-base", icon: BookOpen, permission: "kb.read" },
            { title: "SOPs", path: "/sops", icon: FileText, permission: "sops.read" },
            { title: "Vault", path: "/vault", icon: Lock, permission: "vault.read" },
            { title: "Roles", path: "/roles", icon: Shield, permission: "roles.manage" },
            { title: "Settings", path: "/settings", icon: Settings, permission: "settings.manage" },
            { title: "System Health", path: "/system-health", icon: HeartPulse, permission: "system_health.read" },
            { title: "Data Export", path: "/data-export", icon: Download, permission: "data_export.read" },
        ],
    },
];
