/**
 * Page Load Time Measurement — MOVED
 *
 * The browser console measurement script is now in:
 *   docs/PAGE_LOAD_PERFORMANCE_AUDIT.md § Section 8
 *
 * This file retains the sidebar page path inventory for reference.
 */

// ── All sidebar-navigable paths (extracted from navigation.ts) ──

const SIDEBAR_PAGES: { section: string; title: string; path: string }[] = [
    // Home
    { section: "Home", title: "Dashboard", path: "/dashboard" },
    { section: "Home", title: "Tasks (Home)", path: "/home/tasks" },
    { section: "Home", title: "Documents (Home)", path: "/home/documents" },
    { section: "Home", title: "Calendar", path: "/calendar" },
    { section: "Home", title: "Messages", path: "/messages" },
    { section: "Home", title: "Notifications", path: "/notifications" },
    { section: "Home", title: "Reports", path: "/reports" },
    { section: "Home", title: "Forecasting", path: "/forecasting" },
    { section: "Home", title: "Scenarios", path: "/scenarios" },
    { section: "Home", title: "AI Reports", path: "/reports/ai" },
    { section: "Home", title: "Saved Views", path: "/saved-views" },
    { section: "Home", title: "Custom Dashboards", path: "/dashboards" },
    { section: "Home", title: "Report Builder", path: "/report-definitions" },

    // Business
    { section: "Business", title: "Pipeline", path: "/pipeline" },
    { section: "Business", title: "Leads", path: "/leads" },
    { section: "Business", title: "Opportunities", path: "/opportunities" },
    { section: "Business", title: "Accounts", path: "/accounts" },
    { section: "Business", title: "Contacts", path: "/companies" },
    { section: "Business", title: "Stakeholders", path: "/stakeholders" },
    { section: "Business", title: "Deals", path: "/deals" },
    { section: "Business", title: "Proposals", path: "/proposals" },
    { section: "Business", title: "Estimates", path: "/estimates" },
    { section: "Business", title: "Change Orders", path: "/change-orders" },
    { section: "Business", title: "Lost Reasons", path: "/lost-reasons" },
    { section: "Business", title: "Upsell Events", path: "/upsell-events" },
    { section: "Business", title: "Upsell Triggers", path: "/upsell-triggers" },

    // Production
    { section: "Production", title: "Projects", path: "/projects" },
    { section: "Production", title: "Events", path: "/events" },
    { section: "Production", title: "Activations", path: "/activations" },
    { section: "Production", title: "Tasks", path: "/tasks" },
    { section: "Production", title: "Scopes of Work", path: "/scopes-of-work" },
    { section: "Production", title: "Bills of Materials", path: "/boms" },
    { section: "Production", title: "Schedule", path: "/scheduling" },
    { section: "Production", title: "Locations", path: "/locations" },
    { section: "Production", title: "Advancing", path: "/advancing" },
    { section: "Production", title: "New Advance", path: "/advancing/new" },
    { section: "Production", title: "Approval Queue", path: "/advancing/queue" },
    { section: "Production", title: "Fulfillment", path: "/advancing/fulfillment" },
    { section: "Production", title: "Catalog", path: "/advancing/catalog" },
    { section: "Production", title: "Inventory", path: "/advancing/inventory" },
    { section: "Production", title: "Adv Templates", path: "/advancing/templates" },
    { section: "Production", title: "Adv Reports", path: "/advancing/reports" },
    { section: "Production", title: "Status History", path: "/advance-status-history" },

    // Operations
    { section: "Operations", title: "Approvals", path: "/approvals" },
    { section: "Operations", title: "Approval Workflows", path: "/approval-workflows" },
    { section: "Operations", title: "Checklists", path: "/checklists" },
    { section: "Operations", title: "Checklist Templates", path: "/checklist-templates" },
    { section: "Operations", title: "Automations", path: "/automations" },
    { section: "Operations", title: "Quality Checks", path: "/quality-checks" },
    { section: "Operations", title: "QC Templates", path: "/quality-check-templates" },
    { section: "Operations", title: "QC Gates", path: "/qc-gates" },
    { section: "Operations", title: "Service Requests", path: "/service-requests" },
    { section: "Operations", title: "SLA Dashboard", path: "/service-requests/sla" },
    { section: "Operations", title: "SLA Definitions", path: "/sla-definitions" },
    { section: "Operations", title: "Workflows", path: "/workflows" },
    { section: "Operations", title: "Documents", path: "/documents" },
    { section: "Operations", title: "Call Sheets", path: "/call-sheets" },
    { section: "Operations", title: "Tech Sheets", path: "/tech-sheets" },
    { section: "Operations", title: "Templates", path: "/templates" },
    { section: "Operations", title: "Email", path: "/email-messages" },
    { section: "Operations", title: "Resilience", path: "/resilience-targets" },

    // Workforce
    { section: "Workforce", title: "Crew", path: "/crew" },
    { section: "Workforce", title: "Time Tracking", path: "/time-tracking" },
    { section: "Workforce", title: "TT Compliance", path: "/time-tracking/compliance" },
    { section: "Workforce", title: "Time Entries", path: "/time-entries" },
    { section: "Workforce", title: "Timesheets", path: "/timesheets" },
    { section: "Workforce", title: "Time Off", path: "/time-off" },
    { section: "Workforce", title: "Time Off Requests", path: "/time-off-requests" },
    { section: "Workforce", title: "Resource Planner", path: "/resource-planner" },
    { section: "Workforce", title: "Shifts", path: "/shifts" },
    { section: "Workforce", title: "Availability", path: "/crew-availability" },
    { section: "Workforce", title: "Certifications", path: "/certifications" },
    { section: "Workforce", title: "Workforce", path: "/workforce" },
    { section: "Workforce", title: "Onboarding/Offboarding", path: "/workforce/onboarding" },
    { section: "Workforce", title: "Performance Reviews", path: "/workforce/reviews" },
    { section: "Workforce", title: "Goals & OKRs", path: "/workforce/goals" },
    { section: "Workforce", title: "Vendors", path: "/vendors" },
    { section: "Workforce", title: "Vendor Onboarding", path: "/vendor-onboarding" },
    { section: "Workforce", title: "Vendor Compliance", path: "/vendor-compliance" },
    { section: "Workforce", title: "Vendor Reviews", path: "/vendor-reviews" },
    { section: "Workforce", title: "Work Orders", path: "/work-orders" },

    // Resources
    { section: "Resources", title: "Assets", path: "/assets" },
    { section: "Resources", title: "Asset Scanner", path: "/assets/scan" },
    { section: "Resources", title: "Batch Scanner", path: "/assets/scan/batch" },
    { section: "Resources", title: "Maintenance", path: "/maintenance-schedules" },
    { section: "Resources", title: "Transfer Orders", path: "/transfer-orders" },
    { section: "Resources", title: "Inventory", path: "/inventory" },
    { section: "Resources", title: "Warehouses", path: "/warehouses" },
    { section: "Resources", title: "Shipments", path: "/shipments" },
    { section: "Resources", title: "Fleet", path: "/fleet" },
    { section: "Resources", title: "Dispatch", path: "/dispatch" },
    { section: "Resources", title: "Purchase Orders", path: "/purchase-orders" },
    { section: "Resources", title: "Expense Reports", path: "/expense-reports" },

    // Creative
    { section: "Creative", title: "Briefs", path: "/briefs" },
    { section: "Creative", title: "Brand Guidelines", path: "/brand-guidelines" },
    { section: "Creative", title: "Creative Assets", path: "/creative-assets" },
    { section: "Creative", title: "Digital Assets", path: "/digital-assets" },
    { section: "Creative", title: "Brand Kit", path: "/brand-kit" },
    { section: "Creative", title: "Decks", path: "/decks" },
    { section: "Creative", title: "Creative Reviews", path: "/creative-reviews" },
    { section: "Creative", title: "Campaigns", path: "/campaigns" },
    { section: "Creative", title: "Case Studies", path: "/case-studies" },
    { section: "Creative", title: "Surveys", path: "/surveys" },
    { section: "Creative", title: "Testimonials", path: "/testimonials" },

    // Finance
    { section: "Finance", title: "Overview", path: "/finance" },
    { section: "Finance", title: "Revenue", path: "/revenue" },
    { section: "Finance", title: "Revenue Recognition", path: "/finance/revenue-recognition" },
    { section: "Finance", title: "Expenses", path: "/expenses" },
    { section: "Finance", title: "Invoices", path: "/invoices" },
    { section: "Finance", title: "Client Invoices", path: "/client-invoices" },
    { section: "Finance", title: "Payments", path: "/payments" },
    { section: "Finance", title: "Credit Notes", path: "/credit-notes" },
    { section: "Finance", title: "Recurring Invoices", path: "/recurring-invoices" },
    { section: "Finance", title: "Budgets", path: "/budgets" },
    { section: "Finance", title: "Job Costing", path: "/job-costing" },
    { section: "Finance", title: "Rate Cards", path: "/rate-cards" },
    { section: "Finance", title: "Milestones", path: "/milestones" },
    { section: "Finance", title: "Payroll Runs", path: "/payroll-batches" },
    { section: "Finance", title: "Financial Periods", path: "/financial-periods" },
    { section: "Finance", title: "GL Accounts", path: "/gl-accounts" },
    { section: "Finance", title: "Budget Approvals", path: "/budget-approvals" },
    { section: "Finance", title: "Payment Approvals", path: "/payment-approvals" },
    { section: "Finance", title: "Procurement", path: "/procurement" },
    { section: "Finance", title: "Purchase Requisitions", path: "/purchase-requisitions" },
    { section: "Finance", title: "Goods Receipts", path: "/goods-receipts" },
    { section: "Finance", title: "Vendor Risk", path: "/vendor-risk" },

    // Legal
    { section: "Legal", title: "Contracts", path: "/contracts" },
    { section: "Legal", title: "Insurance", path: "/insurance-policies" },
    { section: "Legal", title: "IP & Usage Rights", path: "/ip-rights" },
    { section: "Legal", title: "Clause Library", path: "/clause-library" },
    { section: "Legal", title: "Obligations", path: "/obligations" },
    { section: "Legal", title: "Incidents", path: "/incidents" },
    { section: "Legal", title: "Permits & Licenses", path: "/permits" },
    { section: "Legal", title: "Engineering Approvals", path: "/engineering-approvals" },
    { section: "Legal", title: "Compliance Checklists", path: "/compliance-checklists" },

    // Admin
    { section: "Admin", title: "Users", path: "/user-management" },
    { section: "Admin", title: "Invitations", path: "/user-management/invitations" },
    { section: "Admin", title: "Access Reviews", path: "/user-management/access-reviews" },
    { section: "Admin", title: "Audit Log", path: "/user-management/audit-log" },
    { section: "Admin", title: "People", path: "/people" },
    { section: "Admin", title: "Org Chart", path: "/org-chart" },
    { section: "Admin", title: "Teams", path: "/teams" },
    { section: "Admin", title: "Roles", path: "/roles" },
    { section: "Admin", title: "Knowledge Base", path: "/knowledge-base" },
    { section: "Admin", title: "SOPs", path: "/sops" },
    { section: "Admin", title: "Vault", path: "/vault" },
    { section: "Admin", title: "Settings", path: "/settings" },
    { section: "Admin", title: "Security", path: "/settings/security" },
    { section: "Admin", title: "Custom Fields", path: "/settings/custom-fields" },
    { section: "Admin", title: "Developer Portal", path: "/settings/developer" },
    { section: "Admin", title: "Email Integration", path: "/settings/email-integration" },
    { section: "Admin", title: "Notification Prefs", path: "/settings/notifications" },
    { section: "Admin", title: "AI Copilot Settings", path: "/settings/ai" },
    { section: "Admin", title: "Tags", path: "/tags" },
    { section: "Admin", title: "Integrations", path: "/integrations" },
    { section: "Admin", title: "Sync Log", path: "/integrations/sync-log" },
    { section: "Admin", title: "Marketplace", path: "/integrations/marketplace" },
    { section: "Admin", title: "System Health", path: "/system-health" },
    { section: "Admin", title: "Data Export", path: "/data-export" },
    { section: "Admin", title: "Credentials", path: "/credentials" },
    { section: "Admin", title: "Cred Assignments", path: "/credentials/assignments" },
    { section: "Admin", title: "Client Portal", path: "/client-portal" },
    { section: "Admin", title: "Vendor Portal", path: "/vendor-portal" },

    // Live Operations
    { section: "Live Ops", title: "Command Dashboard", path: "/live-ops" },
    { section: "Live Ops", title: "Run of Show", path: "/live-ops/run-of-show" },
    { section: "Live Ops", title: "Readiness Gates", path: "/live-ops/readiness" },
    { section: "Live Ops", title: "Department Status", path: "/live-ops/departments" },
    { section: "Live Ops", title: "Live Crew", path: "/live-ops/crew" },
    { section: "Live Ops", title: "Equipment", path: "/live-ops/equipment" },
    { section: "Live Ops", title: "Comms", path: "/live-ops/comms" },
    { section: "Live Ops", title: "Environment", path: "/live-ops/environment" },
    { section: "Live Ops", title: "Financials", path: "/live-ops/financials" },
    { section: "Live Ops", title: "Front of House", path: "/live-ops/foh" },
    { section: "Live Ops", title: "Credentials (Live)", path: "/live-ops/credentials" },
    { section: "Live Ops", title: "Gate Scanner", path: "/live-ops/gate" },
    { section: "Live Ops", title: "VIP Management", path: "/live-ops/vip" },
    { section: "Live Ops", title: "Guest Incidents", path: "/live-ops/guest-incidents" },
    { section: "Live Ops", title: "Strike & Load-Out", path: "/live-ops/strike" },
    { section: "Live Ops", title: "Reconciliation", path: "/live-ops/reconciliation" },
    { section: "Live Ops", title: "Post-Event Reports", path: "/live-ops/reports" },
];

export { SIDEBAR_PAGES };
